### PR TITLE
Update innernet to 1.4.0

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
@LinusCDE or @matteodelabre could you review this?

**Comment by matteodelabre** [comment]
@Eeems Do you have experience with innernet? I tried to follow the official docs to set up a local network between my computer and the tablet, but I can’t seem to add a new peer in the network after creating it. I’m not sure whether I should set up wireguard first or if innernet is supposed to take care of everything?

**Comment by Eeems** [comment]
Internet is suppose to take care of everything, but you can run into trouble with NAT holepunching not being robust enough. I've had no issues with it when I've used it on my rM1, but I also modify the file to make sure it's using an internal IP to connect to my server instead of an external one.

**Comment by matteodelabre** [comment]
Finally managed to make it work. Thanks for the help!

**Review by matteodelabre — APPROVED** [review]

**Pull request merged**
