### PR TITLE
Update display and rm2fb-client to v0.0.29

### PR DESCRIPTION
**Pull request by NeilInnes**
Update display and rm2fb-client to v0.0.29
https://github.com/ddvk/remarkable2-framebuffer/releases/tag/v0.0.29

Fixes bug with Remarkable desktop app screen share freezing: https://github.com/ddvk/remarkable2-framebuffer/issues/71

Adds support for the following OS versions:

- 2.14.4.46
- 3.0.2.1253
- 3.0.4.1305
- ~3.1.0.1346~

### CODE REVIEW

**Comment by lakano** [comment]
Hi ! 
Any news on this PR please? I'm waiting it to permit to install it on version 3.0.4.1305 :-)

**Comment by Eeems** [comment]
> Hi ! Any news on this PR please? I'm waiting it to permit to install it on version 3.0.4.1305 :-)

https://github.com/ddvk/remarkable2-framebuffer/issues/118

**Comment by icedream** [comment]
Works fine on 3.0.4.1305 for me.

**Comment by Eeems** [comment]
Okay with the current testing, I'm going to merge this, but not indicate that it adds 3.1.0.1346 support since that is broken. We'll still have to wait on ddvk-hacks being updated to say we support 3.x though.

**Review by Eeems — APPROVED** [review]

**Comment by icedream** [comment]
Posting this here for who isn't on Discord but I missed out on this while originally testing this.

xochitl crashes with a `Segmentation fault` on the new package versions, however all other apps seem to work fine with this version.


Possibly something wrong with the library that is preloaded via `/opt/etc/xochitl.env.d/rm2fb-preload.env`?

**Comment by Eeems** [comment]
> Posting this here for who isn't on Discord but I missed out on this while originally testing this.
> 
> xochitl crashes with a `Segmentation fault` on the new package versions, however all other apps seem to work fine with this version.
> 
> Possibly something wrong with the library that is preloaded via `/opt/etc/xochitl.env.d/rm2fb-preload.env`?

Have you read https://github.com/ddvk/remarkable2-framebuffer/issues/118 yet? This was already known. I'm guessing you are testing on 3.1+?

**Comment by icedream** [comment]
No, I was commenting earlier in https://github.com/toltec-dev/toltec/pull/656#issuecomment-1426916068 that I tested on 3.0.4.1305, that is still the case.

To be very clear: I tested whether Oxide launches on display/rm2fb-client 0.0.29 without a custom `/opt/etc/rm2fb.conf` in place which it does, it boots all the way to the launcher screen. That's how far I tested it at first.

However, then trying to start xochitl will cause the reMarkable logo to appear and then the app crashes with said `Segmentation fault`. Downgrading to 0.0.27 from the repo and restoring `/opt/etc/rm2fb.conf` with the content below fixes this issue.

```
!20221208102714
version str 3.0.4.1305
update addr 0x552f74
updateType str QRect
create addr 0x5560b0
shutdown addr 0x556040
wait addr 0x554f58
getInstance addr 0x549674
```

**Comment by icedream** [comment]
Figured out the culprit: https://github.com/ddvk/remarkable2-framebuffer/commit/958b57c7e2b8f3c01d3e7f4314ccf7d09688ae34.

There is a [comment on that commit pointing out the correct fix for 3.0.4.1305](https://github.com/ddvk/remarkable2-framebuffer/commit/958b57c7e2b8f3c01d3e7f4314ccf7d09688ae34#commitcomment-97824454).

**Pull request merged**
