### PR TITLE
Update ddvk-hacks to 18.01

### PR DESCRIPTION
**Pull request by matteodelabre**
This update includes the following patch changes:

* For rM1 2.5.0.27, update patch 17.1.04 to 17.1.10
* For rM2 2.5.0.27, update patch 17.2.04 to 17.2.07
* Add rM2 2.5.1.45 with patch 18.2.01

This is also a good time to test the upgrade path for the ddvk-hacks package. Test plan:

* Install the previous ddvk-hacks version (17.04) and then upgrade to 18.01.
* On rM1, the upgrade output should be as follows:

```console
Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...

Restoring the original Xochitl binary

Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
Configuring ddvk-hacks.

Device: reMarkable 1
Xochitl version: 2.5.0.27
Patch version: 17.1.10

Patching Xochitl
Please restart Xochitl to use the patches
```

* On rM2, the upgrade output should be as follows:

```console
Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...

Restoring the original Xochitl binary

Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
Configuring ddvk-hacks.

Device: reMarkable 2
Xochitl version: 2.5.0.27
Patch version: 17.2.07

Patching Xochitl
Please restart Xochitl to use the patches
```

* On rM1 and rM2, make sure Xochitl does not crash when your restart it after the new patch is applied.

My rM2 has not received the 2.5.1.45 update yet, so I cannot test the 18.2.01 patch. I’d be grateful if someone could test it.

### CODE REVIEW

**Comment by matteodelabre** [comment]
(See https://github.com/ddvk/remarkable-hacks/issues/240#issuecomment-798941159)

**Comment by Eeems** [comment]
```shell
reMarkable: ~/ opkg install packages/ddvk-hacks/ddvk-hacks_18.01-1_armv7-3.2.ipk 
Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...

Restoring the original Xochitl binary before upgrading

Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
Configuring ddvk-hacks.

Device: reMarkable 1
Xochitl version: 2.5.0.27
Patch version: 17.1.10

Patching Xochitl
Please restart Xochitl to use the patches
```
2021-03-14T173955 269
LGTM on my rM1 (Also, that email is already public so I'm not worried).

**Comment by Eeems** [comment]
I think we are just waiting on someone with a rM2? @LinusCDE @raisjn @danshick ?

**Review by LinusCDE — APPROVED** [review]
Works fine :+1:

**Comment by matteodelabre** [comment]
@LinusCDE Thanks for testing! Are you on rM2 2.5.0.27 or 2.5.1.45?

**Comment by LinusCDE** [comment]
Only rM2 2.5.0.27. I guess someone should still test it with the newer version.

**Comment by Baccanno** [comment]
> This update includes the following patch changes:
> 
> * For rM1 2.5.0.27, update patch 17.1.04 to 17.1.10
> * For rM2 2.5.0.27, update patch 17.2.04 to 17.2.07
> * Add rM2 2.5.1.45 with patch 18.2.01
> 
> This is also a good time to test the upgrade path for the ddvk-hacks package. Test plan:
> 
> * Install the previous ddvk-hacks version (17.04) and then upgrade to 18.01.
> * On rM1, the upgrade output should be as follows:
> 
> ```
> Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...
> 
> Restoring the original Xochitl binary
> 
> Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
> Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
> Configuring ddvk-hacks.
> 
> Device: reMarkable 1
> Xochitl version: 2.5.0.27
> Patch version: 17.1.10
> 
> Patching Xochitl
> Please restart Xochitl to use the patches
> ```
> 
> * On rM2, the upgrade output should be as follows:
> 
> ```
> Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...
> 
> Restoring the original Xochitl binary
> 
> Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
> Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
> Configuring ddvk-hacks.
> 
> Device: reMarkable 2
> Xochitl version: 2.5.0.27
> Patch version: 17.2.07
> 
> Patching Xochitl
> Please restart Xochitl to use the patches
> ```
> 
> * On rM1 and rM2, make sure Xochitl does not crash when your restart it after the new patch is applied.
> 
> My rM2 has not received the 2.5.1.45 update yet, so I cannot test the 18.2.01 patch. I’d be grateful if someone could test it.

My RM2 is 2.5.1.45, so I'll try it soon. 
I installed it with automagick, should I uninstall it before trying it with toltec as suggested in the ddvk's thread ?
Regards

**Comment by Eeems** [comment]
> My RM2 is 2.5.1.45, so I'll try it soon.
> I installed it with automagick, should I uninstall it before trying it with toltec as suggested in the ddvk's thread ?
> Regards

Yes, installing on top of the automagick script will fail as we expect a specific file hash to be in place: https://github.com/toltec-dev/toltec/blob/5d15171f995dd4a8425fd339f28f40a621d0f824/package/ddvk-hacks/package#L143-L148

**Comment by Eeems** [comment]
Any progress on this?

**Comment by matteodelabre** [comment]
We just need someone to test on version 2.5.1. @Baccanno said he would do so soon.

**Comment by Baccanno** [comment]
Sorry did not had the time yet, a bit underwater nowadays.

**Comment by Baccanno** [comment]
```

opkg install packages/ddvk-hacks/ddvk-hacks_18.01-1_armv7-3.2.ipk
Collected errors:
 * wfopen: packages/ddvk-hacks/ddvk-hacks_18.01-1_armv7-3.2.ipk: No such file or directory.
```
Where should I find the package ?

**Comment by Eeems** [comment]
> 
> 
> ```
> 
> opkg install packages/ddvk-hacks/ddvk-hacks_18.01-1_armv7-3.2.ipk
> Collected errors:
>  * wfopen: packages/ddvk-hacks/ddvk-hacks_18.01-1_armv7-3.2.ipk: No such file or directory.
> ```
> 
> Where should I find the package ?

You'll need to copy it to your device and use the path of where you copied it to.

**Comment by Baccanno** [comment]
This file ?
`https://github.com/toltec-dev/toltec/blob/package/ddvk-hacks-18.01/package/ddvk-hacks/package`

Basically I don't know where the branched ipk is

**Comment by Baccanno** [comment]
That does not seems like it. Looks like I need to built the repo myself yet I'm sorry but I don't have the toolchain installed. Anyone care to share a prebuild ipk ?

**Comment by Eeems** [comment]
https://github.com/toltec-dev/toltec/pull/317/checks?check_run_id=2111554987
image

**Comment by Baccanno** [comment]
@Eeems Great this is what was missing, I'm not used to github CI.

```
opkg install plugins/ddvk-hacks_18.01-1_armv7-3.2.ipk
Upgrading ddvk-hacks on root from 17.04-1 to 18.01-1...

Restoring the original Xochitl binary
Warning: Xochitl binary has changed!
Not restoring the backup

Removing obsolete file /opt/share/ddvk-hacks/patch_17.1.04.
Removing obsolete file /opt/share/ddvk-hacks/patch_17.2.04.
Configuring ddvk-hacks.

Device: reMarkable 2
Xochitl version: 2.5.1.45
Patch version: 18.2.01

Patching Xochitl
Please restart Xochitl to use the patches
```
I confirm it works :)
`Version 2.5.1.45-patch_18.2.1-0-g0e703ad`

Removal as well, got back to stock "2.5.1.45"

**Comment by Eeems** [comment]
@matteodelabre are we good to merge?

**Comment by matteodelabre** [comment]
Yes! Sorry I did not see @Baccanno’s answer before.

**Pull request merged**
