### PR TITLE
package/linux-mainline: Bump to 6.2

### PR DESCRIPTION
**Pull request by alistair23**
Bump the mainline based kernel to the ~~6.1~~ 6.2 release.

Besides the mainline changes from 6.0 to 6.2, this includes a refactoring of the `rohm,bd71815` code to use the mainline driver instead of the reMarkable version. It has also dropped a Koreader related hack from the kernel, see https://github.com/koreader/koreader/issues/10012.

This is the ~~6.1~~ 6.2 mainline kernel and ~~18~~ 12 rM2 specific patches on top.

### CODE REVIEW

**Comment by Etn40ff** [comment]
I just ran this on `20221026104022`. There are a couple of issues:

- a ⚠️ symbol appears next to the battery indicator in xochitl

- I get the following messages in `dmesg`

```
[   15.287260] UDC core: g_ether: couldn't find an available UDC or it's busy
[  231.122624] evbug: Event. Dev: input1, Type: 1, Code: 330, Value: 0
[  231.122635] evbug: Event. Dev: input1, Type: 0, Code: 0, Value: 0
[  234.253718] usbmisc_imx 30b20200.usbmisc: vbus is error
[  234.253764] usbmisc_imx 30b20200.usbmisc: Error occurs during detection: -22
```
  actually `dmesg` output is spammed with `evbug`s messages.

Other than that all seems to be in order.

**Comment by alistair23** [comment]
Weird. I don't see those.

```shell
dmesg | grep g_ether    
[    3.610858] UDC core: g_ether: couldn't find an available UDC
[    4.899438] g_ether gadget.0: Ethernet Gadget, version: Memorial Day 2008
[    4.906347] g_ether gadget.0: g_ether ready
```

After a reboot do you still see the battery warning sign?

**Comment by Etn40ff** [comment]
I do but the message buffer is not spammed by them and ethernet over usb works:
```
reMarkable: ~/ dmesg | grep g_ether
[    2.620511] UDC core: g_ether: couldn't find an available UDC
[    3.493576] g_ether gadget.0: Ethernet Gadget, version: Memorial Day 2008
[    3.493599] g_ether gadget.0: g_ether ready
[   13.885486] UDC core: g_ether: couldn't find an available UDC or it's busy
```

Here are some pictures of the warning signs:

signal-2023-01-19-133447_002
signal-2023-01-19-133442

**Comment by alistair23** [comment]
Ok! Pushed an update to go all the way to the 6.2 kernel.

I double checked and in Xochitl 2.9.0.210 I don't see any warning signs for the battery. Let me know if you still see anything, although I think that's a Xochitl bug as we are now using the upstream driver for the power management

**Comment by Etn40ff** [comment]
I just gave this another spin. I still get the weird error symbol in 2.15.1.1189 but other than that it works as intended.

**Comment by alistair23** [comment]
I think this should be merged then. We can work on the warning symbol in the future

**Comment by alistair23** [comment]
Ping!

**Comment by alistair23** [comment]
Ping!

**Comment by Eeems** [comment]
I'd be happy to merge it if one of the maintainers with a rM2 is okay with that. @raisjn @matteodelabre @LinusCDE ?

**Comment by alistair23** [comment]
Anyone?

**Comment by alistair23** [comment]
Another ping

**Comment by alistair23** [comment]
Ping!

**Comment by Eeems** [comment]
I've asked the question a number of times on discord and had no reply about it, other than @LinusCDE saying he didn't think he was the right person to answer.

**Comment by Eeems** [comment]
@LinusCDE I think it would be fine for you to approve this at this point.

**Review by LinusCDE — APPROVED** [review]
Will rubber stamp, but have not done testing on custom kernels yet. If some unknown issue crops up, i can probably find the time to look into it.

**Comment by Eeems** [comment]
> Will rubber stamp, but have not done testing on custom kernels yet. If some unknown issue crops up, i can probably find the time to look into it.

To clarify, I'm not looking for a rubber stamp. I'm looking for an explicit statement that you are comfortable or not with the battery warning when running this on 2.15.

**Comment by LinusCDE** [comment]
Was initially not sure, because it involves battery seemingly. I doubt that the kernel would need to do any crucial control for it, but on the rM 2 it's usually hard to say what they did in the name of making stuff sleeker and more responsive.

In this case I doubt it's an issue though. Looking at the dmesg log, the problem doesn't seem to be battery but actually the UDC, which according to [this documenation](https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt) should mean USB Device Controller. At first I thought this should not matter to the reMarkable anyway.

But in one way I would: The ethernet interface. Can someone confirm that the Ethernet functionality still works normally? If not I should have probably not approved it. Otherwise I think it should be fine.

**Comment by Eeems** [comment]
@Etn40ff since you are the one who can replicate, can you take a look?

**Comment by Etn40ff** [comment]
> @Etn40ff since you are the one who can replicate, can you take a look?

I do not have my recovery gear with me at the moment; I will not be able to test this again before mid September.

**Comment by alistair23** [comment]
I use the Ethernet interface fairly often. I'm pretty sure it works fine with the 6.2 kernel

**Comment by LinusCDE** [comment]
Then there should be no issue merging this i guess. :+1:

**Comment by Eeems** [comment]
Alright, good enough for me, I guess. Merging.

**Pull request merged**
