### PR TITLE
Update rm2fb to v0.0.4

### PR DESCRIPTION
**Pull request by matteodelabre**
This update includes a change in the server code to set the server process name to 'rm2fb-server' (instead of the default 'xochitl'). See also #359 and rmkit-dev/rmkit#127. I also removed Toltec’s patch to set `argv[0]` since it’s included in upstream now.

Test plan: Started the 'rm2fb' service, retrieved the server PID, and made sure that both `/proc/PID/cmdline` and `/proc/PID/stat` contained 'rm2fb-server' instead of 'xochitl'.

### CODE REVIEW

**Comment by Eeems** [comment]
Installed fine for me on rM1 with no bad side effects.

**Comment by JanLuca** [comment]
Installed and works fine for me on rM2. Thank you for updating the package!

**Review by raisjn — APPROVED** [review]
(based on jan's testing)

**Comment by matteodelabre** [comment]
Thanks all for providing additional testing.

**Pull request merged**
