### PR TITLE
Add various Templates

### PR DESCRIPTION
**Pull request by Eeems**
Add the following templates:

- template-daily-planner
- template-weekly-planner
- template-journal
- template-meeting-notes
- template-smart-goals
- template-good-time-journal

### CODE REVIEW

**Comment by TheSunCat** [comment]
The templates do not show up after installing until you reboot, or disable chroot for xochitl and manually start `usr-share-remarkable-templates.mount` with systemctl.

**Comment by Eeems** [comment]
> The templates do not show up after installing until you reboot, or disable chroot for xochitl and manually start `usr-share-remarkable-templates.mount` with systemctl.

All of which are unrelated to these template packages themselves. After install, which the bind mount working, do they all show up properly? And do they appear properly when using them?

**Comment by TheSunCat** [comment]
After installing all of them and rebooting to get them to show, they all show up and work fine. Some notes:

- Daily Planner: top left has text, which interferes with the interface and it becomes hard to read. The icon has an extra horizontal line which causes it not to match the look of it.
- Good Time Journal: icon has nothing to do with the template
- Journal: same issue as Daily Planner
- Meeting Notes: same issue as Daily Planner; icon does not really match the layout
- Smart Goals: icon looks nothing like it
- Weekly Planner: icon dos not match

**Comment by Eeems** [comment]
Could you suggest some icon codes that would better match the content? We are limited with what icons can be selected, so sometimes the closest one isn't a good representation of the actual content.
https://web.archive.org/web/20230129163327/https://remarkablewiki.com/tips/templates#specifications

**Comment by TheSunCat** [comment]
Aw, it's unfortunate these are hardcoded. I'll add my suggestions for each.

**Review by Jayy001 — APPROVED** [review]

**Pull request merged**
