### PR TITLE
Stable merge for week 15 of 2022

### PR DESCRIPTION
**Pull request by matteodelabre**
This stable merge brings support for reMarkable OS releases 2.12.2 and 2.12.3.

New packages
------------

* `toltec-base` - 1.0-1 (#532)
    - Metapackage used for specifying the default-installed packages
* `open-remarkable-shutdown` - 1.0-1 (#532)
    - Overrides the `remarkable-shutdown` and `remarkable-reboot` default configurations to use `remarkable-splash` instead of the stock utility
    - Fixes custom poweroff/reboot screens not working on rM1
    - Will be installed by default on rM1

Updated packages
----------------

* `ddvk-hacks` - 32.02-1 (#579, #584)
    - Add support for 2.12.2
    - Add support for 2.12.3
* `display` - 1:0.0.16-1 (#578, #585)
    - Add support for rM2 2.12.2
    - Add support for rM2 2.12.3
* `keywriter` - 0.2~20-gddc9e73-1 (#565)
    - Reduce font size in edit mode
    - Set default buffer orientation to portrait
    - Rotate the buffer using Ctrl-Left/Ctrl-Right in view mode
    - Add Ctrl-Q shortcut to quit the app
    - Restore cursor position when switching between modes
* `koreader` - 2022.03.1-1 (#562, #574, #575)
    - Don't use KOReader suspend/screensaver/autosuspend when Oxide is running
    - [2022.03.1 release notes](https://github.com/koreader/koreader/releases/tag/v2022.03.1)
    - [2022.03 release notes](https://github.com/koreader/koreader/releases/tag/v2022.03)
    - [2022.02 release notes](https://github.com/koreader/koreader/releases/tag/v2022.02)
* `toltec-bootstrap` - 0.2.2-1 (#532)
    - Add transient dependency on `toltec-base` for existing installs
* `xochitl` - 0.0.0-13 (#532, #567)
    - Make sure xochitl starts after/stops before the launcher
    - Force creating/removing the launcher.service alias when needed
    - Fix spurious warning when no pre-scripts are available for xochitl (e.g., on rM1)
    - Add transient dependency on `toltec-base` for existing installs
* `rmfakecloud-proxy` - 0.0.3-3 (#561)
    - Add timeout to `status` command in case the upstream server is unreachable
    - Show feedback to the user while the upstream server is being pinged
* `harmony` - 0.2.0-1 (#572)
    - Add layer support
    - Fix segfaults when showing empty load/import dialogs
    - Exporting canvas to PNG supports grays instead of dithering
    - RLE snapshots for history (less memory usage)
    - Support SYN_DROPPED in wacom events
* `remux` - 0.2.2-1 (#572)
    - RLE snapshots use less memory
    - Save BPP when screenshotting current app
    - Filter palm events from gestures (less false positives)
    - Support SYN_DROPPED in wacom events

### CODE REVIEW

**Comment by matteodelabre** [comment]
Build for `folly` is failing because of canselcik/libremarkable#103. I’m excluding that package’s update from this merge, since it is a minor update anyway.

**Review by LinusCDE — APPROVED** [review]
Tested all packages on rM 2 (using fw 2.12.3.606) and they seem to work great!

Note: The [softbrick warning](https://toltec-dev.org/#install-toltec) on the website can be bumped to 2.12.3.606 or removed with this merge.

**Comment by Eeems** [comment]
> Note: The [softbrick warning](https://toltec-dev.org/#install-toltec) on the website can be bumped to 2.12.3.606 or removed with this merge.

Not removed, just bumped. Having the warning helps avoid issues with people using the beta trying to install toltec.

**Comment by matteodelabre** [comment]
Thanks Linus! I’ll test it on rM1 this evening and then we can merge this.

**Comment by LinusCDE** [comment]
> Not removed, just bumped. Having the warning helps avoid issues with people using the beta trying to install toltec.

Top! Wasn't sure which was our current strategy. Hence the "or".

**Comment by matteodelabre** [comment]
Testing on rM1, I found that Oxide doesn’t behave well when an external keyboard is plugged in before boot. KOReader and harmony (and maybe some other apps) do not receive touch input (but Xochitl does). The buttons below the screen have no effect and cannot be used to go back to Oxide or to launch the task manager.

This should not block this merge, though. I reported this to the Oxide repo (Eeems-org/oxide#259).

**Comment by matteodelabre** [comment]
No other issues found, we can merge this!

**Pull request merged**
