### PR TITLE
add python package based on prebuilt tgz

### PR DESCRIPTION
**Pull request by SomethingGeneric**
Hi! I hope this an acceptable addition to toltec, rather than entware.
Obviously I'm not the author of Python :sweat_smile: 
This should:tm: work for both devices.

### CODE REVIEW

**Comment by SomethingGeneric** [comment]
I apologize also if there are rules for wether to build in-tree with docker, but containers are far above me :sweat:

**Comment by Eeems** [comment]
We do prefer building in-tree. There is a tool you can use to help with testing package recipes called toltecmk that you can install from pypi. You can find more info in the toltec-dev/build repo.

You can also look at other recipes in the repo for examples on how to do various builds.

**Comment by Eeems** [comment]
Oh, and what would the reason be to have python in toltec instead of using the one that comes from the entware repositories?

**Comment by SomethingGeneric** [comment]
> Oh, and what would the reason be to have python in toltec instead of using the one that comes from the entware repositories?

Mfw I didn't see that entware has python3. I guess the GUI package manager didn't fuzzy search correctly. Nevermind 😅

**Pull request closed without merging**
