### PR TITLE
[rmkit] update remux with fix for broken wifi on suspend

### PR DESCRIPTION
**Pull request by raisjn**
this update fixes broken wifi on resume from suspend in remux

Test Plan:

* invoke suspend through remux's bottom right corner. 
* wake tablet up by pressing power button
* verify that network comes back up within a couple minutes (look at xochitl's network bar or use `ping` command, etc)

### CODE REVIEW

**Review by LinusCDE — CHANGES_REQUESTED** [review]
The wifi seems to work well for me (though the old version also worked well when following your steps).

A thing I guess I also omitted, was that the PR I made needs the icons added here.

The lines of the icons can be found in this diff (only the changes in package() sections): https://github.com/LinusCDE/toltec/compare/beac3d3...ce47601

**Review by LinusCDE — APPROVED** [review]

**Comment by Eeems** [comment]
So we need someone to test with a rM2 now right?

**Comment by LinusCDE** [comment]
Would be best, but I think it'll suffice. I'm not sure whether the bug is actually rM 2 exclusive. The build works fine for me, and whether the bug was fixed could've been tested by raisjn anyway.

**Comment by Eeems** [comment]
The suspend issue is rM2 exclusive.

**Comment by raisjn** [comment]
yes, i tested the suspend issue on rM2

**Pull request merged**
