### PR TITLE
Add move-logs-to-opt

### PR DESCRIPTION
**Pull request by Eeems**
This package moves system log files to `/opt/var/log` to free up space on the root partition.

This will require testing on a rM2, including making sure that uninstall works as expected.

### CODE REVIEW

**Comment by Eeems** [comment]
image

**Comment by Eeems** [comment]
Okay this works on my rM2. It's still not a default package as I want others to test as well, but I think it's good to merge as-is.

**Review by bkirwi — DISMISSED** [review]
```
Jan 14 17:49:23 reMarkable systemd[1]: Configuration file /lib/systemd/system/var-log.mount is marked executable. Please remove executable permission bits. Proceeding anyway.
```

Other than this, as far as I can tell this is behaving as expected. Approved.

**Comment by Eeems** [comment]
> ```
> Jan 14 17:49:23 reMarkable systemd[1]: Configuration file /lib/systemd/system/var-log.mount is marked executable. Please remove executable permission bits. Proceeding anyway.
> ```
> 
> Other than this, as far as I can tell this is behaving as expected. Approved.

Whoops! Hows that?

**Review by bkirwi — APPROVED** [review]
:+1:

**Pull request merged**
