### PR TITLE
Update YAFT to v0.0.10

### PR DESCRIPTION
**Pull request by FouzR**
- Physical keyboard key repeat support
- Handle rotation when folio is attached/removed
- Support for F1-F12 keys
- Use shell login to make sure to load user profile

### CODE REVIEW

**Review by Eeems — CHANGES_REQUESTED** [review]
It looks like the `yaft-256color` file is no longer being provided, but it's still the default `TERM` value for yaft. This is breaking opening nano, vi, etc which was previously working due to having that included with the correct `TERMINFO` set. The correct `TERMINFO` is now set though.

**Comment by Eeems** [comment]
@FouzR poke

**Comment by timower** [comment]
For the terminfo files, I moved the install logic to libYaft: https://github.com/timower/rM2-stuff/blob/4174e7c70645285be47f7ab20d83e76fc8fd3835/libs/libYaft/CMakeLists.txt
This means you'll have to `cd libs/libYaft && make install` as well as just installing yaft.

**Comment by FouzR** [comment]
Alright, so I installed the .ipk from the actions

All the noted changes seem to be working, but I don't know what the function keys do except in VIM =P

**Review by Eeems — APPROVED** [review]

**Pull request merged**
