### PR TITLE
Don't grab input in KOReader by default.

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Review by raisjn — DISMISSED** [review]
lgtm

**Comment by Eeems** [comment]
I've added a warning message on install if it detects that Oxide is installed. I tested the logic on device. This doesn't handle showing a warning when Oxide is installed after KOReader though.

**Review by raisjn — APPROVED** [review]
shipit

**Review by matteodelabre — APPROVED** [review]
Tested, can confirm it fixes the issue. Thanks!

**Pull request merged**
