### PR TITLE
Stable merge window for week 07 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
New packages:

* quickjs 2020.11.08-1
* zshelf 0.3.1-1

Tooling:

* Add back `make RECIPE-push` command
* Support auto-extracting `tar`, `tar.bz2`, and `tar.xz` archives

Note that the bootstrap changes for creating the timezone mount and the zoneinfo-utils package are once again left out of this merge since we have yet to move the mount creation into the package.

### CODE REVIEW

**Comment by khanhas** [comment]
Hi, can you let zshelf v0.3.1 merge instead?
v0.2.0 has a bug that user cannot download book.

**Comment by matteodelabre** [comment]
Hi @khanhas, done! Thanks for letting me know.

**Comment by raisjn** [comment]
cc @dixonary, @danshick 

for stable merge, the process is more involved. the process should verify basic functionality of the packages. in this case, zshelf functionality would be browsing and downloading a book (downloading requires a cookie), while quickjs testing is likely running a js script after installation.

i'll likely do this review this evening

**Review by raisjn — APPROVED** [review]
tested zshelf and qjs on rM1 (since khanhas tests on rM2). 

* used a cookie to download a file (49MB, oops) through zshelf. opened file through KOReader, verified it actually opens. see UI indicate i'm at 1/5 downloads for the day
* ran script through qjs, verified basic javascript ran

**Review by matteodelabre — COMMENTED** [review]
I went through the same checks as @raisjn on rM2 and everything worked smoothly. Time to merge!

**Pull request merged**
