### PR TITLE
[rm2fb] update rm2fb with wait ioctl and no-op on rM1

### PR DESCRIPTION
**Pull request by raisjn**
this updates rm2fb with matteo's changes for rM1 compat, as well as adds the wait ioctl support. imo, it will need a bit of testing (locally and from outside people) before we merge it into stable.

### CODE REVIEW

**Review by LinusCDE — DISMISSED** [review]
Seems to work fine. I didn't specifically test the ioctl (I can do that later today).

I think this will be fine though. Just needs a version bump.

**Comment by Eeems** [comment]
> 
> 
> Seems to work fine. I didn't specifically test the ioctl (I can do that later today).
> 
> I think this will be fine though. Just needs a version bump.

Could you test with Oxide to see if it resolves that issue?

**Comment by danshick** [comment]
> Could you test with Oxide to see if it resolves that issue?

I can try it out too. Should I use the 2.1.2 PR? Or the current version in testing?

**Comment by Eeems** [comment]
> 
> 
> > Could you test with Oxide to see if it resolves that issue?
> 
> I can try it out too. Should I use the 2.1.2 PR? Or the current version in testing?

Please test with the 2.1.2 PR.

**Review by danshick — APPROVED** [review]
I've been running this for a while now with no ill effect on rM2. It may contribute to fewer weird sleep screen contentions with oxide/decay, but it is hard to say as they were so intermittent before. It certainly doesn't break anything or cause any form of regression, so I'm good for testing.

Given the nature of this change, someone with an rM1 should also review to ensure the no-op behavior is working.

**Comment by Eeems** [comment]
> It may contribute to fewer weird sleep screen contentions with oxide/decay, but it is hard to say as they were so intermittent before.

Some users were getting them quite often from what I understand.

**Comment by danshick** [comment]
> Some users were getting them quite often from what I understand.

I definitely had times when I had to cycle it to sleep and awake a few times to get back to where I was. I can't recall it happening since this fix so I really do think it is solved (the no pin issue being different, as we've discovered). But I've also disabled sleeping in xochitl, so that could be contributing to it not being problematic. I should go back to defaults for a week to see if it remains solved.

**Review by matteodelabre — APPROVED** [review]
I can confirm that the package is now safe to install on rM1. Some scenarios I tested after installing the updated rm2fb package:

* Enable the `xochitl` service.
* Manually start and wrap `xochitl` with `rm2fb-client`.
* Start Oxide and an launch an app through it.
* Reboot the tablet, make sure it does not go into a bootloop and system rollback.

**Pull request merged**
