### PR TITLE
Stable merge window for week 44 of 2020

### PR DESCRIPTION
**Pull request by matteodelabre**
Tooling changes:

* Migrate to the toltec-dev.org domain
* Implement split packages feature

Updated packages:

* koreader 2020.09.29-2 → 2020.10-1
* harmony 0.0.1-16 → 0.0.1-17 (merged in recipe rmkit)
* mines 0.0.1-14 → 0.0.1-16 (ditto)
* nao 0.0.1-15 → 0.0.1-16 (ditto)
* remux 0.0.1-20 → 0.0.1-23 (ditto)
* simple 0.0.1-15 → 0.0.1-16 (ditto)
* oxide 2.0\~beta-4 → 2.0\~beta-5 (splitted erode, fret, rot, tarnish)

New packages:

* erode 2.0~beta-5 (from split of oxide)
* fret 2.0~beta-5 (from split of oxide)
* rot 2.0~beta-5 (from split of oxide)
* tarnish 2.0~beta-5 (from split of oxide)
* reboot-guard 1.0.1-2

### CODE REVIEW

**Comment by raisjn** [comment]
i'm fine with all of this (being that its the package split changes)

**Comment by Eeems** [comment]
I don't think I'll have a chance to test anything to confirm it works today. It looks good to me though.

**Comment by Eeems** [comment]
Has anybody had a chance to test this?

**Comment by raisjn** [comment]
I've tested KOReader and rmkit apps

**Comment by raisjn** [comment]
I tested `oxide` by running `opkg install oxide`. I don't see a system service for oxide (how does it know to start at boot?), but I do see the service for tarnish. I followed instructions and disabled xochitl and remux and enabled tarnish and then rebooted, but oxide did not start.

I then started oxide by hand and was able to import apps as well as start them. I did notice that upon exiting an application, oxide did not repaint itself and I had to click around a blank screen (maybe this was because how I started oxide)

**Comment by raisjn** [comment]
In testing remux, I noticed that the memory usage analyzer (commit 8a372b7516a0665223d0e63f37ccf59a768e8782) from https://github.com/toltec-dev/toltec/pull/126 is no longer there. It likely got removed in the package split PR, so I will update it again this week.

**Comment by Eeems** [comment]
> 
> 
> I tested `oxide` by running `opkg install oxide`. I don't see a system service for oxide (how does it know to start at boot?), but I do see the service for tarnish. I followed instructions and disabled xochitl and remux and enabled tarnish and then rebooted, but oxide did not start.

Tarnish handles starting oxide. Maybe check the tarnish logs? Also check the tarnish config file `/home/root/.config/eeems/tarnish.conf`
> 
> I then started oxide by hand and was able to import apps as well as start them. I did notice that upon exiting an application, oxide did not repaint itself and I had to click around a blank screen (maybe this was because how I started oxide)

Yes this would be because tarnish isn't handling things.

**Comment by matteodelabre** [comment]
I’ll hold back merging rmkit recipes together as per @raisjn’s request.

**Comment by matteodelabre** [comment]
Tested:

- [x] koreader 2020.10-1
- [x] oxide 2.0~beta-5
- [x] erode 2.0~beta-5
- [x] fret 2.0~beta-5
- [x] rot 2.0~beta-5
- [x] tarnish 2.0~beta-5
- [x] reboot-guard 1.0.1-2

**Comment by matteodelabre** [comment]
I missed that the reboot-guard 1.0.1-2 package is new in stable and has to be tested. I’ll update my previous messages accordingly.

**Comment by matteodelabre** [comment]
I think everything is in order. Waiting on @raisjn’s second test of oxide.

**Comment by raisjn** [comment]
yes, it works. i had to delete tarnish.conf while tarnish was not running. in all my testing, i had not done that, so i had a bad config that just wouldn't go away

as to why i had a bad config: not sure

oxide is good to go for me

**Review by raisjn — APPROVED** [review]

**Comment by Eeems** [comment]
That's good enough for me. Please open an issue about empty bin= in the config file. That should really be properly cleaned up for system applications.

**Pull request merged**
