### PR TITLE
Update innernet to v1.5.0

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
@plan5 any idea why it's no longer building?

**Comment by plan5** [comment]
> @plan5 any idea why it's no longer building?

Makes no sense to me... I've even copied your package file and built locally without errors. The only difference between #432 and #434 seems to be the timestamp. 

I _am_ using self-compiled build-images for aarch64 though.

**Comment by Eeems** [comment]
I don't believe we ever ran the builds on your PR, so it might not have been building as well. Could it be that rust needs an update?
@matteodelabre thoughts?

**Comment by plan5** [comment]
I've compiled in verbose mode and this is the error that pops up:
http://ix.io/3zw3

Adding `time = "0.3.2"` to the dependencies section of $srcdir/share/Cargo.toml might be a temporary fix and another hint that Eeems is right.

**Comment by Eeems** [comment]
That's the same error we are getting in the pipeline:
```
[   ERROR] toltec.builder: innernet [rmall]: Compiling wireguard-control v1.5.0 (/src/wireguard-control)
[   ERROR] toltec.builder: innernet [rmall]: Compiling shared v1.5.0 (/src/shared)
[   ERROR] toltec.builder: innernet [rmall]: error[E0658]: use of unstable library feature 'duration_constants'
[   ERROR] toltec.builder: innernet [rmall]: --> shared/src/wg.rs:234:24
[   ERROR] toltec.builder: innernet [rmall]: |
[   ERROR] toltec.builder: innernet [rmall]: 234 |             .unwrap_or(Duration::MAX);
[   ERROR] toltec.builder: innernet [rmall]: |                        ^^^^^^^^^^^^^
[   ERROR] toltec.builder: innernet [rmall]: |
[   ERROR] toltec.builder: innernet [rmall]: = note: see issue #57391 <https://github.com/rust-lang/rust/issues/57391> for more information
[   ERROR] toltec.builder: innernet [rmall]: = help: add `#![feature(duration_constants)]` to the crate attributes to enable
[   ERROR] toltec.builder: innernet [rmall]: 
[   ERROR] toltec.builder: innernet [rmall]: error: aborting due to previous error
[   ERROR] toltec.builder: innernet [rmall]: 
[   ERROR] toltec.builder: innernet [rmall]: For more information about this error, try `rustc --explain E0658`.
[   ERROR] toltec.builder: innernet [rmall]: error: could not compile `shared`
```
We probably should get a fix for this upstream in innernet since https://github.com/rust-lang/rust/issues/57391 is still open.

**Comment by matteodelabre** [comment]
Judging from the discussion in the issue you linked, the `Duration::max` constant has been stabilized separately from the other proposed duration constants. So this build error is because the Rust version in our toolchain is outdated. Indeed, I’ve tried to build it with a more recent Rust version and it compiles fine. I’m going to publish an update of the toolchain.

**Comment by matteodelabre** [comment]
Build fixed!

**Comment by Eeems** [comment]
Anybody had time to test and approve so I can merge this?

**Review by raisjn — APPROVED** [review]
unblocking

**Pull request merged**
