### PR TITLE
Stable merge for week 37 of 2024

### PR DESCRIPTION
**Pull request by Eeems**
### Updated Packages
- `kernelctl` - 0.2-1 (#905)
- `whiteboard-hypercard` - 0.5.0-1 (#917)
- `linux-mainline` - 6.3.0-1 (#732)
  - Now available on OS 3.x
- `toltec-deletions` - 6.3.0-1 (#732 #919)

### CODE REVIEW

**Comment by Eeems** [comment]
#919 will also need to be merged in to make sure that testing and stable have the same version number for toltec-deletions.

**Comment by Eeems** [comment]
Waiting for #921

**Comment by Eeems** [comment]
I've tested this all on my rM2 and it's working as expected. I would still not recommend people use linux-mainline on their device, but at least it's not bricking anything.

**Review by LinusCDE — APPROVED** [review]
Rubber stamped :+1:

**Pull request merged**
