### PR TITLE
package/linux-mainline: Bump to 6.0

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by Etn40ff** [comment]
LGTM

**Review by Etn40ff — APPROVED** [review]
LGTM

**Review by Eeems — APPROVED** [review]
Approving based on @Etn40ff's review

**Comment by Eeems** [comment]
@Etn40ff just to confirm, you also tested this right?

**Comment by Etn40ff** [comment]
Meaning your rebase? then no. I tested this @ 09e8431

**Comment by Eeems** [comment]
I didn't do a rebase, just merged in changes that wouldn't have affected the changes in this branch. Since you tested this, I'd be happy to merge it if @alistair23 has no concerns.

**Comment by alistair23** [comment]
No concerns from me

**Pull request merged**
