### PR TITLE
[rmkit] update to all applications, add new apps: dumbskull, rpncalc and wordlet

### PR DESCRIPTION
**Pull request by raisjn**
rmkit:

* rmkit went through a large refactoring, so we update all apps
* fix keyboard layout (swapped O and I keys originally)

dumbskull:

* add new game, "Dumbskull", which is a themed solitaire

genie:

* add palm rejection to genie (thakns Ekalfwons)

iago:

* add settings dialog (@aeneas) that allows snapping

mines:

* fix spurious crash when playing multiple games in a row

remux:

* add dialog_height/dialog_width options to remux.conf
* better memory analysis (of all processes in group, not just main process)
* rm1: remove usb check that keeps it powered indefinitely

rpncalc:

* add new app, rpncalc
* add better spacing and layout
* add push after operation behavior (next input is on new stack element)

wordlet:

* add new game, "Wordlet", which is a wordle clone

### CODE REVIEW

**Comment by raisjn** [comment]
Tested installation and functionality on rM1:

* bufshot - saved screenshot from CLI
* dumbskull - loaded and clicked through a few games
* genie, iago, lamp - drew circles, rect and line
* harmony - loaded saved images from disk, drew a bit with the pen
* mines - installable, can lose multiple games in a row
* nao - can browse entware / toltec packages
* remux - can see memory for all process types (including bash scripts)
* rpncalc - tested a few simple operations, push, drop, etc
* wordlet - played a single game

I have also individually tested each binary on rM2 (but not through the build artifacts)

**Comment by matteodelabre** [comment]
I’ll test this later today. I’m eager to try out your Wordle clone :-)

**Comment by matteodelabre** [comment]
Sorry for the delay. I went through the same testing process as you detailed in your previous message and most of it worked flawlessly! Here are some things I noticed:

* `rpncalc`: conflicts with `calculator` on file `/opt/etc/draft/icons/calculator.png` (we should probably have an automated check for this kind of issue, pinging toltec-dev/build#12).
* `wordlet`: I still see the keyboard letters “O” and “I” in the wrong order.
* `iago`: are the settings saved somewhere? activating the “snap to grid” option doesn’t seem to persist across multiple executions of `iago`

**Comment by raisjn** [comment]
thanks for the thorough testing! oof on wordlet's keyboard :-D i had fixed the swap on all apps with the normal keyboard but wordlet has a custom keyboard. iago settings are not persisting by design, but this is something we can look into

Fixed those the first two issues in https://github.com/rmkit-dev/rmkit/commit/9375bb9b7b66849cc4c1be578be87b563546d5a3 and https://github.com/rmkit-dev/rmkit/commit/5005c3b0552a5e64a506d74ad506bdad4f2b96bc

since this is a big set of changes for me (refactoring how inputs work, how display works, etc), i appreciate the thoroughness on testing

**Review by LinusCDE — APPROVED** [review]
Did quick tests on both models. I really need to learn to play world. Only heard about it, but didn't get to learn/play it yet.

Other apps also seem fine. Didn't test iago and genie beyond basic installation though. So take this review with a grain of salt.

**Pull request merged**
