### PR TITLE
Fix linux-mainline build

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
@alistair23 would you be able to look at this? It looks like the debian image we are using has become unwilling to install the dependencies require for the package to build. I would try to use the v3.1 image, as it will install the dependencies, but it fails to build.

**Comment by alistair23** [comment]
Having a look

**Comment by alistair23** [comment]
Have a look at https://github.com/toltec-dev/toltec/pull/904 hopefully that works

**Comment by Eeems** [comment]
Closed in favour of #904

**Pull request closed without merging**
