### PR TITLE
Update rm2fb to start before launcher.service

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by matteodelabre** [comment]
Thanks for the PR! It looks good, although I’m not sure whether remux should be marked as conflicting with other launchers since it doesn’t show anything on screen unless triggered (thoughts @raisjn?). We could still force it to start after rm2fb by adding `After=rm2fb.service` to the remux service definition.

**Comment by Eeems** [comment]
Remux does conflict with oxide as they both control applications with drastically different mechanisms. So having Oxide and remux run at the same time will have bad side-effects.

**Comment by matteodelabre** [comment]
Yes you’re right, but remux doesn’t conflict with Xochitl, for example. Should we just leave the Conflicts list for the remux unit?

**Comment by Eeems** [comment]
Good point. Although I believe remux assumes that xochitl isn't started before it? Not sure though.

**Comment by matteodelabre** [comment]
If I understand remux correctly, it does not (but @ raisjn can correct me). It will detect that Xochitl (or any other app) is already running by scanning the process list.

**Comment by raisjn** [comment]
remux doesnt conflict with xochitl on purpose (to reduce likelihood of bricking). if xochitl service is started, remux will stop it before launching xochitl. if xochitl is already launched (outside of system service), remux will properly manage it (iirc)

**Comment by matteodelabre** [comment]
I reverted the changes for the remux unit then.

**Review by matteodelabre — APPROVED** [review]

**Pull request merged**
