### PR TITLE
Add recrossable

### PR DESCRIPTION
**Pull request by matteodelabre**
Still need to figure out why the app does not receive pen events.

### CODE REVIEW

**Comment by Eeems** [comment]
It's probably not handling them. Here is what I have to do in oxide to handle most pen events: https://github.com/Eeems/oxide/blob/master/applications/launcher/eventfilter.cpp#L105-L142

**Comment by matteodelabre** [comment]
But surely it is supposed to handle them, because [it ignores touch events](https://github.com/sandsmark/recrossable/blob/master/drawablecell.cpp#L54) and there is no way to interact with the app otherwise. Or am I missing something?

**Comment by Eeems** [comment]
Looks like there is stuff here: https://github.com/sandsmark/recrossable/blob/master/main.cpp#L23

**Comment by matteodelabre** [comment]
It works, but I must be missing something since that workaround is targeted to Qt ⩽ 5.6 and we’re on Qt 5.11.

**Comment by Eeems** [comment]
> 
> 
> It works, but I must be missing something since that workaround is targeted to Qt ⩽ 5.6 and we’re on Qt 5.11.

He likely hasn't tested on the new toolchain and realized that it also needs the workaround.

**Comment by matteodelabre** [comment]
Plausible indeed since the previous Qt version in the toolchain was 5.6.

**Comment by matteodelabre** [comment]
Reported to upstream in sandsmark/recrossable/issues/3.

**Review by Eeems — APPROVED** [review]
lgtm

**Pull request merged**
