### PR TITLE
Update VNSee to 0.4.0 and add launcher files

### PR DESCRIPTION
**Pull request by matteodelabre**
Upstream changelog for v0.4.0:

- Add reMarkable 2 support (depends on [remarkable2-framebuffer](https://github.com/ddvk/remarkable2-framebuffer)).
- Tolerate server resolutions differing from 1404x1872 or 1408x1872.
    - The server image is cropped to fit in the screen.
- Add `vnsee-gui` script to start VNSee from a GUI.
    - This is a [simple](https://rmkit.dev/apps/sas) script.

This PR additionally contains launcher files for Draft, remux, and Oxide that start the `vnsee-gui` script.

Test plan:

* On rM1 and rM2, start `vnsee` directly to connect to a remote VNC server, make sure the screen refreshes properly and that touch/pen interactions work.
* Connect to a VNC server with a wide resolution and make sure VNSee works, cropping the image to fit in the rM screen.
* [On 2.5] Try starting VNSee from Draft, remux, and Oxide. The script should list all VNC servers listening on the USB network. Tapping one of the servers should establish a connection and show the screen.

### CODE REVIEW

**Comment by LinusCDE** [comment]
Currently trying to build this. It is failing on finding the file `///repo/rmall/Package.gz`. Do you know what I did wrong?

Also tried with merging the newest changes from testing. But that had the same result.

<details>

<summary>Output</summary>

```shell
╭─linus@HomeLX /tmp/tol1/toltec  ‹fde8933*› 
╰─$ FLAGS="-v" make vnsee                                                                                                                                                         2 ↵
./scripts/package_build.py -v "vnsee"
r
[   DEBUG] docker.utils.config: Trying paths: ['/home/linus/.docker/config.json', '/home/linus/.dockercfg']
[   DEBUG] docker.utils.config: No config file found
[   DEBUG] docker.utils.config: Trying paths: ['/home/linus/.docker/config.json', '/home/linus/.dockercfg']
[   DEBUG] docker.utils.config: No config file found
[   DEBUG] urllib3.connectionpool: http://localhost:None "GET /version HTTP/1.1" 200 833
[   DEBUG] docker.utils.config: Trying paths: ['/home/linus/.docker/config.json', '/home/linus/.dockercfg']
[   DEBUG] docker.utils.config: No config file found
[   DEBUG] docker.utils.config: Trying paths: ['/home/linus/.docker/config.json', '/home/linus/.dockercfg']
[   DEBUG] docker.utils.config: No config file found
[   DEBUG] urllib3.connectionpool: http://localhost:None "GET /version HTTP/1.1" 200 833
The build directory 'build/package/vnsee' for recipe 'vnsee' already exists.
Would you like to [c]ancel, [r]emove that directory, or [k]eep it (not recommended)? [C/r/k] [    INFO] toltec.builder: vnsee [rmall]: Fetching source files
[   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): github.com:443
[   DEBUG] urllib3.connectionpool: https://github.com:443 "GET /boostorg/preprocessor/archive/5e17804af2496e13ca0cc03d892b5351b637ea43.zip HTTP/1.1" 302 160
[   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): codeload.github.com:443
[   DEBUG] urllib3.connectionpool: https://codeload.github.com:443 "GET /boostorg/preprocessor/zip/5e17804af2496e13ca0cc03d892b5351b637ea43 HTTP/1.1" 200 1521649
[   DEBUG] toltec.builder: vnsee [rmall]: Not extracting /tmp/tol1/toltec/build/package/vnsee/rmall/src/vnsee.draft (unsupported archive type)
[   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): github.com:443
[   DEBUG] urllib3.connectionpool: https://github.com:443 "GET /matteodelabre/vnsee/archive/v0.4.0.zip HTTP/1.1" 302 124
[   DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): codeload.github.com:443
[   DEBUG] urllib3.connectionpool: https://codeload.github.com:443 "GET /matteodelabre/vnsee/zip/v0.4.0 HTTP/1.1" 200 221296
[   DEBUG] toltec.builder: vnsee [rmall]: Not extracting /tmp/tol1/toltec/build/package/vnsee/rmall/src/vnsee-gui-set-path.patch (unsupported archive type)
[   DEBUG] toltec.builder: vnsee [rmall]: Not extracting /tmp/tol1/toltec/build/package/vnsee/rmall/src/VNSee.oxide (unsupported archive type)
[   DEBUG] toltec.builder: vnsee [rmall]: Not extracting /tmp/tol1/toltec/build/package/vnsee/rmall/src/vnsee.png (unsupported archive type)
[    INFO] toltec.builder: vnsee [rmall]: Preparing source files
[   DEBUG] toltec.builder: vnsee [rmall]: patching file vnsee-gui
[    INFO] toltec.builder: vnsee [rmall]: Building artifacts
[   DEBUG] urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/create HTTP/1.1" 201 88
[   DEBUG] urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e/json HTTP/1.1" 200 None
[   DEBUG] urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e/start HTTP/1.1" 204 0
[   DEBUG] urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e/logs?stderr=1&stdout=1&timestamps=0&follow=1&tail=all HTTP/1.1" 200 None
[   DEBUG] urllib3.connectionpool: http://localhost:None "GET /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e/json HTTP/1.1" 200 None
[   DEBUG] toltec.builder: vnsee [rmall]: * opkg_download_file: ///repo/rmall/Packages.gz: No such file.
[   DEBUG] urllib3.connectionpool: http://localhost:None "POST /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e/wait HTTP/1.1" 200 None
[   DEBUG] urllib3.connectionpool: http://localhost:None "DELETE /v1.41/containers/9fb278e90cde742aeee784d9751248d82c702494e748c1c26246d44128d2fb8e?v=False&link=False&force=False HTTP/1.1" 204 0
[   ERROR] toltec.builder: vnsee [rmall]: build() failed
Traceback (most recent call last):
  File "/tmp/tol1/toltec/./scripts/package_build.py", line 64, in <module>
    if not builder.make(generic_recipe, arch_packages):
  File "/tmp/tol1/toltec/scripts/toltec/builder.py", line 143, in make
    if not self._make_arch(
  File "/tmp/tol1/toltec/scripts/toltec/builder.py", line 168, in _make_arch
    self._build(recipe, src_dir)
  File "/tmp/tol1/toltec/scripts/toltec/builder.py", line 357, in _build
    self._print_logs(logs, "build()")
  File "/tmp/tol1/toltec/scripts/toltec/builder.py", line 689, in _print_logs
    raise err
  File "/tmp/tol1/toltec/scripts/toltec/builder.py", line 670, in _print_logs
    for line in logs:
  File "/tmp/tol1/toltec/scripts/toltec/bash.py", line 416, in run_script_in_container
    raise ScriptError(f"Script exited with code {result['StatusCode']}")
toltec.bash.ScriptError: Script exited with code 1
make: *** [Makefile:60: vnsee] Error 1
```
</details>

(Edit: Fixed grammar issue)

**Comment by matteodelabre** [comment]
Hi @LinusCDE! I looks like you were hit by #321. Did you try building libvncserver (a dependency of VNSee) first?

**Review by LinusCDE — APPROVED** [review]
> Hi @LinusCDE! I looks like you were hit by #321. Did you try building libvncserver (a dependency of VNSee) first?

Yeah. Forgot that. Installing libvncserver first fixed it indeed.

Tested all the points on both devices and it works like charm!

**Comment by matteodelabre** [comment]
Thank you for reviewing and testing :)

**Pull request merged**
