### PR TITLE
Stable merge window for week 1 of 2024

### PR DESCRIPTION
**Pull request by Eeems**
### New Packages
- `sudoku` - 0.1.1-1 (#817)

### Updated Packages
- `webinterface-onboot` - 1.2.3-1 (#813)

### CODE REVIEW

**Comment by rM-self-serve** [comment]
@HookedBehemoth Does the pen lack the ability to click the buttons or may that be an issue on my end?

**Comment by Eeems** [comment]
> @HookedBehemoth Does the pen lack the ability to click the buttons or may that be an issue on my end?

It appears to be an issue for just rM1: https://github.com/HookedBehemoth/remarkable-sudoku/issues/1

**Comment by rM-self-serve** [comment]
I should've taken a look at the issues.

Tested sudoku_0.1.1-1 on rM1, v2.10 and v2.15.1.

-  Functionality works as intended barring https://github.com/HookedBehemoth/remarkable-sudoku/issues/1 
- Correct icon in draft launcher 

My only input would be that the close button seems to conflict with the way gui applications are typically managed, such as starting/stopping from the launcher or command line.

**Comment by Eeems** [comment]
> My only input would be that the close button seems to conflict with the typical way gui applications are managed, such as starting/stopping from the launcher or command line.

There are several applications that have a UI element to exit. KOReader, Plato, and the supporting oxide applications, for example.

**Comment by bkirwi** [comment]
Both packages work as expected for me on RM2.

**Review by bkirwi — APPROVED** [review]
Approving, but we should make sure this is clean on RM1 before merging of course.

**Comment by Eeems** [comment]
I think only webinterface-onboot is outstanding for rM1 testing, I can do that before merging if necessary

**Comment by HookedBehemoth** [comment]
Do the libremarkable demos work for you on rm1?
I really can't debug these issues.

**Comment by Eeems** [comment]
> Do the libremarkable demos work for you on rm1? I really can't debug these issues.

I'd recommend moving this discussion to https://github.com/HookedBehemoth/remarkable-sudoku/issues/1

**Comment by Eeems** [comment]
Okay, final test of webinterface-onboot looks good. Time to release!

**Pull request merged**
