### PR TITLE
Stable merge for week 42 of 2021

### PR DESCRIPTION
**Pull request by Eeems**
Updated packages:

- koreader - 2021.10-1
- remux - 0.1.10-1
- toltec-bootstrap - 0.2.1-1

Tooling:
- Add caching of toltec dependencies to speed up build time.

### CODE REVIEW

**Comment by Eeems** [comment]
Anybody had a chance to test?

**Comment by matteodelabre** [comment]
I’m still a bit busy but I will try my best to test it over the week-end.

**Comment by MechEng70** [comment]
Running the above with no issues.

**Comment by Eeems** [comment]
@MechEng70 using a rM1 or rM2?

**Review by raisjn — APPROVED** [review]

**Pull request merged**
