### PR TITLE
Stable merge for week 26 of 2022

### PR DESCRIPTION
**Pull request by Eeems**
### New packages
- `linux-mainline` - 5.18.0-1 (#488)
  - Mainline linux kernel for the rM2 only

### Updated packages

- `koreader` - 2022.06-1 (#590 #599)
  - Fix reMarkable crash bug v2022.05: event overwrite with new time module
- `display` `rm2fb-client` - 1:0.0.20-1 (#592 #597 #604)
  - Added support for OS 2.13.0.758
  - Added support for OS 2.14.0.861
  - Added support for OS 2.14.1.866
- `ddvk-hacks` - 35.01-1 (#593 #598 #605)
  - Support OS 2.12.3.606 for rM1
  - Support OS 2.13.0.758 for rM2
  - Support OS 2.14.0.861 for both rM1 and rM2
  - Supprot OS 2.14.1.866 for both rM1 and rM2
- `folly` - 0.0.1-3 (#587)
- `remux` - 0.2.3-1 (#588)
  - Make palm filtering a config option
- `harmony` - 0.2.1-1 (#558)
  - More layer dialog improvements
  - Sort import dialog by file date
  - Refactor pressure / tilt events to use hardware values
- `wireguard` - 1.0.20210219-3 (#488)
  - Move to kernel section
- `fuse` - 1.0.0-4 (#488)
  - Move to kernel section

### CODE REVIEW

**Comment by raisjn** [comment]
thanks for opening! can you also include the PRs that matteo accepted last week? 

* https://github.com/toltec-dev/toltec/commit/f17336fa607809d02084f2b7c87e47feb1a60730
* https://github.com/toltec-dev/toltec/commit/de887138ec78c5748c79f8febf5e6402f171ccbf
* https://github.com/toltec-dev/toltec/commit/b671b5af88d42557aebb77e4835130f1cb7cbbb2

**Comment by Eeems** [comment]
@raisjn Since they were only merged 5 days ago, I was holding off on this first stable merge. @matteodelabre any concerns with pulling those forward as well?

**Comment by matteodelabre** [comment]
Thanks for the PR. Yes, I think it would be worthwhile to include the commits that raisjn mentioned.

**Comment by Eeems** [comment]
@matteodelabre @LinusCDE @raisjn poke

**Review by LinusCDE — CHANGES_REQUESTED** [review]
Tested most packages on both models except:
 - The Linux related packlages (`linux-mainline`, `fuse`, `wireguard`) as I don't want to dive into that rn. Maybe later
 - ddvk-hacks (I think I already had this version installed prior and updated to 35.x from PR #605 for this update for testing and because I got this fw as well).

Regressions:
 - ⚠️ harmony@rm2: Hides the toolbar for some brushes (e.g. "Paint brush", which causes hitching when touching the pen. The rM 1 is not affected. More an inconvenience, I don't deem that problematic.
 - ❗ koreader@rm2: Crashed when touched by either pen or finger -> Unusable ([Screenshot of crash report](https://transfer.cosmos-ink.net/gUGhJB/192.168.2.png)). Runs fine on the rM 1. Seems like #599 would fix that. Will test that one next and we should probably include that to fix this issue.

I manually added the entry for the rm2fb to make it run on the 2.14.1.866 FW. We really need some solution that can just update the `/opt/etc/rm2fb.conf` file with newer entries to reduce delays and the need to release and test package a bunch until users can have the improvement.

**Comment by Eeems** [comment]
There is a PR for 2.14.1.866 rm2fb support already open to testing. I agree about just editing the file instead of waiting for a new release. There are issues open on the rm2fb repo with ideas to simplify things, they just need to be implemented.

**Comment by LinusCDE** [comment]
> There is a PR for 2.14.1.866 rm2fb support already open to testing. [...]

Right. Just noticed that. Tested and merged it.

> [...] I agree about just editing the file instead of waiting for a new release. There are issues open on the rm2fb repo with ideas to simplify things, they just need to be implemented.

Yeah. Just wanted to point it out again. At this point it seems toltec on the rM 2 is only useful when being 1-2 fw releases behind because of the delayed releases. Or one knows how to get the update advance with said file. But this is probably the minority. Maybe I'll find time for it next. I think, we should just include the procedure in toltecctl / bootstrap and either parse the config.cpp file or pull an extra released standalone version of it.

**Comment by Eeems** [comment]
@LinusCDE I've pulled in the latest commits for 2.14.1.866 support

**Review by LinusCDE — DISMISSED** [review]
Retested, koreader works now fine and ddvk and rm2fb work out-of-the box.

Nice work, @Eeems !

I didn't really follow the kernel and wireguard things. If someone can confirm those to work, this should be good to go.

**Comment by Eeems** [comment]
@matteodelabre would you be able to test the final pieces?

**Comment by matteodelabre** [comment]
Sure, I can take a look! Sorry for the delay.

**Comment by matteodelabre** [comment]
(Note: I fixed the `display` version number in your original PR comment.)

Tested on rM1 and rM2, 2.14.0 and 2.14.1.

* `linux-mainline` currently instructs users to make a backup of the stock kernel files to the `/opt/boot-backup` directory, but this directory will get removed by `toltecctl uninstall`. We should change this to recommend backing up to a folder under `/home/root` instead. (#606)
* Can confirm the issue mentioned by @LinusCDE with `harmony` on rM2. This makes it a bit difficult to draw (ping @raisjn)
* `fuse` and `wireguard` do not require testing as they are just being moved to a different section.

Everything else is working correctly as far as I can tell.

**Comment by Eeems** [comment]
Fuse and wireguard will require testing with the mainline kernel and the latest OS kernel at some point to make sure they work properly. They've been broken for a while but the latest OS kernel should start working again.

**Comment by Etn40ff** [comment]
> Fuse and wireguard will require testing with the mainline kernel and the latest OS kernel at some point to make sure they work properly. They've been broken for a while but the latest OS kernel should start working again.

Fuse may give issues with linux-mainline since it already has `CONFIG_FUSE_FS=y`. 

Maybe we should re-think the whole idea of making packages with single modules
because it may lead to a lot of confusion whit alternative kernels. Moreover installing things in /lib/modules is definitely going to make `kernelctl` much more complicated than already is.

**Comment by matteodelabre** [comment]
It should be possible to make package variations for each kernel that Toltec provides, and for example mark `fuse` as conflicting with the mainline kernel/depending on the stock kernel.

**Comment by Etn40ff** [comment]
> It should be possible to make package variations for each kernel that Toltec provides, and for example mark `fuse` as conflicting with the mainline kernel/depending on the stock kernel.

Not really a straightforward path: suppose you install linux-mainline but do not enable it, or possibly temporarily decide to switch to the upstream kernel: you will have to install/uninstall the package just to switch. Moreover, how is `kernelctl` going to know which files in `/lib/modules/` belong to the kernel and which to the package? I mean, it is possible but not in a clean way.

**Comment by Eeems** [comment]
I'm not sure the conflict will mater too much since modprobe would still load fuse properly since it's included in the kernel no"?

**Comment by Etn40ff** [comment]
I never tried adding an off-tree kernel module on top of a kernel that already provides it, I do not know how it would react. Possibly just with a warning.

**Review by matteodelabre — APPROVED** [review]
Looks good to me. Thanks again @Eeems for your work on this!

**Pull request merged**
