### PR TITLE
Update retris to 0.6.1-1

### PR DESCRIPTION
**Pull request by LinusCDE**
Should have fully working input support for the rM 2.

@raisjn, could you test this with the shim?

A binary is available on [the release page](https://github.com/LinusCDE/retris/releases/tag/0.6.0-1). I also added the ipk to my test repo.

### CODE REVIEW

**Comment by Eeems** [comment]
@raisjn and @LinusCDE poke

**Comment by LinusCDE** [comment]
Just waiting on my pr to get into libremarkable, so i can reference that instead.

Not sure if the stable window is still open. If so I can probably just reference my fork fork now and update this (and chessmarkable) tomorrow.

**Comment by Eeems** [comment]
Technically I think you've missed the window already. We should work on getting it merged though.

**Comment by LinusCDE** [comment]
Can do so tomorrow then. Also not sure if there is now a nicer way to start apps with immediate rm2 compatibility. And not sure if I have time to persue that tomorrow.

If it won't fit into the merge window I don't think it'll be a problem though. Didn't even plan on getting this into into the current one.

**Comment by Eeems** [comment]
> Can do so tomorrow then. Also not sure if there is now a nicer way to start apps with immediate rm2 compatibility. And not sure if I have time to persue that tomorrow.
> 
> If it won't fit into the merge window I don't think it'll be a problem though. Didn't even plan on getting this into into the current one.

I believe there is a way to have systemd handle most of it for you. As long as your launcher is passing on the environment it should all work nicely.

**Comment by LinusCDE** [comment]
If someone can review this for the rM2, I'll we might be able to squeeze it into the stable window.

Particulary check the following:
 - Input is mapped correctly on the rM2
 - Can launchers start this without this package specifying the shim?

**Review by raisjn — APPROVED** [review]
shipit

**Pull request merged**
