### PR TITLE
Update micro to 2.0.13

### PR DESCRIPTION
**Pull request by Eeems**
[2.0.12 release notes](https://github.com/zyedidia/micro/releases/tag/v2.0.12)
[2.0.13 release notes](https://github.com/zyedidia/micro/releases/tag/v2.0.13)

### CODE REVIEW

**Comment by Eeems** [comment]
I was trying to test this, and for some reason micro is completely broken on my rM1, both the old version, and the latest. This could be related to the profile changes we made to fix yaft? Can anybody else confirm if micro is working or not for them?

**Comment by Jayy001** [comment]
I just tested and it works fine on my rm2 3.3.2.1666 - able to use the new `reload` option and open/work on files.

**Comment by Eeems** [comment]
Can you test on 2.15.1, as we aren't testing support for 3.x yet.

**Comment by rM-self-serve** [comment]
Working on v2.10.2.356 and v2.15.1.1189.

Tested reload and file writes from xterm-256color ssh and yaft.

micro2 0 13

**Review by rM-self-serve — APPROVED** [review]

**Review by Jayy001 — APPROVED** [review]

**Pull request merged**
