### PR TITLE
Update KOReader to v2021.02

### PR DESCRIPTION
**Pull request by Eeems**
Question, do we still need the rm2 support patch?

### CODE REVIEW

**Comment by raisjn** [comment]
some rM2 specific stuff:

* test touch works with swipe gestures (ddvk added touch support)
* test that it can be paused / resumed from oxide or remux
* test wifi stuff (cc @snelg - do you have recommendations of what we should test here?)

the rM2.patch should no longer be necessary

**Comment by snelg** [comment]
> * test wifi stuff (cc @snelg - do you have recommendations of what we should test here?)

Nothing fancy; just make sure turning on wifi ("Settings - Network - Wi-Fi connection") actually connects to a network.

**Comment by matteodelabre** [comment]
Testing on rM2. I’m experiencing very long startup times for KOReader from Oxide (up to 2 minutes). This is not the case when starting KOReader from remux. Not sure whether this is related, but the tarnish logs contain the following repeated messages every ~3 seconds, independently of whether KOReader is started.

```
OPENED SHARED MEM: /dev/shm/swtfb.01 at 75782000, errno: 0
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
OPENED SHARED MEM: /dev/shm/swtfb.01 at 7582a000, errno: 0
OPENED SHARED MEM: /dev/shm/swtfb.01 at 75792000, errno: 0
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
OPENED SHARED MEM: /dev/shm/swtfb.01 at 757ca000, errno: 0
OPENED SHARED MEM: /dev/shm/swtfb.01 at 757d3000, errno: 0
OPENED SHARED MEM: /dev/shm/swtfb.01 at 757ef000, errno: 0
OPENED SHARED MEM: /dev/shm/swtfb.01 at 7578c000, errno: 0
ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
OPENED SHARED MEM: /dev/shm/swtfb.01 at 757e4000, errno: 0
OPENED SHARED MEM: /dev/shm/swtfb.01 at 75810000, errno: 0
```

> * test touch works with swipe gestures (ddvk added touch support)

I tested that swiping down from the upper edge brings the system menu and up from the lower edge brings the reading menu when inside a book. Is there any other gesture to test?

> * test that it can be paused / resumed from oxide or remux

Tested with both Oxide and remux, works well.

> * test wifi stuff (cc @snelg - do you have recommendations of what we should test here?)

Connected successfully to my home Wi-Fi network (WPA2/PSK). There seems to be some kind of conflict with Xochitl’s Wi-Fi management though. Here’s a way to exhibit unexpected behavior in Xochitl:

* Start the device, open KOReader.
* Connect to a Wi-Fi network from KOReader.
* Exit KOReader and start Xochitl.
* Go to Xochitl’s Wi-Fi menu. There are two possible behaviors I noticed:
    1. Xochitl cycles between “Not connected”, “Connected to <Wi-Fi name>”, and “Authentication failed”
    2. Xochitl says “Connected to Wi-Fi”, instead of saying “Connected to <Wi-Fi name>”. In this case, if you try to connect to a network in the list, you’ll go into case (i.)

All of this is fixed with a reboot, so this is not a major bug, just an inconvenience.

**Comment by Eeems** [comment]
> Testing on rM2. I’m experiencing very long startup times for KOReader from Oxide (up to 2 minutes). This is not the case when starting KOReader from remux. Not sure whether this is related, but the tarnish logs contain the following repeated messages every ~3 seconds, independently of whether KOReader is started.
> 
> ```
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 75782000, errno: 0
> ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 7582a000, errno: 0
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 75792000, errno: 0
> ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
> ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 757ca000, errno: 0
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 757d3000, errno: 0
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 757ef000, errno: 0
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 7578c000, errno: 0
> ERROR: ld.so: object '/opt/lib/librm2fb_client.so.1.0.0' from LD_PRELOAD cannot be preloaded (internal error): ignored.
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 757e4000, errno: 0
> OPENED SHARED MEM: /dev/shm/swtfb.01 at 75810000, errno: 0
> ```
> 
> > *

Looks like an issue with rm2fb somehow? @raisjn or @ddvk?

**Comment by raisjn** [comment]
the rm2fb log messages are likely https://github.com/ddvk/remarkable2-framebuffer/issues/37, the long startup time: i don't know. we did add the new wait ioctl in rm2fb, but if it's remux vs. oxide, that wouldn't make sense. should do an investigation (ptrace? strace? gdb? to figure out where the slowdowns are)

**Comment by Eeems** [comment]
@raisjn or @LinusCDE can either of you replicate the slow startup time? @matteodelabre have you had a chance to do some more looking into it?

**Comment by LinusCDE** [comment]
> @raisjn or @LinusCDE can either of you replicate the slow startup time? @matteodelabre have you had a chance to do some more looking into it?

I can't reproduce it. Seems to be a rare edgecase and not rm2 in general. Though investigating this would be useful in case other people encounter this as well.

**Review by raisjn — APPROVED** [review]

**Pull request merged**
