### PR TITLE
ddvk-hacks: Update metadata

### PR DESCRIPTION
**Pull request by matteodelabre**
The version and timestamp for ddvk-hacks were not updated in #462. This PR fixes that.

### CODE REVIEW

**Review by Eeems — APPROVED** [review]
That's really odd, I remember updating them

**Comment by matteodelabre** [comment]
Did you update them in a separate commit that didn’t get pushed by any chance?

**Comment by Eeems** [comment]
> 
> 
> Did you update them in a separate commit that didn’t get pushed by any chance?

I tend to edit in the GitHub web interface, so that isn't likely. Must have been remembering something else.

**Comment by LinusCDE** [comment]
Oh shute. I remember noticing that. But completely forgot after testing it. I should have noticed that.

**Comment by matteodelabre** [comment]
No worries, that’s what the _testing_ branch is for. :-)

**Pull request merged**
