### PR TITLE
[rmkit] patch genie to fix crash in testing

### PR DESCRIPTION
**Pull request by raisjn**
from discussion with matteo, there is a crash in genie on testing (see test plan) when using the example genie config. i tested this patch and verified it fixes the crash. 

test plan:

* use 3 finger tap on rM2 with example genie config (/opt/etc/genie.example.conf). watch genie output and verify that it recognizes the gesture. gesture several times, trying to trigger crash. it's useful to verify that genie in testing crashes for you and that this version does not

### CODE REVIEW

**Comment by danshick** [comment]
I'll update tomorrow and check. Should any repeated gesture for any command cause a crash or only the default config?

**Comment by raisjn** [comment]
any gesture for any command (it's a timing thing), but its easy to use the 3 finger tap rapidly

**Review by matteodelabre — APPROVED** [review]
Tested on rM1 and rM2, works well. Looks good to me!

**Comment by danshick** [comment]
I can't create a crash with this patch.

**Pull request merged**
