### PR TITLE
Update ddvk-hacks to 38.03

### PR DESCRIPTION
**Pull request by NickHu**
Add support for 2.15.0.1067

### CODE REVIEW

**Comment by NickHu** [comment]
@Eeems could you please fire off the CI so that I can test the build?

**Comment by Eeems** [comment]
@NickHu have you had a chance to test?

**Comment by NickHu** [comment]
@Eeems Confirmed working on my reMarkable 2 (I don't have a rm1 to test, but it probably works fine, I took the shasums directly from upstream).

**Comment by Eeems** [comment]
image

**Review by Eeems — APPROVED** [review]
Tested on my rM1 and fixed an issue.

**Pull request merged**
