### PR TITLE
Stable merge window for week 05 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
New packages:

* templatectl 0.1.3-1
* template-cartesian-graph 1.0.0-4
* wireguard 1.0.20201221-1

Updated packages:

* fingerterm 1.3.5-10 → 1.3.5-12
* restream 0.0.0-1 → 1.1-1
* retris 0.6.1-2 → 0.6.3-1
* genie 0.1.1-1 → 0.1.2-3
* harmony 0.1.0-5 → 0.1.1-2
* mines 0.1.0-4 → 0.1.1-2
* nao 0.1.0-4 → 0.1.1-2
* remux 0.1.6-2 → 0.1.7-3
* simple 0.1.1-1 → 0.1.2-2
* vnsee 0.3.0-2 → 0.3.1-1

Documentation:

* Add packaging tutorial and opkg information.
* Improve contributing guide.
* Add instructions for building from source.

Tooling:

* Move packages from utils to new sections.
* Add Toltec home page.
* Rewrite tooling scripts in Python.

### CODE REVIEW

**Comment by matteodelabre** [comment]
Tested on rM1, found no major issues.

In the `wireguard` package, I think showing a message saying that users need to `modprobe wireguard` to enable the module would be a welcome addition.  The `wireguard_watchdog` script, included in `wireguard-tools` (pulled from Entware by `wireguard`), does not work (it says that `/lib/functions.sh` does not exist, and there is no such file in the package).

**Comment by Eeems** [comment]
> In the `wireguard` package, I think showing a message saying that users need to `modprobe wireguard` to enable the module would be a welcome addition.

`depmod -a` in configure already loads the module.

**Comment by matteodelabre** [comment]
Cool! Thanks for clarifying.

**Comment by jonahweissman** [comment]
> The `wireguard_watchdog` script, included in `wireguard-tools` (pulled from Entware by `wireguard`), does not work (it says that `/lib/functions.sh` does not exist, and there is no such file in the package).

I'm happy to write a toltec recipe for wireguard-tools that just contains the stuff that's relevant to reMarkable (and perhaps include wg-quick, a handy shortcut that is not present in entware). I tried [sending entware a pull request](https://github.com/Entware/Entware/pull/592), but they haven't responded yet.

**Comment by matteodelabre** [comment]
That would be great! In the meantime, I think this is not blocking the inclusion of wireguard in the current stable merge, since this script does not impair its main functionalities.

**Comment by matteodelabre** [comment]
Also tested on rM2, no additional issues to report.

**Review by raisjn — APPROVED** [review]
does anything need to happen with the website? i think it should automatically pick up right hash, but let's check after this lands to make sure

**Comment by matteodelabre** [comment]
This PR adds automated deployment of the website to the production server on push to stable. I’ll keep an eye on it and if anything goes wrong I’ll make sure to fix it manually.

**Pull request merged**
