### PR TITLE
Stable merge for week 32 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
Updated packages:

* display, rm2fb-client - 1:0.0.7-1 (#410)
* innernet-client - 1.4.0-1 (#384)
* micro - 2.0.10-1 (#408)
* toltec-completion - 0.3.0-1 (#403)

### CODE REVIEW

**Review by raisjn — DISMISSED** [review]
justdoit

**Comment by Eeems** [comment]
@matteodelabre What are we waiting on for this?

**Comment by matteodelabre** [comment]
It hasn't received testing yet (if I'm not mistaken).

**Comment by Eeems** [comment]
I believe various people have been using specific packages from the list. Since 2.9 and 2.9.1 are becoming quite wide-spread we probably shouldn't hold off too long on merging as we are getting quite a few questions from people about how to fix things due to rm2fb not working out of box in toltec anymore.

**Comment by matteodelabre** [comment]
Should we add rm2fb 0.0.7 (which adds support for version 2.9.1) to this merge?

**Comment by raisjn** [comment]
i've tested display package on rm1 from testing and it works

> Should we add rm2fb 0.0.7 (which adds support for version 2.9.1) to this merge?

yes please

**Comment by matteodelabre** [comment]
Tested on rM1 and rM2, I found no issues. I think this can be merged.

**Review by Eeems — APPROVED** [review]
Shipit

**Pull request merged**
