### PR TITLE
Update KOReader to v2021.12

### PR DESCRIPTION
**Pull request by gbyl**
Remarkable specific changes:

- Fix: Middle button launch for reMarkable 1 [koreader-base#1428](https://github.com/koreader/koreader-base/pull/1428) and [koreader#8487](https://github.com/koreader/koreader/pull/8487)

[Release notes](https://github.com/koreader/koreader/releases/tag/v2021.12)

### CODE REVIEW

**Comment by Eeems** [comment]
Since we don't include button-listen in our package, that wont actually be included in the package we provide.

**Comment by gbyl** [comment]
@Eeems Good point. I noticed that the timestamp was not updated for https://github.com/toltec-dev/toltec/pull/496. How did you generate it?

**Comment by Eeems** [comment]
> @Eeems Good point. I noticed that the timestamp was not updated for https://github.com/toltec-dev/toltec/pull/496. How did you generate it?

Grabbed it from the KOReader GitHub release

**Comment by gbyl** [comment]
That makes sense. I was confused for a second as a different timestamp is listed in https://build.koreader.rocks/download/stable/v2021.12/

**Review by Eeems — APPROVED** [review]

**Pull request merged**
