### PR TITLE
Update innernet to v1.5.0

### PR DESCRIPTION
**Pull request by plan5**
The package builds fine, I'm not able to test right now. For testers: make sure to backup your sqlite database as recommended here:
https://github.com/tonarino/innernet/releases/tag/v1.5.0

This update is supposed to improve NAT traversal.

### CODE REVIEW

**Comment by Eeems** [comment]
Duplicate of #432 ? Although you do have some changes that my PR doesn't have.

**Comment by plan5** [comment]
> Duplicate of #432 ? Although you do have some changes that my PR doesn't have.

Ah, yes it's a duplicate. Mine contains a corrected path for the to-be-patched build file as I see it. I don't mind updating that one or keeping this one.

**Comment by Eeems** [comment]
It might be best to use #432 since this PR seems to have more noise.

**Comment by plan5** [comment]
> It might be best to use #432 since this PR seems to have more noise.
That's right. I'm closing this one.

**Pull request closed without merging**
