### PR TITLE
Stable merge window for week 42 of 2020

### PR DESCRIPTION
**Pull request by matteodelabre**
New packages:

* chessmarkable 0.4.2-1
* whiteboard-hypercard 0.3.0-1

Updated packages:

* harmony 0.0.1-15 → 0.0.1-16
* ~koreader 2020.09.29-2 → 2020.09-53-1~
* ~mines (previously minesweeper) 0.0.1-14 → 0.0.1-15~
* oxide 2.0\~beta-3 → 2.0\~beta-4
* recrossable 0.0.0-1 → 0.0.0-2
* remux 0.0.1-18 → 0.0.1-20

Other changes:

* Now licensed under MIT.
* Added bootstrap script.
* Packages listing split in sections.

### CODE REVIEW

**Comment by matteodelabre** [comment]
Test results:

- [x]     chessmarkable 0.4.2-1
- [x]     whiteboard-hypercard 0.3.0-1
- [x]     harmony 0.0.1-15 → 0.0.1-16
- [x]     ~koreader 2020.09.29-2 → 2020.09-53-1~
    - ~Bug: Opkg considers 2020.09-53-1 as lower than 2020.09.29-2 and refuses to upgrade.~
- [x]     ~mines (previously minesweeper) 0.0.1-14 → 0.0.1-15~
    - ~Bug: `mines` conflicts with `minesweeper` if `minesweeper` was already installed, and Opkg refuses to install `mines`.~
- [x]     oxide 2.0\~beta-3 → 2.0\~beta-4
- [x]     recrossable 0.0.0-1 → 0.0.0-2
- [x]     remux 0.0.1-18 → 0.0.1-20

**Comment by Eeems** [comment]
Do we have a way to mark `mines` as replacing `minesweeper` such that it doesn't error out?

Did you solve the version number issue with KOReader, or do we need to patch in a new version number?

**Comment by matteodelabre** [comment]
> Do we have a way to mark `mines` as replacing `minesweeper` such that it doesn't error out?

This should be possible using some combination of `Replaces` and `Conflicts` (https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces).

> Did you solve the version number issue with KOReader, or do we need to patch in a new version number?

No, I did not.

**Comment by Eeems** [comment]
I think we should hold `mines` back until we implement a proper automatic upgrade path with `Replaces` and `Conflicts`. As for KOReader, we should probably give it a version number that will be detected as newer.

**Comment by raisjn** [comment]
++holding mines back

we are waiting for October koreader monthly release before switching to it
and technically don't need this upgrade, it's there bc the package wasn't
building due to outdated url

**Comment by Eeems** [comment]
> we are waiting for October koreader monthly release before switching to it and technically don't need this upgrade, it's there bc the package wasn't building due to outdated url

Didn't it also change the default to not grab input?

**Comment by raisjn** [comment]
> > we are waiting for October koreader monthly release before switching to it and technically don't need this upgrade, it's there bc the package wasn't building due to outdated url
> 
> Didn't it also change the default to not grab input?

that was in last merge window, i just looked at this pr and it's not changing that line

**Comment by matteodelabre** [comment]
Done.

**Review by Eeems — APPROVED** [review]
lgtm

**Comment by raisjn** [comment]
lgtm

**Pull request merged**
