### PR TITLE
Stable merge window for week 49 of 2023

### PR DESCRIPTION
**Pull request by Eeems**
### New Packages
- `webinterface-onboot` 1.2.2-2 - (#770 #721)
  - Allows the usb web interface to start without the USB cable being connected.
- `webinterface-upload-button` - 1.0.1-1 (#771)
  - Adds an upload button to the usb web interface.
- `signature-rm` - 1.0.2-1 (#772)
  - Removes the `Sent from my reMarkable` signature from emails sent by the device.

### Updated Packages
- `linux-stracciatella` - 5.4.70-3 (#742)
  - Updated to RM1XX_5.4.70_v1.3.4 tag from upstream kernel.
  - Added wireguard module.
- `wireguard` - 1.0.20210219-4 (#743 #784)
  - Removed wireguard-tools and wg-quick from wireguard package. These packages are provided by entware already.
- `display` and `rm2fb-client` - 1:0.0.32-2 (#758 #721)
  - Add support for OS 3.3.2.1666
- `rmfm` - 1.5.1-1 (#766)
  - Fix issue where listing a directory with an invalid symlink would crash the application.
- `neofetch` - 1.1.0-1 (#769)
- `webinterface-wifi` - 2.0.0-2 (#768 #721)
- `micro` - 2.0.13-1 (#738)
- `koreader` - 2023.10-2 (#749 #721)
- `ddvk-hacks` - 39.01-2 (#720 #778)
  - Fix issue where `ddvk-hacks` wouldn't be reapplied when using `toltecctl reenable`.
- `draft` - 0.2.0-22 (#721)
- `erode`, `fret`, `oxide`, `rot`, `tarnish`, `decay`, `corrupt`, `anxiety`, `oxide-utils`, `inject_evdev`, and `liboxide` - 2.6-3 (#721)
- `reboot-guard` - 1.0.1-8 (#721)
- `rmfakecloud-proxy` - 0.0.3-4 (#721)
- `genie` - 0.1.6-3 (#721)
- `remux` - 0.2.4-2 (#721)
- `tailscale-systemd` - 0.0.0-2 (#721)
- `toltec-base` - 1.2-3 (#721)
- `xochitl` - 0.0.0-17 (#721)

### Tooling
- New `provides=()` field added for packages.
- Added `unit-exists` and `disable-unit` methods to install-lib

**Note:** This doesn't change what OS version that toltec supports, as full support still requires various packages to be updated, removed, or replaced. Along with proper testing of all packages in the repository, as well as the upgrade process. https://github.com/toltec-dev/toltec/milestone/7 contains the current list of issues and pull requests required for 3.x support.

### CODE REVIEW

**Comment by Eeems** [comment]
**Todo**
- [x] Populate description with release notes
- [x] Test on rM1
- [ ] Test on rM2

**Comment by Eeems** [comment]
I can install `wireguard` and `wireguard-tools` at the same time, even though `wireguard` provides `wireguard-tools` and `wireguard-tools` conflicts with `wireguard`. It doesn't matter the order I specify them in. Upon inspecting `/opt/lib/opkg/status` it appears that `wireguard-tools` is missing the conflicts line. This will need to be resolved before this can merge to stable.

**Comment by Eeems** [comment]
I've opened https://github.com/toltec-dev/toltec/pull/784 to resolve the issue. It will need to be included before this can merge to stable.

**Comment by bkirwi** [comment]
I did some testing on rm2 this evening: rmfm, display/rm2fb, remux, neofetch all behave well.

I expect to test most of the other rm2 packages sometime before the end of the weekend... except for linux-stracciatella probably, in case someone else with an rm2 wants to pick it up.

**Comment by Eeems** [comment]
> I did some testing on rm2 this evening: rmfm, display/rm2fb, remux, neofetch all behave well.
> 
> I expect to test most of the other rm2 packages sometime before the end of the weekend... except for linux-stracciatella probably, in case someone else with an rm2 wants to pick it up.

Is there a chance that you could review/test #784 in the next day or two so we can get it merged and tested as well? I was hoping to get another merge window started before this weekend, as this merge window was supposed to merge on Sunday.

**Comment by bkirwi** [comment]
Did what I could!

**Comment by Eeems** [comment]
> Did what I could!

Thanks! It's now merged and ready for further testing.

**Comment by trixmoe** [comment]
# Testing
I did some testing with an `rm2` on `2.15.1.1189`.

## Approach
Extreme, but works.

1. Uninstall toltec
2. Reinstall toltec
3. Install all packages mentioned in PR
4. Run some applications (to generate configs, e.g oxide, koreader, etc.)
5. Download PR-specific build artifact from GH PR "Checks" tab
6. Set up repo locally
7. Update and upgrade packages through opkg
8. Test packages

### Using a local-repo with build artifacts
#### Locally (computer)
Firstly, download the PR-specific build artifacts. Then:
```bash
scp repo.zip rm:
```

#### Remotely (rM)
```bash
mkdir -p ~/packages/local/
cd ~/packages/local/
mv ~/repo.zip ./repo.zip
unzip repo.zip
cat > /opt/etc/opkg.conf.d/16-local.conf << EOF
src/gz local-rmall file:///home/root/packages/local/rmall
src/gz local-rm2 file:///home/root/packages/local/rm2
EOF
toltecctl generate-opkg-conf
opkg update
opkg upgrade
```

##### Packages to install (mentioned in PR)
```bash
opkg install webinterface-onboot webinterface-upload-button signature-rm linux-stracciatella wireguard display rm2fb-client rmfm neofetch webinterface-wifi micro koreader ddvk-hacks draft erode fret oxide rot tarnish decay corrupt anxiety oxide-utils liboxide inject_evdev reboot-guard rmfakecloud-proxy genie remux tailscale-systemd toltec-base xochitl
```

## Results
### New Packages
 - [X] `webinterface-onboot`
    * uninstall ddvk-hacks after testing it
    * enable service
    * reboot
 - [X] `webinterface-upload-button`
    * uploaded pdf via web interface
 - [X] `signature-rm`
    * uninstalled ddvk-hacks and webinterface-onboot
 	* missing "restart xochitl or the device" note
    * restarted xochitl
    * sent page by email
 
 ### Updated Packages
 - [X] `linux-stracciatella`
    * switch kernel via kernelctl, rebooted
 - [X] `wireguard`
 	* got a connection working, without using wg-quick
        * following [official instructions](https://www.wireguard.com/quickstart/) and an existing setup
 - [X] `display` and `rm2fb-client`
    * used it for everything
 - [X] `rmfm`
    * open, browse, open text file
 - [X] `neofetch`
 - [X] `webinterface-wifi`
 - [X] `micro`
    * open, edit, save file
 - [X] `koreader`
    * opens a ePUB book and PDF paper
 - [X] `ddvk-hacks`
    * present, works
 - [X] `draft`
    * opened/exited KOReader, opened/exited rmfm
 - [X] `erode`, `fret`, `oxide`, `rot`, `tarnish`, `decay`, `corrupt`, `anxiety`, `oxide-utils`, `liboxide` and `inject_evdev`
    * anxiety, fret: took a screenshot, viewed it
    * corrupt, oxide, tarnish: opened/exited rmfm, opened/exited xochitl
    * erode: open process manager
    * rot: `rot apps get applications`
    * inject_evdev: open a oxide menu, run [example usage](https://oxide.eeems.codes/documentation/02_oxide-utils.html#inject-evdev)
    * oxide-utils: `notify-send test`
 - [X] `reboot-guard`
    * blocks everything correctly after running `rguard -1`, works again after `rguard -0`
 - [X] `rmfakecloud-proxy`
    * ran `rmfakecloudctl`, `rmfakecloudctl status`
 - [X] `genie`
    * used iago and lamp, with [example config](https://rmkit.dev/apps/iago) in `/opt/etc/genie.conf`, `systemctl restart genie`, default bezier curve
 - [X] `remux`
    * switch to rmfm, switch back to xochitl
 - [X] `tailscale-systemd`
    * connect to network
    * reboot rm
    * connect to rm via tailscale
 - [X] `toltec-base`, `xochitl`
    * not sure how to test those, but nothing bad really happened

### Summary
- `signature-rm` is missing "restart xochitl or the device" postinstall note

**Comment by Eeems** [comment]
> ### Summary
> 
>     * `signature-rm` is missing "restart xochitl or the device" postinstall note

The code for uninstall that runs is as follows:
```bash
_restore() {
    echo "Reverting /usr/bin/xochitl"
    if signature-rm has-backup > /dev/null; then
        signature-rm revert --backup -y > /dev/null
    else
        signature-rm revert --reverse -y > /dev/null
    fi
    echo "Success"
    echo
}
```
Did you at least see the `Reverting /usr/bin/xochitl` and `Success` lines? They appear to be masking stdout from `signature-rm revert`, but that's also what the `webinterface-onboot` and `webinterface-upload-button` do.

**Comment by trixmoe** [comment]
> > ### Summary
> > ```
> > * `signature-rm` is missing "restart xochitl or the device" postinstall note
> > ```
> Did you at least see the `Reverting /usr/bin/xochitl` and `Success` lines?

Yes, here's the full output of an installation and removal on my device:
```
root@reMarkable:~# opkg install signature-rm
Package ddvk-hacks version 39.01-2 has no valid architecture, ignoring.
Package ddvk-hacks version 39.01-2 has no valid architecture, ignoring.
Package ddvk-hacks version 39.01-2 has no valid architecture, ignoring.
Package ddvk-hacks version 39.01-2 has no valid architecture, ignoring.
Installing signature-rm (1.0.2-1) to root...
Downloading file:///home/root/packages/local/rmall/signature-rm_1.0.2-1_rmall.ipk
Configuring signature-rm.

Applying signature-rM
Success

root@reMarkable:~# opkg remove signature-rm
Removing package signature-rm from root...
Reverting /usr/bin/xochitl
Success

root@reMarkable:~# 
```

I think the `ddvk-hacks` printing might be related to some quirk of my device, but I'm not sure and it's not exactly blocking installation, just printing more text than necessary.

**Comment by Eeems** [comment]
> I think the `ddvk-hacks` printing might be related to some quirk of my device, but I'm not sure and it's not exactly blocking installation, just printing more text than necessary.

Hmm, that is kind of odd, what does `grep -A 10 ': ddvk-hacks' /opt/lib/opkg/status` return?

**Comment by trixmoe** [comment]
> > I think the `ddvk-hacks` printing might be related to some quirk of my device, but I'm not sure and it's not exactly blocking installation, just printing more text than necessary.
> 
> Hmm, that is kind of odd, what does `grep -A 10 ': ddvk-hacks' /opt/lib/opkg/status` return?

Nothing at all.

**Comment by Eeems** [comment]
What is the output of `cat /opt/etc/opkg.conf`?

EDIT: Oh, I just noticed you added rm1 to your conf file, you should remove that line and regenerate your opkg.conf, as rm1 packages are not meant to be installed on a rM2. That is probably why this is happening.

**Comment by trixmoe** [comment]
> What is the output of `cat /opt/etc/opkg.conf`?

```
root@reMarkable:~# cat /opt/etc/opkg.conf
# Opkg configuration
# Generated by toltecctl (do not modify!)

# Define custom configuration in files under the '/opt/etc/opkg.conf.d' directory
# then run `toltecctl generate-opkg-conf` to regenerate this file

dest root /
dest ram /opt/tmp
lists_dir ext /opt/var/opkg-lists
option tmp_dir /opt/tmp

# /opt/etc/opkg.conf.d/10-entware.conf
arch all 100
arch armv7-3.2 160
src/gz entware https://bin.entware.net/armv7sf-k3.2

# /opt/etc/opkg.conf.d/15-toltec.conf
arch rmall 200
src/gz toltec-rmall https://toltec-dev.org/stable/rmall
arch rm2 250
src/gz toltec-rm2 https://toltec-dev.org/stable/rm2

# /opt/etc/opkg.conf.d/16-local.conf
src/gz local-rmall file:///home/root/packages/local/rmall
src/gz local-rm1 file:///home/root/packages/local/rm1
src/gz local-rm2 file:///home/root/packages/local/rm2
```

Noting that the setup of the last 3 local ones is described in my initial message.

**Comment by Eeems** [comment]
```
src/gz local-rm1 file:///home/root/packages/local/rm1
```
This line would be causing issues, as any packages included here have the `rm1` architecture, which is not defined in the rest of your config, as you are configured for rm2/rmall only. So if you remove this line from `/opt/etc/opkg.conf.d/16-local.conf` and then run `toltecctl generate-opkg-conf` and `opkg update`, the errors should no longer be happening.

**Comment by trixmoe** [comment]
> Oh, I just noticed you added rm1 to your conf file, you should remove that line and regenerate your opkg.conf, as rm1 packages are not meant to be installed on a rM2. That is probably why this is happening.

Indeed, it's now a clean output:
```
root@reMarkable:~# opkg install signature-rm 
Installing signature-rm (1.0.2-1) to root...
Downloading file:///home/root/packages/local/rmall/signature-rm_1.0.2-1_rmall.ipk
Configuring signature-rm.

Applying signature-rM
Success

root@reMarkable:~# opkg remove signature-rm 
Removing package signature-rm from root...
Reverting /usr/bin/xochitl
Success
```

I thought I could just add both without thinking much about it 😅. I also fixed my initial message with the code block for future reference.

**Comment by Eeems** [comment]
Alright, I'm happy with the testing as-is now. @beelux you may want to open an issue about rm-signature/webinterface-onboot/webinterface-upload-button not instructing the user to restart xochitl, that way @rM-self-serve can weigh in on it. In my opinion, it does not block this stable merge.

**Comment by rM-self-serve** [comment]
I would be happy to add the 'restart xochitl' line to the onboot/signature-rm packages. I believe my thinking with onboot was that the name implied rebooting and then I likely copied that to signature-rM. @Eeems would you like me to push that out really quick or are you looking to merge asap? Upload-button does not need to restart xochitl.

**Comment by Eeems** [comment]
> I would be happy to add the 'restart xochitl' line to onboot/signature-rm. I believe my thinking with onboot was that the name implied rebooting and then I likely copied that to signature-rM. @Eeems would you like me to push that out really quick or are you looking to merge asap? Upload-button does not need to restart xochitl.

It's not needed for this stable merge. I'd actually like to have it be done using the new `launcherctl` command in #795 to see if `xochitl` is running and give instructions to the user on how to restart `xochitl` with it.

**Review by Jayy001 — APPROVED** [review]

**Pull request merged**
