### PR TITLE
Move zoneinfo bind mount to zoneinfo-utils package

### PR DESCRIPTION
**Pull request by matteodelabre**
Changes:

* Update tzcode and tzdata from 2020f to 2021a
* Refactor the `templatectl` package to move bind mount config creation and maintenance to more generic `add-bind-mount` and `remove-bind-mount` install functions
* Move the `/usr/share/zoneinfo` bind mount config from the global bootstrap script to the `zoneinfo-utils` package. This keeps the bootstrap more lightweight, eases future updates to the bind mount config, and only enables the bind mount when it’s needed (i.e., when the user actually has timezone information installed in `/opt/share/zoneinfo`)

Test plan (currently only tested on rM2, needs testing on rM1):

* From a Toltec stable install made using the bootstrap script currently in **stable**, install the new `templatectl` and `zoneinfo-utils` packages (versions 0.1.3-2 and 2021a-1).
* Check that the following messages appear in the install log:

```
Mounting '/home/root/.entware/share/remarkable/templates' over '/usr/share/remarkable/templates'
Created symlink /etc/systemd/system/local-fs.target.wants/usr-share-remarkable-templates.mount → /lib/systemd/system/usr-share-remarkable-templates.mount.
Mounting '/home/root/.entware/share/zoneinfo' over '/usr/share/zoneinfo'
Created symlink /etc/systemd/system/local-fs.target.wants/usr-share-zoneinfo.mount → /lib/systemd/system/usr-share-zoneinfo.mount.
```

* Check that the mount points get created (they should appear in `mount`, `systemctl status usr-share-zoneinfo.mount`, and `systemctl status usr-share-remarkable-templates.mount`)
* Remove both packages and check that the following messages appear in the uninstall log:

```
Removing mount over '/usr/share/remarkable/templates'
Removed /etc/systemd/system/local-fs.target.wants/usr-share-remarkable-templates.mount.
Removing mount over '/usr/share/zoneinfo'
Removed /etc/systemd/system/local-fs.target.wants/usr-share-zoneinfo.mount.
```

* Check that the mount points no longer exist (in `mount`, `systemctl status usr-share-zoneinfo.mount`, and `systemctl status usr-share-remarkable-templates.mount`)
* From a Toltec testing install made using the bootstrap script currently in **testing**, upgrade `zoneinfo-utils` to the new version 2021a-1.
* Check that the following message appears in the install log:

```
Bind mount configuration for '/usr/share/zoneinfo' already exists, updating
```

### CODE REVIEW

**Comment by Eeems** [comment]
Changes look good to me. Not sure if I'll have time to test this week though.

**Comment by matteodelabre** [comment]
If anyone has got some free time to review this PR it would be much appreciated. After this is merged, we can move forward with the uninstall script (#295) which is an important feature in my opinion. Thanks!

**Review by Eeems — APPROVED** [review]
Seems to work well for me on my rM1

**Comment by matteodelabre** [comment]
Thanks for your review!

**Pull request merged**
