### PR TITLE
Add issue templates

### LINKED ISSUE #239: Add issue templates
- [x] Package request
- [x] Package issue
- [x] Documentation issue

More?

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Review by LinusCDE — APPROVED** [review]
Looks great!

**Review by danshick — APPROVED** [review]

**Review by raisjn — APPROVED** [review]
🚢 ship it ⚓

**Comment by Eeems** [comment]
Alright, that's the majority of us. I'll wait until later tomorrow to merge, just in case there are concerns from anybody who hasn't approved yet.

**Review by bkirwi — APPROVED** [review]
Works for me!

**Pull request merged**
