### PR TITLE
Update chessmarkable to 0.5.1-1

### PR DESCRIPTION
**Pull request by LinusCDE**
Should have fully working input support for the rM 2. This version also uses a multithreaded bot algo that should be therefore faster.

@raisjn, could you test this with the shim and check whether the bot reponds faster (2nd move on Hard should be a lot faster on the rM2)?

A binary is available on [the release page](https://github.com/LinusCDE/chessmarkable/releases/tag/0.5.0-1). I also added the ipk to my test repo.

### CODE REVIEW

**Comment by Eeems** [comment]
@raisjn any chance to test this soon? @LinusCDE It might be a good idea to get some of the other users who are testing rm2fb to help with testing.

**Comment by LinusCDE** [comment]
If someone can review this for the rM2, I'll we might be able to squeeze it into the stable window.

Particulary check the following:
 - Input is mapped correctly on the rM2
 - Can launchers start this without this package specifying the shim?

**Comment by MechEng70** [comment]
Just tested this on rm2 and can confirm that it works.

**Review by raisjn — APPROVED** [review]
shipit

**Pull request merged**
