### PR TITLE
[rmkit] upgrade remux with further 2.9+ support

### PR DESCRIPTION
**Pull request by raisjn**
1) fix for fast show/hide behavior (https://github.com/rmkit-dev/rmkit/commit/b6b86a464774c699e265c0b3cc71933db5af65bb)
2) error in remux if the input device is not available when the machine starts (https://github.com/rmkit-dev/rmkit/commit/285e7572420167bf02c2c13eaea15ca9777e5197)

### CODE REVIEW

**Comment by raisjn** [comment]
tested on rM2 2.10.3.379

**Comment by LinusCDE** [comment]
Will take a look in the evening.

**Comment by raisjn** [comment]
no rush, I'm also waiting on bkirwi's offline input. when testing, please make sure to reboot and verify remux gestures work after reboot

**Review by LinusCDE — APPROVED** [review]
Works for me on both devices. Works now again after reboot and the launch gesture also works (was never a problem for me at least).

**Pull request merged**
