### PR TITLE
Update ddvk-hacks: conflict with new hacks

### PR DESCRIPTION
**Pull request by rM-self-serve**
Conflict with https://github.com/toltec-dev/toltec/pull/770 and https://github.com/toltec-dev/toltec/pull/772.

### CODE REVIEW

**Comment by Eeems** [comment]
Is the conflicts in the other packages not enough?

**Comment by rM-self-serve** [comment]
Ah, I thought it was best practice to put conflicts on both packages.

**Comment by Eeems** [comment]
> Ah, I thought it was best practice to put conflicts on both packages.

I would say it probably is best practice. I was under the impression we were going to try to resolve the conflict next, so I was just making sure there wasn't an issue this was trying to resolve.

**Comment by rM-self-serve** [comment]
No issues other than the issue of ddvk-hacks failing to install/remove if webinterface-onboot or signature-rm has been installed.

**Comment by Eeems** [comment]
> No issues other than the issue of ddvk-hacks failing to install/remove if webinterface-onboot or signature-rm has been installed.

Just to clarify, by this you mean that without those packages including conflicts it would fail, right? And now that they include it, you can't get them and ddvk-hacks to install at the same time?

**Comment by rM-self-serve** [comment]
Yes, I do mean that without https://github.com/toltec-dev/toltec/pull/770 and https://github.com/toltec-dev/toltec/pull/772 including the conflicts, it would fail. 

The conflicts are working correctly when ddvk-hacks is installed then attempting to install https://github.com/toltec-dev/toltec/pull/770 or https://github.com/toltec-dev/toltec/pull/772.
onboot_conflict

But, when https://github.com/toltec-dev/toltec/pull/770 or https://github.com/toltec-dev/toltec/pull/772 is installed then attempting to install ddvk-hacks, ddvk-hacks will fail in configure() as the previous packages have changed the shasum.

 ddvk-noconflict

**Comment by Eeems** [comment]
Alright, so we do need to make sure that ddvk-hacks has conflicts as well to avoid this. Thanks!

**Review by Eeems — APPROVED** [review]

**Pull request merged**
