### PR TITLE
Apply Oxide hotfix

### PR DESCRIPTION
**Pull request by Eeems**
Hotfix for issues found in #232

### CODE REVIEW

**Comment by raisjn** [comment]
how do i see what patches went into the release zip? did you upload a new tarball manually to v2.1 release on github?

**Comment by Eeems** [comment]
I replaced the zip files from the latest build on the `support/v2.1` branch. You can see the changes here: https://github.com/Eeems/oxide/compare/support/v2.1

**Comment by matteodelabre** [comment]
Tested on my rM1 and this fixes the issues around the `events` field registration. Thanks!

**Comment by Eeems** [comment]
Do we want to wait for a rM2 test or just merge?

**Comment by raisjn** [comment]
i think if its an issue that applies to both, it should be fine to test+accept with rM1 unless there is a reason to think rM2 won't work or has a different code path

**Comment by Eeems** [comment]
> 
> 
> i think if its an issue that applies to both, it should be fine to test+accept with rM1 unless there is a reason to think rM2 won't work or has a different code path

I expect them both to work the same. I'm just waiting on an approval to merge.

**Review by raisjn — APPROVED** [review]

**Pull request merged**
