### PR TITLE
Update KOReader to v2022.03.1

### PR DESCRIPTION
**Pull request by Eeems**
[Release notes](https://github.com/koreader/koreader/releases/tag/v2022.03.1)
Don't use KOReader suspend/screensaver/autosuspend when Oxide is running

### CODE REVIEW

**Comment by matteodelabre** [comment]
@Eeems On rM1, when KOReader is started from Oxide, after putting the device to sleep and resuming it, or after pausing KOReader and then going back to it from Oxide, there seems to be a screen depth issue when the last screen is recalled (fixes itself after interacting with KOReader).

**Comment by Eeems** [comment]
Oh, it might be a bug with Oxide since it's not aware of screen depth and just changes it as part of pause/resume/start/stop events.

**Comment by matteodelabre** [comment]
I see. This should not be blocking for merging this PR then.

**Review by matteodelabre — COMMENTED** [review]
Tested on rM1 and rM2 2.12.3, with a focus on testing that the KOReader sleep screen does not show up when KOReader is started from Oxide, and that it is triggered when KOReader is not started from Oxide.

**Review by matteodelabre — APPROVED** [review]

**Pull request merged**
