### PR TITLE
[rmkit] update remux and harmony

### PR DESCRIPTION
**Pull request by raisjn**
remux: palm filtering config option. defaults to off
harmony: layer dialog improvements, better HW support for pressure/tilt

test plan:

* start remux, verify "ENABLED PALM EVENT FILTERS" is not in the initial output. 
* harmony: play with layers, import/export, etc

### CODE REVIEW

**Comment by jlwbr** [comment]
Tested on rm2, this did fix the issue!

**Comment by matteodelabre** [comment]
Tested remux on rM2 2.14, everything works.

With harmony, I consistently get a `SIGABRT` when trying to Export from the layer management dialog. This happens even when I start from a clean `~/harmony` folder and don’t draw anything before trying to export.

Logs:
```
W: 1404 H: 1872 S: 1404
XRES 1404 YRES 1872 BPP 16 GRAYSCALE 0
TILT_X RANGE: -9000 9000
TILT_Y RANGE: -9000 9000
PRESSURE RANGE: 0 4095
ERROR OPENING INPUT DEVICE /dev/input/event3
ERROR OPENING INPUT DEVICE /dev/input/event4
ADDING TO UNDO STACK, DIRTY AREA IS 1404 1872 0 0
COMPRESSING LAYER Layer 0 0x75947000
COMP TOOK 0.0340649 TOTAL SIZE 0 KBYTES, 1 ELEMENTS
SAVING /home/root/harmony/saved_images/Layer 0-2022-06-23-15:47:27.png
CLEANING UP FB
received SIGABRT, exiting
```

Strace around crash:
```
write(2, "SAVING", 6SAVING)                   = 6
write(2, " ", 1 )                        = 1
write(2, "/home/root/harmony/saved_images/"..., 63/home/root/harmony/saved_images/Layer 0-2022-06-23-15:48:21.png) = 63
write(2, "\n", 1
)                       = 1
mmap2(NULL, 2633728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x73ceb000
munmap(0x73ceb000, 2633728)             = 0
openat(AT_FDCWD, "/home/root/harmony/saved_images/Layer 0-2022-06-23-15:48:21.png", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 10
fstat64(10, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(10, "\211PNG\r\n\32\n\0\0\0\rIHDR\0\0\5|\0\0\7P\10\0\0\0\0J\353\334"..., 24576) = 24576
write(10, "\243i`4\4FC`4\4FC\200F!0:\3540\232\264FC`4\4FC`\0B`"..., 3290) = 3290
close(10)                               = 0
munmap(0x73f6e000, 10514432)            = 0
munmap(0x74975000, 5259264)             = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x2e3221b6} ---
write(2, "CLEANING UP FB", 14CLEANING UP FB)          = 14
write(2, "\n", 1
)                       = 1
ioctl(6, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
ioctl(5, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
ioctl(3, EVIOCGRAB, 0)                  = -1 EINVAL (Invalid argument)
write(2, "received SIGABRT, exiting", 25received SIGABRT, exiting) = 25
write(2, "\n", 1
)                       = 1
close(6)                                = 0
close(5)                                = 0
close(3)                                = 0
futex(0x45a61fc4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
exit_group(11)                          = ?
+++ exited with 11 +++
```

**Comment by matteodelabre** [comment]
(This also occurs on the previous `harmony` release 0.2.0)

**Comment by matteodelabre** [comment]
This seems to occur only on rM2. Following the same test procedure, I experience no crash no rM1. Logs:

```
write(2, "SAVING", 6SAVING)                   = 6
write(2, " ", 1 )                        = 1
write(2, "/home/root/harmony/saved_images/"..., 63/home/root/harmony/saved_images/Layer 0-2022-06-23-22:09:39.png) = 63
write(2, "\n", 1
)                       = 1
mmap2(NULL, 2637824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x743de000
munmap(0x743de000, 2637824)             = 0
openat(AT_FDCWD, "/home/root/harmony/saved_images/Layer 0-2022-06-23-22:09:39.png", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 10
fstat64(10, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(10, "\211PNG\r\n\32\n\0\0\0\rIHDR\0\0\5\200\0\0\7P\10\0\0\0\0@\233\260"..., 24576) = 24576
write(10, "\217\246\201\321\20\30\r\201\321\20\30\r\1:\204\300\350\20\304h2\33\r\201\321\20\30\r\201\1\n\201"..., 3290) = 3290
close(10)                               = 0
munmap(0x74662000, 10547200)            = 0
munmap(0x75071000, 5275648)             = 0
ioctl(3, FBIOGET_VSCREENINFO, 0x7ee247d0) = 0
ioctl(3, FBIOGET_VSCREENINFO, 0x7ee24868) = 0
ioctl(3, FBIOGET_VSCREENINFO, 0x7ee248a0) = 0
ioctl(3, FBIOGET_VSCREENINFO, 0x7ee248d8) = 0
mmap2(NULL, 483328, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7580f000
munmap(0x7580f000, 483328)              = 0
brk(0x294a000)                          = 0x294a000
ioctl(3, _IOC(_IOC_WRITE, 0x46, 0x2e, 0x48), 0x7ee24b08) = 0
```

**Review by matteodelabre — APPROVED** [review]

**Pull request merged**
