### PR TITLE
Update packages for release 2.6 and onwards

### LINKED ISSUE #322: Support for system update 2.6
A new official system update, 2.6, is being rolled out to users. [Most system libraries have been updated](https://github.com/toltec-dev/toolchain#version-matrix) in this new version, which makes apps compiled for previous versions incompatible. In particular:

* Qt was updated from 5.11.3 to 5.15.1 and the libqsgepaper.a library does not work as-is. This is because the library interfaces with private Qt classes whose API have changed between the two versions (see Eeems/oxide#187, sandsmark/recrossable#15, khanhas/zshelf#3, dixonary/fingerterm-reMarkable#8, dps/remarkable-keywriter#18).
* libcrypto.so was updated from 1.0.2 to 1.1, which causes the apps that use this library to not work unless the old lib is copied (see pl-semiotics/rM-vnc-server#8).
* Method signatures in xochitl and remarkable-shutdown, used by rm2fb have changed (see ddvk/remarkable2-framebuffer#18, ddvk/remarkable2-framebuffer#55, rmkit-dev/rmkit#117).

[A new release of the Toltec toolchain](https://github.com/toltec-dev/toolchain/releases/tag/v2.0) was made to support building apps that target the new 2.6 update. However, most packages compiled for 2.6 will not work for 2.5, and vice-versa. Our current plan is to take advantage of the new features in #310 to create two separate repos containing packages for each of the two versions.

### PR DESCRIPTION
**Pull request by matteodelabre**
With release 2.6 having reached most users, I think it makes sense to rebuild our packages to use the 2.x toolchain. This will make Toltec work with updates 2.6 and onwards (fixes #322), at the price of **breaking compatibility with system updates 2.5 and earlier.**

Testing plan: Having update 2.7.1 installed, I went through basic checks for each package on rM2 to make sure that each app at least starts up and seems to react to user input.

### CODE REVIEW

**Comment by matteodelabre** [comment]
The only issue I found for now is that @Eeems’s Oxide has some missing icons (top-left menu button and top-right power button). Other than that, the launcher works well.

Another issue that is minor in the context of this PR is that @fenollp’s whiteboard-hypercard does not build with the new image, because it features an updated Rust nightly toolchain that is no longer compatible with one of its crates. Since it does not use Qt libs, it should work without needing an update to the newer toolchain for now.

**Comment by Eeems** [comment]
> The only issue I found for now is that @Eeems’s Oxide has some missing icons (top-left menu button and top-right power button). Other than that, the launcher works well.

I'm including a font to drive those. Are the files not being pulled in?

**Comment by matteodelabre** [comment]
The missing icons bug is already tracked in issue https://github.com/Eeems/oxide/issues/194 and PR https://github.com/Eeems/oxide/pull/195.

**Comment by matteodelabre** [comment]
Added a patch for Oxide (taken from Eeems/oxide#195) that fixes the missing icons bug.

**Comment by ralsei** [comment]
I can confirm the following applications work on 2.8 on rM1:
- All parts of Oxide (except `decay`, not because it doesn't work, but because I don't use it)
- ZShelf
- Wikipedia
- Yaft
- nao
- Plato
so at first glance it doesn't look like 2.8 bumped the Qt version in a way that matters.

**Comment by Eeems** [comment]
There have been several users who have used this branch on 2.6+, what is currently blocking this from merging?

**Comment by matteodelabre** [comment]
To me this PR is clear for merging. @raisjn and you did mention the need for adding a check that the user is actually running version ⩾ 2.6 before upgrading. This can also be done in a separate PR, since this is going to testing and not directly to stable.

**Review by Eeems — APPROVED** [review]

**Pull request merged**
