### PR TITLE
upgrade whiteboard-hypercard to v0.3.4

### PR DESCRIPTION
**Pull request by fenollp**
Hi! Author of this package here, upgrading it.

A "changelog": https://github.com/fenollp/reMarkable-tools/compare/v0.3.0...v0.3.4
Really it's a collection of functional & UI fixes and the addition of rM2 support.

Note: I'm still testing building toltec packages...

### CODE REVIEW

**Comment by Eeems** [comment]
`error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly`

**Comment by fenollp** [comment]
@Eeems Then x86_64-unknown-linux-gnu is the default toolchain in image rust:v2. Maybe we should be changing that?
Anyway I'll push a fix here

**Comment by Eeems** [comment]
> 
> 
> @Eeems Then x86_64-unknown-linux-gnu is the default toolchain in image rust:v2. Maybe we should be changing that? Anyway I'll push a fix here

Have you tried with the latest version of the toolchain image? v2.2 https://github.com/toltec-dev/toolchain/pkgs/container/rust

**Comment by fenollp** [comment]
Any way I can download the uploaded ipkg artefacts? That'd be an easy way to test on my devices.

**Comment by Eeems** [comment]
Click the details link, and then select summary on the top left. The repo artifact should be at the bottom after that.

**Comment by fenollp** [comment]
Looks fine (draws, connects and prints QR code).
Top right buttons aren't buttons yet so that's fine.
Top right digits are messed up, likewise, this is future stuff.

**Comment by Eeems** [comment]
Just tested, QR code displays, and I can draw. But I can't trigger any of the buttons on the top left. Are they suppose to work?

**Comment by fenollp** [comment]
> I can't trigger any of the buttons on the top left. Are they suppose to work?

Nope they aren't implemented yet. That's expected.

**Comment by Eeems** [comment]
> 
> 
> > I can't trigger any of the buttons on the top left. Are they suppose to work?
> 
> Nope they aren't implemented yet. That's expected.

Your earlier comment only mentioned top right so I wasn't sure.

**Review by Eeems — APPROVED** [review]

**Pull request merged**
