### PR TITLE
Stable merge for week 41 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
Updated packages:

* ddvk-hacks - 26.02-1
* display, rm2fb-client - 1:0.0.8-2
* remarkable-stylus - 0.0.3-2
* xochitl - 0.0.0-9

Documentation:

* README improved by <a href="https://github.com/gbyl">@gbyl</a> (thanks!)

### CODE REVIEW

**Comment by Eeems** [comment]
I can't test display, rm2fb-client, or remarkable-stylus so it might make more sense for someone else to test this merge.

**Comment by MechEng70** [comment]
Have display and rm2fb-client installed, no launchers.  Other than booting up correctly and normal responsiveness, is there anything you want tested?

Have ddvk installed (26.2.02). They are working.

**Comment by Eeems** [comment]
I think that's good enough. @matteodelabre ?

**Comment by colehpage** [comment]
hey guys - any updates on this one? are we good to go here or is there more review needed?

**Comment by Eeems** [comment]
> 
> 
> hey guys - any updates on this one? are we good to go here or is there more review needed?

Still waiting on a response from @matteodelabre

**Comment by matteodelabre** [comment]
Seems good for merging. @Eeems Could you take care of this merge?

**Review by Eeems — APPROVED** [review]

**Comment by Eeems** [comment]
Done!

**Comment by matteodelabre** [comment]
Thanks!

**Comment by colehpage** [comment]
Thanks guys!

**Pull request merged**
