### PR TITLE
Update KOReader to v2023.04

### PR DESCRIPTION
**Pull request by Eeems**
There are no reMarkable specific changes.

See the [release notes](https://github.com/koreader/koreader/releases/tag/v2023.04) for more information.

### CODE REVIEW

**Review by LinusCDE — COMMENTED** [review]
Runs fine on the rM 2, but on the rM 1 I received the following crash:

grafik

I made sure to update toltec on both devices before but didn't update the firmware. The rM is currently on firmware 2.15.1.1189 which is probably pretty old. If that is the case and it runs on modern firmwares well, feel free to merge anyway @Eeems .

**Comment by Eeems** [comment]
Based on https://github.com/koreader/koreader/issues/9771 it looks like your filesystem has some corruption that needs to be cleaned up. Try deleting the cached data files and see if it will work

**Comment by LinusCDE** [comment]
Deleting `/opt/koreader/cache/fontlist/fontinfo.dat` did indeed solve the issue. Seems indeed like some corruption that causes zstd to try to allocate an insane amount of memory (far more than installed ram).

**Comment by LinusCDE** [comment]
Fyi just tested whether it's random corruption or not.

For that I downgraded Koreader to a release from roughly September 2022 and copied back the file (`/opt/koreader/cache/fontlist/fontinfo.dat`, which I only moved it to `/tmp` instead of deleting it) and started that.

```bash
opkg install koreader_2022.08-1_rmall.ipk --force-downgrade
```
https://transfer.cosmos-ink.net/KQCerPfqRa/koreader_2022.08-1_rmall.ipk

That version started fine. When then upgrading the the newest release, it started crashing again. The file has been last changed on Aug 31 2022 according to ls
```
reMarkable: ~pkgs/pkgs1/ ls -lah /tmp/fontinfo.dat
-rw-rw-rw-    1 root     root       34.4K Aug 31  2022 /tmp/fontinfo.dat
reMarkable: ~pkgs/pkgs1/
```

So this is likely not some corruption or unexpected crash which aborted writing the file, but the inability of never koreader versions to properly read the (older version?) of this file.

Below the fontinfo.dat that crashes, as well as a different one where there was no issue for comparison.

- File in question that causes crashes on a recent version: https://transfer.cosmos-ink.net/ofHeNebpbN/fontinfo.dat
- Similar file of other device model, which worked fine: https://transfer.cosmos-ink.net/BNTt5jaVgk/fontinfo.dat (the file appears to have been replaced / upgraded automatically when running the newer version)

**Review by LinusCDE — APPROVED** [review]
With the new workaround, upgrading from 2022-08 to this release (with the old problematic file from before) works fine.

Thanks for investigating and fixing it @Eeems! :+1:

**Pull request merged**
