### PR TITLE
Create fbink packages

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Review by LinusCDE — APPROVED** [review]
Runs fine.

**Comment by Eeems** [comment]
@NiLuJe Just poking you so you are aware that this will be making its way into toltec stable in the next couple weeks.

**Comment by NiLuJe** [comment]
Cool, thanks ;).

Given the rM TC, I don't think this'll be an issue, so, just FYI, it requires a compiler w/ C11 support, and ideally not utterly-broken LTO handling ;).

(I generally use GCC 7.x, because arm32 performance took a nosedive in later releases. Or a recent Clang).

----

Fair warning that I've never tested the doom thing outside of a Kindle or a Kobo (or a plain linux fb) ;).

**Comment by Eeems** [comment]
> Cool, thanks ;).
> 
> Given the rM TC, I don't think this'll be an issue, so, just FYI, it requires a compiler w/ C11 support, and ideally not utterly-broken LTO handling ;).
> 
> (I generally use GCC 7.x, because arm32 performance took a nosedive in later releases. Or a recent Clang).

Hmm, I'm just using whatever is in the latest base toolchain. I might have to look into the image to see if it needs clang or something. 
> 
> ----
> 
> Fair warning that I've never tested the doom thing outside of a Kindle or a Kobo (or a plain linux fb) ;).

@NiLuJe it worked fine on the reMarkable 1.

**Comment by LinusCDE** [comment]
> Cool, thanks ;).
> 
> Given the rM TC, I don't think this'll be an issue, so, just FYI, it requires a compiler w/ C11 support, and ideally not utterly-broken LTO handling ;).
> 
> (I generally use GCC 7.x, because arm32 performance took a nosedive in later releases. Or a recent Clang).


```
arm-linux-gnueabihf-gcc (crosstool-NG 1.24.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ls: cannot access '/bin/*clang*': No such file or directory
ls: cannot access '/usr/bin/*clang*': No such file or directory
```

> Fair warning that I've never tested the doom thing outside of a Kindle or a Kobo (or a plain linux fb) ;).

Here is it in action on the rM 1:

https://user-images.githubusercontent.com/22298664/103420789-6ca89880-4b99-11eb-9757-e65dbecebcdf.mp4

**Comment by Eeems** [comment]
> > Cool, thanks ;).
> > Given the rM TC, I don't think this'll be an issue, so, just FYI, it requires a compiler w/ C11 support, and ideally not utterly-broken LTO handling ;).
> > (I generally use GCC 7.x, because arm32 performance took a nosedive in later releases. Or a recent Clang).
> 
> ```
> arm-linux-gnueabihf-gcc (crosstool-NG 1.24.0) 8.3.0
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> ls: cannot access '/bin/*clang*': No such file or directory
> ls: cannot access '/usr/bin/*clang*': No such file or directory

Sounds like we'll have to add a new image to the toolchain that contains clang. I'll probably spend some time today figuring that out.

**Comment by LinusCDE** [comment]
> Sounds like we'll have to add a new image to the toolchain that contains clang. I'll probably spend some time today figuring that out.

Sounds cool, but is not necessary. I just ran the command to check in case. Not sure if there is any need atm.

**Comment by NiLuJe** [comment]
FWIW, Gentoo here, so it's as simple as adding `ARM` to `LLVM_TARGETS`  ;p.

Then I build an [arm compiler-rt](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/x-clang-compiler-rt.sh) just for the cherry on top.

(Can't bootstrap a full Linux Clang TC, as Clang cannot build the glibc).

**Pull request merged**
