### PR TITLE
Update ddvk-hacks to 29.01-1

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
I plan on updating to 2.11 soon, so I'll be able to test on a rM1, but someone else will need to test on a rM2.

**Comment by Eeems** [comment]
Works for me on my rM1. @matteodelabre, @raisjn, or @LinusCDE can you check the rM2?

**Comment by matteodelabre** [comment]
There seems to be a missing file, here’s what I get on rM2 2.11.0.442:
```
Installing ddvk-hacks (29.01-1) to root...
Configuring ddvk-hacks.

Device: reMarkable 2
Xochitl version: 2.11.0.442
Patch version: 29.2.02

Patching Xochitl
bspatch: fopen(/opt/share/ddvk-hacks/patch_29.2.02): No such file or directory
```

**Comment by Eeems** [comment]
We really need a way to automate creation and testing of this package :(

**Comment by matteodelabre** [comment]
> We really need a way to automate creation and testing of this package :(

Yes! The `package()` part can probably be automated to go look for the highest patch version number in each directory. Extracting the metadata used in `configure()` (version number, version timestamp, Xochitl original hash) will probably not be as easy though.

**Review by matteodelabre — APPROVED** [review]
Working on rM2 2.11.0.442

**Comment by Eeems** [comment]
> Extracting the metadata used in `configure()` (version number, version timestamp, Xochitl original hash) will probably not be as easy though.

Since you just need to parse it out of patch.sh, it's probably not that difficult.

**Comment by matteodelabre** [comment]
> Since you just need to parse it out of patch.sh, it's probably not that difficult.

Mmh. Parsing shell scripts can be a challenge sometimes. But assuming the patch.sh format stays fixed it should be doable indeed.

**Pull request merged**
