### PR TITLE
Add zerotier-one

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Etn40ff** [comment]
I think that zerotier is already available in entrare but it misses the systemd integration.

**Comment by Eeems** [comment]
> I think that zerotier is already available in entrare but it misses the systemd integration.

It looks like you are correct. I'll have to check to see what all they include, but it is a couple of minor versions behind. They probably don't have the manpages or selftest packages either.

**Comment by Eeems** [comment]
https://github.com/Entware/entware-packages/tree/master/net/zerotier

It looks like they have the same config and a couple of other small patches that I should take a closer look at. They also have picked an odd name for the package. Most distributions call it zerotier-one since that's what the software is called.

I'll have to adjust my package to take into account that the entware one exists, and add some of the patches they use.

**Comment by Eeems** [comment]
Tested on my rM1 and it's working. The selftest succeeds as well:
image

**Comment by Eeems** [comment]
The selftest also passes on my rM2, as well as running it. A lack of tun in the kernel I'm on is keeping it from fully working, but I'll resolve that when I can test a custom kernel.

**Comment by Eeems** [comment]
Tested with `linux-stracciatella` and this works as expected.

**Review by raisjn — APPROVED** [review]

**Pull request merged**
