### PR TITLE
Add reboot-guard

### PR DESCRIPTION
**Pull request by Eeems**
I'm likely going to add this as a dependency for Oxide.

### CODE REVIEW

**Review by raisjn — DISMISSED** [review]
:cool:

how big is python? 30MBish download?

**Comment by Eeems** [comment]
> cool
> 
> how big is python? 30MBish download?

Not quite sure, the python3 package is only 967 bytes compressed. Didn't check what else it pulls down.

**Comment by Eeems** [comment]
Tested and it now works.

**Review by raisjn — APPROVED** [review]
shipit

**Pull request merged**
