### PR TITLE
package/wikipedia

### PR DESCRIPTION
**Pull request by dps**
v0.1.0-1 of remarkable-wikipedia for toltec

### CODE REVIEW

**Comment by Eeems** [comment]
I would recommend adding an icon. Everything seems to work great though (aside from the issues/enhancements I've already opened on your repo)!

**Review by Eeems — APPROVED** [review]

**Comment by raisjn** [comment]
I suggest someone test on rM2 since https://github.com/ddvk/remarkable2-framebuffer/issues/17 has been a long-standing issue. my understanding is dps fixed that in https://github.com/dps/remarkable-wikipedia/commit/ad039ff801bd2d20919ec6131f934cc2464432e8 a few days ago, but it should still be verified by someone with an rM2.

**Comment by danshick** [comment]
I can probably give it a shot tonight.

Edit: Even if links turn out to be broken, that's no reason to keep the package out of testing.

**Comment by Eeems** [comment]
@dps did mention he was testing on a rM2, but having a second test would be fine. I was waiting to merge based on if @dps wanted to add an icon or not.

**Comment by Eeems** [comment]
> Edit: Even if links turn out to be broken, that's no reason to keep the package out of testing.

https://github.com/dps/remarkable-wikipedia/issues/12 Known issue

**Comment by danshick** [comment]
Closing in favor of #311

**Pull request closed without merging**
