### PR TITLE
Update README to include warning from the website

### PR DESCRIPTION
**Pull request by jmrtsh**
Well I just soft-bricked my remarkable 2 because I followed the instructions here, which could have been avoided if the README contained the same warning as the Website.

I am pretty sure your "pull requests to stable cannot be accepted" rule does not apply to README updates, but if thats not the case then I'll create another one for testing.

### CODE REVIEW

**Comment by LinusCDE** [comment]
Whether changes of the readme to stable are accepted I'm unsure.

I've installed toltec on my rM 2 with 2.10 support. As long as rm2fb is not installed, it shouldn't softbrick the device. The problem is, that for every release, rm2fb needs updated signatures to work properly or xochitl won't start. The issue is updating rm2fb (or just the signatures) fast enough and there are ongoing discussions about this in issue #445 and pr #461 on updating the signatures of rm2fb faster without waiting on a new release of the software. I think there were more discussions, but I'm unsure where or if just in discord).

In general I approve of adding this disclaimer for now. But I think we should have a more generalized disclaimer, that
 - warns for this very issue
 - shows where to check the currently supported xochitl version with rm2fb (though completion of the issue #445 might address this automatically)
 - urges people to write down their ssh password beforehand

Side note: rm2fb "only" bricks the selected launcher/xochitl from starting up if on an unsupported version and ssh should still work (at least over usb). PR #455 should resolve this issue in the future.

As said, I'm unsure whether changes to stable are accepted for the readme but find it logical as well. @Eeems or @matteodelabre, if this is okay, I would suggest merging this.

**Comment by jmrtsh** [comment]
> Side note: rm2fb "only" bricks the selected launcher/xochitl from starting up if on an unsupported version and ssh should still work (at least over usb). PR #455 should resolve this issue in the future.

Yes, I fortunately managed to get back into it via ssh and uninstall toltec again, after the reboot it worked again :D

**Comment by Eeems** [comment]
@LinusCDE the following will make it so we don't really need to have a warning anymore after upgrades:
- https://github.com/ddvk/remarkable2-framebuffer/issues/69
- https://github.com/ddvk/remarkable2-framebuffer/issues/76
- https://github.com/toltec-dev/toltec/pull/455

It's probably fine to add to the stable readme for now, but it'll have to be removed after the next stable merge.

@matteodelabre thoughts?

**Comment by jmrtsh** [comment]
It might also be advantageous to only have one place where the installation process is detailled to avoid such inconsistencies in the future. Maybe the website can just link to the installation part of the README?

**Comment by Eeems** [comment]
> 
> 
> It might also be advantageous to only have one place where the installation process is detailled to avoid such inconsistencies in the future. Maybe the website can just link to the installation part of the README?

I think it would make more sense to have the readme link to the website. That said, this isn't going to be an issue for much longer due to issues/prs that both @LinusCDE and I linked.

**Comment by jmrtsh** [comment]
Well which way around the installation instructions are, is for you to decide, I also thought it could prevent similar issues in general.

**Comment by matteodelabre** [comment]
I also had in mind of redirecting users to the website for install instructions. As a nice side effect it would also free us from having to maintain the bootstrap checksum manually in the readme. As a temporary solution I think it’s fine to merge this PR.

**Review by Eeems — APPROVED** [review]

**Comment by Eeems** [comment]
I'll update the next stable merge to include removing the warning.

**Comment by Eeems** [comment]
I just realized that we just pushed 2.10 support.. maybe we should remove the warning now and remove it from the website? @matteodelabre

**Pull request merged**
