### PR TITLE
[display] add remux.service.conf override to display package on rm2

### PR DESCRIPTION
**Pull request by raisjn**
this turns on the display shim for remux on rm2 apps. the reasoning for this is so that people can launch homebrew apps that they compiled from other sources without having to use patchelf. 

TEST PLAN:

* install display package on rm2, verify that /etc/systemd/system/remux.service.d/remux.service.conf exists and has an Environment= line in it
* restart remux, verify that applications can be launched
* custom compile an application without patchself (or remove the DT needed using patchelf) and verify remux can launch it

### CODE REVIEW

**Comment by raisjn** [comment]
over time, if everyone starts using patchelf, this may be less and less needed. before then, i will work on being able to disable the preload on an app by app basis so people can disable it if they like. 

this PR is related to https://github.com/toltec-dev/toltec/issues/337

**Comment by matteodelabre** [comment]
Thanks for raising this point @raisjn. I agree with you. The current state of things is that all apps that work on rM2 assume that they’ll be used with LD_PRELOAD, so making a hard transition to requiring each of those apps to be patchelf-ed will confuse users. For consistency, this should be applied to all the launchers, not only remux (any thoughts on this @Eeems @dixonary?).

In the long run (if everyone agrees that this is a good thing to do), I think we should update rm2fb’s docs to recommend that users use patchelf when they self-compile their apps and do not rely on LD_PRELOAD being there. We could also open issues with rM2-compatible projects to ask if they can update their build instructions and pre-built binaries too.

**Comment by Eeems** [comment]
I'm okay with applying this to Oxide as well for now. I do think that patchelf is the right longer term solution though.

**Comment by matteodelabre** [comment]
I moved those overrides to the `rm2fb-client` package as they depend on the librm2fb_client library, which is provided by that package instead of `display`. I also renamed the files to a name that more explicitly states their intent.

**Review by matteodelabre — APPROVED** [review]
I tested it on my rM2 by removing the librm2fb_client dependency on the calculator binary and starting the app from each of the three launchers. This is ready for merging if you agree with my minor changes above @raisjn

**Pull request merged**
