### PR TITLE
Bump sources to latest available (05/10/2022)

### PR DESCRIPTION
**Pull request by Etn40ff**
Incorporate the latest changes from upstream

### CODE REVIEW

**Comment by Etn40ff** [comment]
usb networking does not work with this kernel: apparently two usb interfaces are created and the udhcpd runs on the wrong one.
Previously only one usb interface existed.
 
I might have to update my software version for this to work properly (I am on 20221026104022). 
Someone testing on RM1 and/or other software versions could be helpful.

**Comment by Etn40ff** [comment]
I traced the usb issue down to https://github.com/reMarkable/linux/commit/6a394b204c06a8df11493f9160948cafd561966b: CDC ECM and CDC EEM behave differently. 

The latest version supported on toltec is 20221026104022 (i.e. 2.15.1.1189) and the kernel shipping with this version does not have this commit merged in: it is built from https://github.com/reMarkable/linux/tree/RM1XX_5.4.70_v1.2.5. 

I guss this PR will have to wait.

**Review by raisjn — CHANGES_REQUESTED** [review]
waiting for update for USB fixes

**Comment by Eeems** [comment]
@Etn40ff the reMarkable linux repo has been updated recently. Does it have what you need?

**Comment by Etn40ff** [comment]
I am not sure, it looks like all the changes are related to the new pogo module that handles the keyboard folio. 

I will have to test this.

**Comment by Eeems** [comment]
@Etn40ff have you had a chance to look closer?

**Comment by Eeems** [comment]
@Etn40ff poke again

**Comment by Eeems** [comment]
@Etn40ff poke

**Comment by Etn40ff** [comment]
This is now #742

**Comment by Eeems** [comment]
@Etn40ff so should this be closed?

**Comment by Etn40ff** [comment]
I guess so

**Pull request closed without merging**
