### PR TITLE
Update to Oxide v2.2

### PR DESCRIPTION
**Pull request by Eeems**
- Update Oxide to v2.2
- Update Xochitl registration to run it in a chroot under Oxide.

### CODE REVIEW

**Comment by raisjn** [comment]
looks like an awesome release! is there anything specific you want help with testing? (nice work with chroot!)

**Comment by Eeems** [comment]
> looks like an awesome release! is there anything specific you want help with testing? (nice work with chroot!)

I wouldn't mind more testing of the chroot to make sure there are no large bugs that were missed before making it the default.

**Comment by matteodelabre** [comment]
I found references to `/opt/etc/draft/icons/{erode,oxide,anxiety}-splash.png` in application registration files, but those files don’t exist in the packages. Also, anxiety’s icon is stored in `/opt/etc/draft/icons/image.svg`: why not call it `anxiety.png`?

While testing gestures, I noticed that Oxide’s gesture to disable gestures by swiping down from the upper border conflicts with Xochitl’s gesture for closing documents.

Regarding the chroot, is Xochitl supposed to run in a chroot in the current configuration? Or do I need to change something to test it? From my tests, it doesn’t seem to run in a chroot by default.

Other than that, everything looks good, thanks for your work on this release!

**Comment by Eeems** [comment]
> I found references to `/opt/etc/draft/icons/{erode,oxide,anxiety}-splash.png` in application registration files, but those files don’t exist in the packages.

Odd, those should be pulled across. Qt Creator is handling them when installing with that. I'll have to poke around a bit to see why it's missed.

> Also, anxiety’s icon is stored in `/opt/etc/draft/icons/image.svg`: why not call it `anxiety.png`?

Because it's just a generic image icon.

> While testing gestures, I noticed that Oxide’s gesture to disable gestures by swiping down from the upper border conflicts with Xochitl’s gesture for closing documents.

If you want to trigger Xochitl's closing document gesture, you can swipe from lower than the edge of the screen.

> Regarding the chroot, is Xochitl supposed to run in a chroot in the current configuration? Or do I need to change something to test it? From my tests, it doesn’t seem to run in a chroot by default.

If you install the new xochitl package included in these changes it will run in a chroot.

**Comment by Eeems** [comment]
Upon reviewing the project files, they do include references to the *-splash.png files. Not entirely sure why they are being missed.
https://github.com/Eeems/oxide/blob/master/applications/screenshot-viewer/anxiety.pro#L33

**Comment by Eeems** [comment]
Ah, I forgot to add them to the `package` file.

**Comment by matteodelabre** [comment]
The missing resources issue is fixed, thanks!

> If you install the new xochitl package included in these changes it will run in a chroot.

Sorry, I forgot to upgrade the xochitl package indeed. Starting chrooted Xochitl from Oxide on rM2, I don’t get any on-screen output. The logs show that Xochitl is running, though. I think the Xochitl wrapper script is failing, I see the following error in the logs:

```
grep: /opt/etc/xochitl.env.d/*: No such file or directory
```

**Comment by Eeems** [comment]
> 
> 
> The missing resources issue is fixed, thanks!
> 
> > If you install the new xochitl package included in these changes it will run in a chroot.
> 
> Sorry, I forgot to upgrade the xochitl package indeed. Starting chrooted Xochitl from Oxide on rM2, I don’t get any on-screen output. The logs show that Xochitl is running, though. I think the Xochitl wrapper script is failing, I see the following error in the logs:
> 
> ```
> grep: /opt/etc/xochitl.env.d/*: No such file or directory
> ```

Ah, makes sense. I'll add the folder to the chroot.

**Comment by matteodelabre** [comment]
That did fix the script error, but unfortunately I still don’t have any display output.

**Comment by Eeems** [comment]
> 
> 
> That did fix the script error, but unfortunately I still don’t have any display output.

Anything helpful in the logs? @LinusCDE wasn't having issues when using the builds from my repo.

**Comment by matteodelabre** [comment]
It’s now working, must have been some kind of transient issue.

**Review by matteodelabre — APPROVED** [review]

**Comment by Eeems** [comment]
> 
> 
> It’s now working, must have been some kind of transient issue.

You would have to make sure to kill xochitl, and then  restart tarnish, or reload the applications list before launching it again for the change to take affect.

**Comment by matteodelabre** [comment]
> You would have to make sure to kill xochitl, and then restart tarnish, or reload the applications list before launching it again for the change to take affect.

That must have been something like this yes.

**Comment by LinusCDE** [comment]
I'll review it tomorrow.

**Comment by Eeems** [comment]
> 
> 
> I'll review it tomorrow.

We believe that this is already resolved by #386

**Pull request merged**
