### PR TITLE
Create symlink for rm2fb-server to fix exe name in /proc/<id>/stat

### PR DESCRIPTION
**Pull request by JanLuca**
The current patch just fix the name of rm2fb-server in `/proc/<id>/cmdline` but not the executable name in `/proc/<id>/stat`. Therefore in some process list still the server is shown as `xochitl`. This patch creates a symlink `/opt/bin/rm2fb-server` and use this as exec in the systemd unit.

### CODE REVIEW

**Comment by matteodelabre** [comment]
While this works, a cleaner solution to me would be to use `prctl(PR_SET_NAME, "rm2fb-server");` to set the process name [in rm2fb](https://github.com/ddvk/remarkable2-framebuffer/blob/e594fc4430446f9321b716da8eb0193dc2b2b9f2/src/server/main.cpp#L176). I tested it and it does change the value that appears in `/proc/*/stat`.

**Comment by JanLuca** [comment]
That's right, sounds like a good approach as well. I suggested the symlink idea since your approach needs the patch to change the argv[0] value, too. But I have no strong opinion so let's go with the prctl. I just have seen the problem and wanted to provide a first idea how to fix it :)

**Comment by matteodelabre** [comment]
Do you have a preference? @raisjn

**Comment by raisjn** [comment]
prctl sounds better, thank you (and thanks for finding this, jan)

**Comment by matteodelabre** [comment]
I added the `prctl` call to upstream. I’ll close this PR and open a new one to update the package to the latest upstream release. Thanks for your help @JanLuca!

**Pull request closed without merging**
