### PR TITLE
Update oxide to v2.8.4

### PR DESCRIPTION
**Pull request by Eeems**
[v2.8 Release notes](https://github.com/Eeems-Org/oxide/releases/tag/v2.8)
[v2.8.1 Release notes](https://github.com/Eeems-Org/oxide/releases/tag/v2.8.1)
[v2.8.2 Release notes](https://github.com/Eeems-Org/oxide/releases/tag/v2.8.2)
[v2.8.3 Release notes](https://github.com/Eeems-Org/oxide/releases/tag/v2.8.3)
[v2.8.4 Release notes](https://github.com/Eeems-Org/oxide/releases/tag/v2.8.4)

- Adds landscape and folio support to all oxide apps.
- Add non-versioned symlink for rm2fb-client.
- Add a simple preload that forces any calls to /sys/power/state to use systemd instead.
- Xochitl will no longer be chrooted by oxide and will instead use the new sysfs preload.
- Update sentry to 0.7.6.
- Reduced overall logging.
- Disabled logging that was providing some information to me in telemetry that could be used to identify a user based on wireless networks around their device.

### CODE REVIEW

**Comment by Eeems** [comment]
Fresh install returns the following:
```
Run the following command(s) to use oxide as your launcher
$ systemctl disable --now xochitl
$ systemctl disable --now xochitl
$ systemctl enable --now tarnish
```
It appears our `how-to-enable` code doesn't remove duplicate lines.

**Comment by Eeems** [comment]
Upon further investigation, it's because the results of `get-conflicts tarnish` is the following:
```
xochitl.service
xochitl.service sync.service
```
This will need to be cleaned up.

**Comment by Eeems** [comment]
Tarnish is crashing when trying to run this. I'll have to dig into this before this can be merged. It might require a v2.8.2 release.

**Comment by Eeems** [comment]
Opened https://github.com/Eeems-Org/oxide/issues/354 to resolve this.

**Comment by Eeems** [comment]
It appears that libsysfs_preload is segfaulting on a rM2, which is keeping this from working as expected.

**Comment by Eeems** [comment]
Upon further investigation, this might be due to rm2fb-client and sysfs_preload conflicting somehow. I'm not sure why.

**Review by Jayy001 — APPROVED** [review]

**Pull request merged**
