### PR TITLE
Stable merge for week 45 of 2022

### PR DESCRIPTION
**Pull request by Eeems**
This update brings official support for OS 2.15.1.1189 to toltec.

### Updated Packages

- `ddvk-hacks` - 39.01-1 (#633 #640 #645)
  - Add support for OS
    - 2.14.3.1047
    - 2.15.0.1067
    - 2.15.1.1189
  - Fix hash for rM1 2.14.1.866
- `display` and `rm2fb-client` - 0.0.27 (#634 #643 )
  - Add support for OS
     - 2.14.3.1047
     - 2.15.0.1011
     - 2.15.0.1046
     - 2.15.0.1052
     - 2.15.0.1067
     - 2.15.1.1189
- `kernelctl` - 0.1-5 (#636 #641)
  - Add prune
  - Fix bug where initial install would always fail
- `linux-mainline` - 6.0.0-1 (#637)
- `erode` `fret` `oxide` `rot` `tarnish` `decay` `corrupt` `anxiety` `liboxide` - 2.4-2 (#641)
  - Fix xochitl not being run in chroot
  - Fix systemd and dbus access in chroot
  - Fix sync for xochitl inside chroot when using rmfakecloud-proxy
- `toltec-base` - 1.1-1 (#641)
  - Speed up boot time on 2.15.1.1189 by disabling unused usb1 network interface
  - Disable auto update
- `xochitl` - 0.0.0-14 (#641)
  - Fix issue where xochitl would run even though it was disabled due to how sync.service is configured

### CODE REVIEW

**Review by LinusCDE — COMMENTED** [review]
Tested on the specified version with the rM 2 and `ddvk-hacks`.

Initial update worked fine, but booting takes a long time (a few minutes).

I looked into the logs and can't find the cause. I had remux on it before updating opkg and adding the newest pkgs, but only xochitl is enabled rn.

Logs. Should be of one boot, but might be two: https://haste.cosmos-ink.net/axexuqosuk.log

@matteodelabre Can you reproduce this bug? If not, then it might just be my non-clean setup.

**Comment by Eeems** [comment]
I noticed a long boot on 2.15.0.1067, but I didn't have that issue on 2.15.1.1189. IIRC the kdump and xochitl services failed, and my root partition was full.
I'd recommend always moving your log files to the data partition on upgrade: https://discord.com/channels/385916768696139794/385921709649297409/968207357437943830
```sh
echo "/home/root/.log  /var/log  none  defaults,bind 0 0" >> /etc/fstab
mkdir -p /home/root/.log
journalctl --vacuum-size 1
mv -f /var/log/* /home/root/.log/
mount /var/log
systemctl restart systemd-journald
```
I really need to create a package that does this automatically for us.

**Comment by LinusCDE** [comment]
It doesn't seem space related as already discussed.

My guess is that something is hanging or waiting on remarkable-framebuffers side. Particularily these logs **seem** to be where it starts hanging:

```
Nov 11 17:56:30 reMarkable systemd[1]: Started Login Service.
Nov 11 17:56:32 reMarkable xochitl[195]: Reading waveforms from /usr/share/remarkable/320_R333_AFEE21_ED103TC2U2_VB3300-KCD_TC.wbf
Nov 11 17:56:32 reMarkable xochitl[195]: 1404 1872 16
Nov 11 17:56:32 reMarkable xochitl[195]: WAITING FOR SEND UPDATE ON MSG Q
Nov 11 17:56:32 reMarkable systemd[1]: Started reMarkable 2 Framebuffer Server.
Nov 11 17:56:33 reMarkable systemd[1]: systemd-rfkill.service: Succeeded.
```

Not sure, but would guess that the `WAITING FOR SEND UPDATE ON MSG Q` line is remarkable-framebuffer waiting for something to happen that doesn't? Any idea, @raisjn or @matteodelabre ?

The hang happens after the "Starting" boot screen wants to transition to xochitls loading screen. The screen goes white, stays white for a minute or two and then it seemingly just works. Maybe systemd killing and restarting it after a timeout?

**Comment by LinusCDE** [comment]
It was indeed not rmfb but as Eeems found out an issue with the device files (new pr?). This seems to be a workaround for now as suggested by him:

`systemctl mask sys-subsystem-net-devices-usb1.device`

**Review by LinusCDE — DISMISSED** [review]
Tested on rM 1. Works fine :+1:

**Review by LinusCDE — APPROVED** [review]
I've not tested `kernelctl` yet but will assume it was tested already.

**Pull request merged**
