### PR TITLE
Add support for limiting packages to OS versions

### LINKED ISSUE #445: Warn users when installing Toltec on an unsupported OS version

### LINKED ISSUE #509: toltecctl reenable when already installed
`toltecctl reenable` can mess up if it's already installed. Should we do some sort of check and then require a `--force` flag if we determine it's already installed?

https://discord.com/channels/385916768696139794/385922812121972737/917831080000761906

### LINKED ISSUE #524: Toltecctl doesn't work with built-in wget
This means that using it manually to clean up a bad install will not work, and it gives users a confusing message saying to connect to wifi.

### LINKED ISSUE #559: toltecctl reenable did not recreate the templatectl mount point

### LINKED ISSUE #650: Unable to build packages `assert next_token == "("`
When trying to build any toltec package I am seeing this error:

```shell
$  make koreader
./scripts/package_build.py  "koreader"
Traceback (most recent call last):
  File "/var/home/alistair/sources/remarkable/toltec/./scripts/package_build.py", line 44, in <module>
    repo = Repo(paths.RECIPE_DIR, paths.REPO_DIR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/alistair/sources/remarkable/toltec/scripts/toltec/repo.py", line 56, in __init__
    self.generic_recipes[name] = GenericRecipe.from_file(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/alistair/sources/remarkable/toltec/scripts/toltec/recipe.py", line 45, in from_file
    return GenericRecipe(name, path, recipe.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/alistair/sources/remarkable/toltec/scripts/toltec/recipe.py", line 58, in __init__
    variables, functions = bash.get_declarations(definition)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/alistair/sources/remarkable/toltec/scripts/toltec/bash.py", line 147, in get_declarations
    assert next_token == "("
AssertionError
make: *** [Makefile:60: koreader] Error 1

```

It doesn't matter what package I build, I see the same error.

```shell
$ python3 --version
Python 3.11.0
```

```shell
bash --version
GNU bash, version 5.2.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### LINKED ISSUE #683: During installation, error with 'typed-ast'  python package
During installation of the toltec environment I get the following error:

Requirement already satisfied: wrapt==1.12.1 in ./venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (1.12.1)
Installing collected packages: typed-ast, regex, pyelftools, mypy-extensions, mccabe, certifi, appdirs, urllib3, toml, six, pathspec, mypy, MarkupSafe, lazy-object-proxy, isort, idna, click, chardet, websocket-client, requests, python-dateutil, Jinja2, black, astroid, pylint, docker
  DEPRECATION: typed-ast is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for typed-ast ... error

...

      In file included from ast27/Custom/typed_ast.c:3:
      ast27/Custom/../Include/compile.h:5:10: fatal error: code.h: No such file or directory
          5 | #include "code.h"
            |          ^~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

-------------------------
The process I used, on Ubuntu 23.04.

git clone https://github.com/toltec-dev/toltec
cd toltec
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

### LINKED ISSUE #701: Limit packages to specific OS versions
image
image

Another option is to break down the OS versions into separate "arch" repos like we did with rm1/rm2. This would probably add a bunch of extra complexity to the build process, and increase the size of the repo, or at least require a lot of hard links. It also adds complexity to the install/upgrade flow since we have to then maintain the opkg.conf file.

### PR DESCRIPTION
**Pull request by Eeems**
**For any of those who are just finding this PR and not a toltec maintainer, please just stick to the stable, or testing branches.**

- Port 3.11 and c-string fixes from toltecmk
- Add rmallos2, rmallos3, rm1os2, rm1os3, rm2os2, and rm2os3 archs for limiting packages to only supporting those versions
- Update documentation
- Update known issues packages to only be for 2.x
- Make toltec-base generate a package for each arch to make sure that the folders always get created
- Added experimental toltec branch for testing purposes. You need to add the experimental tag to a PR, and it will start applying changes to the experimental branch.
- Fix various issues with the install and reenable process
- Update toltecctl output to use the same logging as bootstrap

### CODE REVIEW

**Comment by Eeems** [comment]
- [x] Test upgrade path to make sure it adds the 2.x arch
- [x] Test installing on 3.x to make sure it adds the 3.x arch
- [x] Update toltecctl reenable to handle adding new arch repos
- [x] Update compatibility check to have different OS ranges for the 2.x and 3.x arch. Maybe use a list of supported OS versions instead of min/max?
- [x] Sort out deleting 2.x stuff on reenable if there is no 3.x package. ~Probably with a 3.x meta package to force them to be removed.~
- [x] Test upgrade path to make sure it removes the following packages as expected
  - [x] ddvk-hacks
  - [x] fuse
  - [x] wireguard (How does this play with wireguard-tools?)

**Comment by Eeems** [comment]
Changes in this PR are now available on the `experimental` branch. You can switch to this by running the following:
```bash
toltecctl switch-branch experimental
opkg upgrade
```
You can do a fresh install with this branch with the following

```bash
rm bootstrap
wget https://raw.githubusercontent.com/toltec-dev/toltec/multi-repos/scripts/bootstrap/bootstrap
chmod +x bootstrap
toltec_branch=experimental ./bootstrap
```
For any of those who are just finding this PR and not a toltec maintainer, please just stick to the stable, or testing branches.

**Comment by Eeems** [comment]
image
~~Not exactly what I was expecting, as the existing code handles creating `opkg.conf` using the same code.~~

This appears to be due to using `opkg` to compare version numbers.

**Comment by Eeems** [comment]
```
Collected errors:
 * opkg_files_cmd: Package Package not installed.
Package toltec-base version 1.3-1 has no valid architecture, ignoring.
```
This appears to break some things

**Comment by Eeems** [comment]
**For any of those who are just finding this PR and not a toltec maintainer, please just stick to the stable, or testing branches.**


Okay I've tested this, and I'm happy with how it works on a rM1, Someone will need to test on a rM2 though to see what the upgrade path is like. I expect that there may be issues with upgrading and rm2fb not updating properly or something.

I think the following test cases need to be tested at the very least:

1. Stale update 2.x
  - Start on toltec testing branch
  - Manually update `/opt/etc/opkg.conf` and `/opt/etc/opkg.conf.d/15-toltec.conf` to point at experimental instead of testing (Only update the existing lines, don't add more lines)
  - OS upgrade to 3.x
  - `toltecctl reenable`
  - `opkg update` and then `opkg upgrade`, as instructed by the output
2. Normal update 2.x
  - Start on toltec testing branch
  - Manually update `/opt/etc/opkg.conf` and `/opt/etc/opkg.conf.d/15-toltec.conf` to point at experimental instead of testing (Only update the existing lines, don't add more lines)
  - `opkg update && opkg upgrade`
  - `opkg update` and then `opkg upgrade`, as instructed by the output
  - OS upgrade to 3.x
  - `toltecctl reenable`
3. Fresh install 2.x
  - `wget https://raw.githubusercontent.com/toltec-dev/toltec/multi-repos/scripts/bootstrap/bootstrap`
  - `chmod +x bootstrap`
  - `toltec_branch=experimental ./bootstrap`
  - OS upgrade to 3.x
  - `toltecctl reenable`
4. Fresh install 3.x
  - `wget https://raw.githubusercontent.com/toltec-dev/toltec/multi-repos/scripts/bootstrap/bootstrap`
  - `chmod +x bootstrap`
  - `toltec_branch=experimental ./bootstrap`

**Comment by gullradriel** [comment]
> I think the following test cases need to be tested at the very least:

I can say point 2. and point 3. are working perfectly on rm2, as I tested them myself.

**Comment by gullradriel** [comment]
webinterface-onboot reports a conflict with ddvk-hacks, which is owned by toltec-deletion.
Installation of webinterface-onboot worked fine forced with --force-depends

**Comment by Eeems** [comment]
Test scenario 1 on my new rM2 results in the following:
image

**Comment by Eeems** [comment]
Test scenario 1 on a rM2 produces the following error:
image

This is probably part of why:
image


Edit: Ah, I forgot to edit the underlying `opkg.conf.d/*.conf` files.

**Comment by Eeems** [comment]
image

**Comment by Eeems** [comment]
Sure enough, the sha256sum in `Packages.gz` doesn't match the file downloaded. I'll trigger a rebuild.

**Comment by Eeems** [comment]
Alright that's odd, the file in the github action matches the sha256sum, but the one I get when downloading does not. @matteodelabre do you have any ideas why?

**Comment by Eeems** [comment]
This also breaks test case 4

**Comment by matteodelabre** [comment]
Cannot replicate right now as it seems that a subsequent deploy fixed the issue. It is still worth investigating why that happened, though. Please reach out if the issue surfaces again.

**Comment by Eeems** [comment]
While trying test case 1 on a rM2
image

I would consider this working as expected, as it instructs the user to `opkg update && opkg upgrade` again. These don't error.

**Comment by Eeems** [comment]
@matteodelabre I'm getting the checksum error again while running through test case 2.
image

**Review by JohnRigoni — APPROVED** [review]

**Review by Jayy001 — APPROVED** [review]
lgtm

**Pull request merged**
