### PR TITLE
Update bootstrap wget to 1.21.1

### PR DESCRIPTION
**Pull request by matteodelabre**
This contains only minor changes, and no registered CVEs that I could find. See the full changelog: <https://github.com/toltec-dev/wget/commit/ca68c38e890362f28b015f0fc2708107adbfc480>.

### CODE REVIEW

**Review by Eeems — CHANGES_REQUESTED** [review]
Also update toltec-bootstrap version

**Comment by matteodelabre** [comment]
Good catch, thanks

**Review by Eeems — DISMISSED** [review]
lgtm, I haven't tested though.

**Comment by matteodelabre** [comment]
I tested it on my rM1 and it works correctly. Guess we can defer the rM2 testing until the merge window.

**Comment by Eeems** [comment]
Works for me, unless @raisjn wants to test before we merge.

**Comment by matteodelabre** [comment]
Just realized that the wget binary is not stripped. I’m re-releasing toltec-dev/wget, please don’t merge yet.

**Comment by matteodelabre** [comment]
Done. Confirmed working on my rM1. This change makes the script faster (pulls 3 MB instead of 20 MB).

**Review by Eeems — APPROVED** [review]

**Comment by LinusCDE** [comment]
Binary the binary runs on rM 2 without a problem. So I assume it'll work in the bootstrap as well.

**Pull request merged**
