### PR TITLE
Update ddvk-hacks to 30.01-1

### PR DESCRIPTION
**Pull request by EntrixIII**
Tested 30.2.05 successfully on rm2.

I was unsure about name, considering ddvk has published about 5-6 versions of 30 already. (30.1.06 and 30.2.05).
So, I simply based myself off the name from #514, but up to date.

## Changelogs
For 30: https://github.com/ddvk/remarkable-hacks/blob/master/patches/2121527_rm2/readme.md
For 29: https://github.com/ddvk/remarkable-hacks/blob/master/patches/2110442_rm2/readme.md

### CODE REVIEW

**Comment by EntrixIII** [comment]
Requesting review from @matteodelabre, maintainer of the package (ddvk-hacks).

**Comment by matteodelabre** [comment]
I can look at this over the week-end. Thanks for the PR!

**Comment by EntrixIII** [comment]
ddvk updated ddvk-hacks 2.12 again.
This version should have fixed https://github.com/ddvk/remarkable-hacks/issues/416 (see changelog).
Edit: whoops commit message mentions issue 417 :|
Edit2: fixed it by rebasing and force pushing :/

**Comment by EntrixIII** [comment]
I forgot to update the source when updating the paths :/
This should now build.

**Review by LinusCDE — APPROVED** [review]
Tested on both models. Lgtm!

**Comment by matteodelabre** [comment]
@LinusCDE Thank you ! :-)

**Pull request merged**
