### PR TITLE
Add rm2-suspend-fix

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
@snelg Have you had a chance to test this to see if it works properly?

**Comment by snelg** [comment]
> @snelg Have you had a chance to test this to see if it works properly?

Yep. Sorry, I posted a reply in the koreader thread a few days ago, but didn't tag you.

Works fine.

**Comment by Eeems** [comment]
@snelg Was that with this package installed, or just doing the rmmod/modprobe calls another way?

**Comment by snelg** [comment]
Manually copied `rm2-suspend-fix.sh` into `/lib/systemd/system-sleep/`, and suspend/wake worked as expected.

I wasn't sure how to properly use toltec to install a package from an arbitrary branch, though, so technically I didn't fully test the package itself.

**Comment by Eeems** [comment]
> 
> 
> Manually copied `rm2-suspend-fix.sh` into `/lib/systemd/system-sleep/`, and suspend/wake worked as expected.
> 
> I wasn't sure how to properly use toltec to install a package from an arbitrary branch, though, so technically I didn't fully test the package itself.

You can download the repo from the build here: https://github.com/toltec-dev/toltec/suites/1794253243/artifacts/34371048
All you need to transfer to your device is the rm2-suspend-fix ipkg file from inside the archive. After which you can install it with: `okg install <path/to/file>`

Also, it would be good to confirm that the rmmod/modprobe are actually being called by checking the `dmesg` output.

**Comment by snelg** [comment]
Ah, didn't know you could specify arbitrary paths in `opkg install`. I'll test it out a little later.

**Comment by snelg** [comment]
Properly tested :)

```
> opkg install /home/root/rm2-suspend-fix_0.0.0-1_armv7-3.2.ipk`
> systemctl suspend`

[press power button to wake up]

> dmesg

[52825.642302] brcmfmac: brcmf_fil_cmd_data: bus is down. we have nothing to do.
[52825.649461] brcmfmac: brcmf_cfg80211_get_channel: chanspec failed (-5)
[52825.857611] PM: suspend entry (deep)

[...]

[52826.645238] PM: suspend exit
[52826.901458] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000009
[52827.022479] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available(err=-2), device may have limited channels available
[52827.022836] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Sep 27 2019 15:21:10 version 7.45.96.53 (5a84613@shgit) (r745790) FWID 01-54faa385 es7.c5.n4.a3
```


And just to be certain:
```
> opkg remove rm2-suspend-fix`
> systemctl suspend`

[power button]

> dmesg
```
No `brcmfmac` lines in dmesg output

**Review by raisjn — APPROVED** [review]

**Pull request merged**
