### PR TITLE
[build] only build new artifacts during PRs should work for stable too

### PR DESCRIPTION
**Pull request by raisjn**

### CODE REVIEW

**Review by matteodelabre — APPROVED** [review]
LGTM

**Comment by raisjn** [comment]
this still needs testing (i guess i can put it in a PR on stable and see what happens)

**Comment by matteodelabre** [comment]
I tested the command locally, replacing the placeholder alternatively with stable and testing, and it produces the expected result.

**Comment by Eeems** [comment]
Will this be a problem with the rsync --delete changes?

**Pull request merged**
