### PR TITLE
Update KOReader

### PR DESCRIPTION
**Pull request by Eeems**
Will only happen if `rot` is available

### CODE REVIEW

**Comment by Eeems** [comment]
Test scenarios:

- Oxide is not installed
- Oxide is installed but not enabled or running
- Oxide is installed and running (Should automatically register with the correct settings)
- Test on both rM1 and rM2

**Review by LinusCDE — CHANGES_REQUESTED** [review]
**EDIT:** When speaking of suspending/resuming, I meant the KOReader app only and not the sleepscreen. I missed that this could be misinterpreted.

When testing with remux at first, I encountered some glitching when switching the folder pages.

&nbsp;

Some pages were fine, but some glitched like above without a clear pattern on which turn this happens.

It seems only to happen when remux is enabled on boot and regardless of whether oxide is installed. @raisjn 


**Oxide is not installed**

Works. Only when remux is used, the first time launching the files are glitched (even suspending is enough until probably a reboot).

**Oxide is installed but not enabled or running**

Same as above

**Oxide is installed and running (Should automatically register with the correct settings)**

Cool start works fine. When suspending directly to oxide, there is a chance of the screen getting misconfigured (probably mismatch between set size and assumed size of the framebuffer). Launching erode (middle button) then or either before returning to oxide seems to work around this problem. (Taking a screenshot got the expected result though. Maybe just another refresh needed?)



When resuming koreader, I get this view however (both images are updated).


**Test on both rM1 and rM2** => Only rM 1

**Comment by raisjn** [comment]
thanks for the indepth testing! the latest remux from build.rmkit.dev/master/latest has fixes for koreader which might help here

**Comment by Eeems** [comment]
@LinusCDE could you test the suspend/resume with the v2.1 branch of oxide? It looks like there might be timing issues with the onPause/onResume there.

**Comment by LinusCDE** [comment]
> @LinusCDE could you test the suspend/resume with the v2.1 branch of oxide? It looks like there might be timing issues with the onPause/onResume there.

Built the v2.1 branch (`make release`) and copied all binaries (and the /etc/dbus thing) over my existing ones in `/opt/bin` (current toltect testing branch).

I still get the "screen corruption" when leaving directly to oxide (left button). It doesn't seem to happen any second time though when KOReader was not killed.

It also seems that you are not clearing the sceen as much anymore which leaves some residue when launching erode (middle button) and returning.

&nbsp;

So it behaves a bit differently, but still has problems.

---

> thanks for the indepth testing! the latest remux from build.rmkit.dev/master/latest has fixes for koreader which might help here

Couldn't reproduce the bug anymore with the updated binary. :+1:

**Comment by LinusCDE** [comment]
Reinstalling koreader now fixes the issue. The missing onPause/onResume values in tarnish.conf were added and seem to have been the problem. Probably just ensure that people who update koreader get these changes as well and then it should work.

**Comment by Eeems** [comment]
Hmm, well 

> Reinstalling koreader now fixes the issue. The missing onPause/onResume values in tarnish.conf were added and seem to have been the problem. Probably just ensure that people who update koreader get these changes as well and then it should work.

Added code to handle removing the application entry on remove that should handle this in the future. Maybe I'll also add it to the configure.

**Comment by Eeems** [comment]
Still fighting with the code to make it more robust. It would be great if you could share functions.

**Comment by Eeems** [comment]
Okay, so the configure script works properly, but the postremove script doesn't seem to run ever. When I source the package file on the device and run postremove it works properly. @matteodelabre thoughts?

**Comment by LinusCDE** [comment]
~~If you mean bash functions, you can probably just nest them in this case.~~

**Review by LinusCDE — CHANGES_REQUESTED** [review]
It somehow still does not add the onPause and onResume to `tarnish.conf`. Now I fail to get it even forced in by either deleting the `tarnish.conf`, removing & installing koreader, fore-reinstalling koreader or some combinations.

EDIT: Using oxide 2.0.1~beta-1

**Comment by Eeems** [comment]
> It somehow still does not add the onPause and onResume to `tarnish.conf`. Now I fail to get it even forced in by either deleting the `tarnish.conf`, removing & installing koreader, fore-reinstalling koreader or some combinations.
> 
> EDIT: Using oxide 2.0.1~beta-1

With `jq` installed?

**Comment by LinusCDE** [comment]
> > It somehow still does not add the onPause and onResume to `tarnish.conf`. Now I fail to get it even forced in by either deleting the `tarnish.conf`, removing & installing koreader, fore-reinstalling koreader or some combinations.
> > EDIT: Using oxide 2.0.1~beta-1
> 
> With `jq` installed?

Yes. But rot wasn't for this particular test. Maybe it should just be a dependency?

- With rot, entries get added and removed properly.
- Upgrading from 2020.10-2 to this version didn't update the onPause and onResume lines, so oxide was still broken when quitting.
- Removing and installing this version didn't work either.

EDIT: Giving the tarnish service a look makes it seem that it doesn't take notice of the app getting added or removed. Maybe oxide should get updated first?

**Comment by Eeems** [comment]
> 
> Yes. But rot wasn't for this particular test. Maybe it should just be a dependency?
> 
>     * With rot, entries get added and removed properly.
> 
>     * Upgrading from 2020.10-2 to this version didn't update the onPause and onResume lines, so oxide was still broken when quitting.
> 
>     * Removing and installing this version didn't work either.
> 
> 
> EDIT: Giving the tarnish service a look makes it seem that it doesn't take notice of the app getting added or removed. Maybe oxide should get updated first?

rot is a dependency of oxide now, but maybe not for the version you have installed. If rot is making the calls, it will notice that changes, since all rot does is make calls out to tarnish and have it handle it.

**Comment by raisjn** [comment]
i should have brought this up earlier, but why does koreader package need to do special calls for oxide? (is it the onPause/onResume commands?) it seems like this should really be solved by config file (i think you are doing this because i saw config file stuff in oxide commits) + a SIGHUP to tarnish.

**Comment by Eeems** [comment]
> i should have brought this up earlier, but why does koreader package need to do special calls for oxide? (is it the onPause/onResume commands?) it seems like this should really be solved by config file (i think you are doing this because i saw config file stuff in oxide commits) + a SIGHUP to tarnish. 

Because KOReader changes the bitdepth of the display by default, and oxide didn't have pgroup signals yet. v2.1 of oxide has a new file format for applications installed in a package that will solve all of this though.

**Comment by LinusCDE** [comment]
Retested with the testing version of oxide. Same behaviour as before.

**Comment by Eeems** [comment]
> Retested with the testing version of oxide. Same behaviour as before.

What output are you getting during the install?

**Comment by LinusCDE** [comment]
> > Retested with the testing version of oxide. Same behaviour as before.
> 
> What output are you getting during the install?

I get the Removed app and added app lines when removing/installing the app respectively. `journalctl -fu tarnish` doesn't show any lines regarding this lines though.

**Review by LinusCDE — APPROVED** [review]
Even though the resize problems still persist, they most likely do so for the older version as well. Fixing this will be a goal for a future PR.

The app registers fine now using the older draft method.

**Comment by Eeems** [comment]
v2.1 will have a proper solution.

**Pull request merged**
