### PR TITLE
Update yaft to v0.1.1

### PR DESCRIPTION
**Pull request by Eeems**
[Release notes v0.1.0](https://github.com/timower/rM2-stuff/releases/tag/v0.1.0)
[Release notes v0.1.1](https://github.com/timower/rM2-stuff/releases/tag/v0.1.1)

### CODE REVIEW

**Comment by Eeems** [comment]
@timower For some reason, the icon that gets included is broken.

2023-12-06T205544 318
yaft

**Comment by timower** [comment]
Same issue, git LFS file not being pulled.

**Comment by gbyl** [comment]
Works great on rM1. I've been running the artifact from the last commit for about a week. Tested: `vim`, `htop`, `ncdu`, `lf`, `btm`.

**Comment by Eeems** [comment]
> Works great on rM1. I've been running the artifact from the last commit for about a week. Tested: `vim`, `htop`, `ncdu`, `lf`, `btm`.

Thanks! I've also been using it. I just need someone to test on a rM2, and get another maintainer to approve this PR so it can be merged.

**Comment by Eeems** [comment]
Tested on my new rM2 and it works :sunglasses:

**Review by raisjn — APPROVED** [review]

**Pull request merged**
