### PR TITLE
[rmkit] update to latest version (11.07.2020)

### PR DESCRIPTION
**Pull request by raisjn**
* add memory stats to remux dialog
* show running app in remux
* fix harmony missing SAVE_DIR (finally)
* fix remux multi-launch issue (no bug, but clutters logs)

### CODE REVIEW

**Comment by matteodelabre** [comment]
Thanks! I think that you need to increase the pkgver of remux and harmony.

> * fix harmony missing SAVE_DIR (finally)

Does this mean that we can remove the `configure()` section on lines 37–39 of the recipe?

**Comment by raisjn** [comment]
good catch, thanks! i'll bump pkgver for harmony and remux

**Comment by raisjn** [comment]
I will have to test, but yes, this should address the package making the SAVE_DIR

**Comment by matteodelabre** [comment]
Just tested and it works, even if I remove the save dir before launching harmony. Good job! I’ll remove the configure section from the package and merge.

**Review by matteodelabre — APPROVED** [review]

**Pull request merged**
