### PR TITLE
Stable merge for week 4 of 2024

### LINKED ISSUE #748: Folly build broken
**Describe the issue**
Building folly is currently broken

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to build folly
2. It will fail to build

**Expected behaviour**
It should build successfully.

**Upstream issue**
https://github.com/bkirwi/folly/issues/2

**Additional context**
https://github.com/toltec-dev/toltec/actions/runs/6686361561/job/18165646849?pr=700#step:4:125
```
[   ERROR] toltec.builder: folly [rmall]: error: failed to run custom build command for `tflite v0.9.4 (https://github.com/bkirwi/tflite-rs?rev=4212a1bf33ebbcbf535b162cc591d46c7d054d92#4212a1bf)`
[   ERROR] toltec.builder: folly [rmall]: 
[   ERROR] toltec.builder: folly [rmall]: Caused by:
[   ERROR] toltec.builder: folly [rmall]: process didn't exit successfully: `/src/target/release/build/tflite-afdb010debeb3618/build-script-build` (exit status: 101)
[   ERROR] toltec.builder: folly [rmall]: --- stderr
[   ERROR] toltec.builder: folly [rmall]: thread 'main' panicked at '"aligned_storage_type_(unnamed_struct_at_/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/10_3_0/type_traits_2074_2)" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.26/src/fallback.rs:696:9
[   ERROR] toltec.builder: folly [rmall]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[   ERROR] toltec.builder: folly [rmall]: warning: build failed, waiting for other jobs to finish...
[   ERROR] toltec.builder: folly [rmall]: error: build failed
[   ERROR] toltec.builder: folly [rmall]: build() failed
```

### PR DESCRIPTION
**Pull request by Eeems**
### New Packages
- `move-logs-to-opt` - 0.0.1-1 (#821)
  - Move log files to `/opt` to avoid filling up the root partition.
- `oxide-extra` and `liboxide-dev` - 2.7-3 (#760)

### Updated Packages
- `folly` - 0.0.1-4 (#823)
- `koreader` - 2024.01-1 (#826)
- `linux-stracciatella` - 5.4.70.4-1 (#808)
- `oxide`,  `oxide-utils`, `inject_evdev`, and `liboxide` - 2.7-3 (#760)
- `puzzles` - 0.2.4-4 (#785)
- `rm2-suspend-fix` - 0.0.0-3 (#821)
- `genie` - 0.1.7-1 (#825)
- `harmony` - 0.2.3-1 (#825)
- `iago` - 0.1.2-1 (#825)
- `remux` - 0.3.0-1 (#825)
- `simple` - 0.2.1-1 (#825)
- `tilem` - 0.1.1-1 (#764)
- `toltec-base` - 1.3-1 (#806)
- `yaft` - 0.1.1 (#763)
- `zoneinfo-utils` - 2023c-1 (#702)
- `rmfakecloud-proxy` - 0.0.3-5 (#757 #831)

### Packages removed
- `erode`, `tarnish`, `decay`, and `corrupt`
  - Replaced by `oxide`
- `fret`, and `anxiety`
  - Replaced by `oxide-extra`
- `rot`
  - Replaced by `oxide-utils`

### CODE REVIEW

**Comment by Eeems** [comment]
This needs #831 in order to merge to stable

**Comment by rM-self-serve** [comment]
Device: rM1
Version: 2.10.2.356

I am not sure if this is an issue with zoneinfo-utils or timedatectl but I am not able to set the timezone.
zoneinfo-utils2023c_rm1-v2 10 2 356
I also tried America/Bahia to no avail. Will try v2.15 soon.

**Comment by Eeems** [comment]
> Device: rM1 Version: 2.10.2.356
> 
> I am not sure if this is an issue with zoneinfo-utils or timedatectl but I am not able to set the timezone. zoneinfo-utils2023c_rm1-v2 10 2 356 I also tried America/Bahia to no avail. Will try v2.15 soon.

Could you double-check to make sure that the bind mount is active?

https://github.com/toltec-dev/toltec/blob/2cad2a2a5443c9d3bf9593d36320d214eadf8c61/package/zoneinfo-utils/package#L71-L72

Timedatectl will list the full list, even if they aren't available. That said, installing this will make more available. By default, it'll just install `zoneinfo-core`, so you may need to also install one of the other `zoneinfo-*`packages (https://remarkable.guide/guide/config/timezone.html#available-timezones).

**Comment by rM-self-serve** [comment]
Looks like it is. I will look further into it.

zoneinfo-mount

**Comment by rM-self-serve** [comment]
It set Europe/London fine so no worries.

**Comment by rM-self-serve** [comment]
Device: rM1
Version: 2.10.2.356

Genie does not seem to be able to load the config at /opt/etc/genie.conf
genie-0 1 7-1_rm1-2 10

I also tried ~/.config/genie/genie.conf to no avail.

**Comment by Eeems** [comment]
> Device: rM1 Version: 2.10.2.356
> 
> Genie does not seem to be able to load the config at /opt/etc/genie.conf genie-0 1 7-1_rm1-2 10
> 
> I also tried ~/.config/genie/genie.conf to no avail.

Have you put config in `/opt/etc/genie.conf` yet? The package only creates `/opt/etc/genie.example.conf`, and assumes that the user will create a configuration file.

**Comment by rM-self-serve** [comment]
Yeah you can see the contents in the screenshot

**Comment by Eeems** [comment]
> Yeah you can see the contents in the screenshot

Apologies, it's late. Have you tried running the genie service instead of running it by hand?

**Comment by rM-self-serve** [comment]
That works just fine, looks like the config path needs to follow the command if it is not in the current directory.

Via genie.service ExecStart=/opt/bin/genie /opt/etc/genie.conf

**Comment by rM-self-serve** [comment]
Oxide seems to be failing while upgrading due to fret. I did a fresh install of oxide 2.6-3 from the stable toltec repo and had it working fine. Then I added the testing packages to a local repo. When installing oxide 2.7-3, it seems to have an issue with fret. 

I will also mention I installed the .ipk from .cache before configuring the local repo and in that case I had issues with fret as well, where I had to remove it manually.

oxide_upgrade

Oxide still seems to work fine and then I can remove fret no problem.

**Comment by Eeems** [comment]
> Oxide seems to be failing while upgrading due to fret. I did a fresh install of oxide 2.6-3 from the stable toltec repo and had it working fine. Then I added the testing packages to a local repo. When installing oxide 2.7-3, it seems to have an issue with fret.
> 
> I will also mention I installed the .ipk from .cache before configuring the local repo and in that case I had issues with fret as well, where I had to remove it manually.
> 
> oxide_upgrade
> 
> Oxide still seems to work fine and then I can remove fret no problem.

I see that you are "upgrading" by telling it to install the oxide package. Could you try this test by doing the recommended full system upgrade, so that all package updates can be processed at once? https://remarkable.guide/guide/software/toltec.html#updating-your-installation

**Comment by rM-self-serve** [comment]
Here is the output from an upgrade, still seem to be catching some error with fret. 

```
reMarkable: ~/ opkg upgrade
Upgrading genie on root from 0.1.6-3 to 0.1.7-1...
Downloading file:///home/root/packages/local/rmall/genie_0.1.7-1_rmall.ipk
Upgrading oxide-utils on root from 2.6-3 to 2.7-3...
Downloading file:///home/root/packages/local/rmall/oxide-utils_2.7-3_rmall.ipk
Installing libpython3 (3.11.7-1) to root...
...
Installing reboot-guard (1.0.1-8) to root...
Downloading https://toltec-dev.org/stable/rmall/reboot-guard_1.0.1-8_rmall.ipk
Upgrading liboxide on root from 2.6-3 to 2.7-3...
Downloading file:///home/root/packages/local/rmall/liboxide_2.7-3_rmall.ipk
Removing obsolete file /opt/lib/libliboxide.so.2.6.0.
Removing obsolete file /opt/lib/libliboxide.so.2.6.
Upgrading oxide-utils on root from 2.6-3 to 2.7-3...
Removing package rot from root...
Upgrading oxide on root from 2.6-3 to 2.7-3...
Downloading file:///home/root/packages/local/rmall/oxide_2.7-3_rmall.ipk
Removing package decay from root...
Reloading Oxide applications: Done!
Removing package tarnish from root...
Stopping tarnish.service
Disabling tarnish.service
Removed /etc/systemd/system/multi-user.target.wants/tarnish.service.
Removed /etc/systemd/system/launcher.service.
Removing package erode from root...
Upgrading zoneinfo-utils on root from 2021a-2 to 2023c-1...
Downloading file:///home/root/packages/local/rmall/zoneinfo-utils_2023c-1_rmall.ipk
Upgrading oxide-extra (2.7-3) to root...
Downloading file:///home/root/packages/local/rmall/oxide-extra_2.7-3_rmall.ipk
Removing package fret from root...
oxide (2.7-3) already install on root.
Upgrading iago on root from 0.1.1-2 to 0.1.2-1...
Downloading file:///home/root/packages/local/rmall/iago_0.1.2-1_rmall.ipk
Upgrading rmfakecloud-proxy on root from 0.0.3-4 to 0.0.3-5...
Downloading file:///home/root/packages/local/rmall/rmfakecloud-proxy_0.0.3-5_rmall.ipk
Upgrading koreader on root from 2023.10-2 to 2024.01-1...
Downloading file:///home/root/packages/local/rmall/koreader_2024.01-1_rmall.ipk
Removing obsolete file /opt/koreader/libs/libutf8proc.so.2.
Removing obsolete file /opt/koreader/libs/libcrengine.so.
Removing obsolete file /opt/koreader/libs/libglib-2.0.so.0.
Upgrading simple on root from 0.2.0-2 to 0.2.1-1...
Downloading file:///home/root/packages/local/rmall/simple_0.2.1-1_rmall.ipk
Upgrading linux-stracciatella on root from 5.4.70-3 to 5.4.70.4-1...
Downloading file:///home/root/packages/local/rm1/linux-stracciatella_5.4.70.4-1_rm1.ipk
Removing obsolete file /opt/usr/share/kernelctl/stracciatella-5.4.70.tar.bz2.
Upgrading harmony on root from 0.2.2-2 to 0.2.3-1...
Downloading file:///home/root/packages/local/rmall/harmony_0.2.3-1_rmall.ipk
oxide-utils (2.7-3) already install on root.
oxide (2.7-3) already install on root.
oxide (2.7-3) already install on root.
liboxide (2.7-3) already install on root.
Upgrading remux on root from 0.2.4-2 to 0.3.0-1...
Downloading file:///home/root/packages/local/rmall/remux_0.3.0-1_rmall.ipk
Upgrading toltec-base on root from 1.2-3 to 1.3-1...
Downloading file:///home/root/packages/local/rm1/toltec-base_1.3-1_rm1.ipk
Upgrading tilem on root from 0.0.7-3 to 0.1.1-1...
Downloading file:///home/root/packages/local/rmall/tilem_0.1.1-1_rmall.ipk
Upgrading yaft on root from 0.0.10-2 to 0.1.1-1...
Downloading file:///home/root/packages/local/rmall/yaft_0.1.1-1_rmall.ipk
oxide (2.7-3) already install on root.
Configuring toltec-base.
Disabling automatic update
Disabling usb1 network device to avoid long boots
Created symlink /etc/systemd/system/busybox-ifplugd@usb1.service → /dev/null.
Configuring genie.
Run 'systemctl enable genie --now' to enable genie
Configuring libpython3.
Configuring python3-base.
Configuring libbz2.
Configuring python3-light.
Configuring python3-asyncio.
Configuring python3-email.
Configuring python3-cgi.
Configuring python3-pydoc.
Configuring python3-cgitb.
Configuring python3-codecs.
Configuring libffi.
Configuring python3-ctypes.
Configuring libgdbm.
Configuring python3-dbm.
Configuring python3-decimal.
Configuring python3-distutils.
Configuring python3-logging.
Configuring liblzma.
Configuring python3-lzma.
Configuring python3-multiprocessing.
Configuring python3-ncurses.
Configuring python3-openssl.
Configuring libreadline.
Configuring python3-readline.
Configuring libsqlite3.
Configuring python3-sqlite3.
Configuring python3-unittest.
Configuring python3-urllib.
Configuring libuuid.
Configuring python3-uuid.
Configuring python3-xml.
Configuring python3.
Configuring reboot-guard.
Configuring liboxide.
Configuring oxide.

Run the following command(s) to use oxide as your launcher
$ systemctl enable --now tarnish

Configuring oxide-utils.
Configuring zoneinfo-utils.
Bind mount configuration for '/usr/share/zoneinfo' already exists, updating
Configuring oxide-extra.
Configuring iago.
Configuring rmfakecloud-proxy.
Status: disabled (inactive)
Upstream server: (not set)
Run `rmfakecloudctl enable` to enable rmfakecloud-proxy.
Run `rmfakecloudctl set-upstream https://<server>` to set the upstream server.
Configuring koreader.

Run the following command(s) to use koreader as your launcher
$ systemctl enable --now koreader

Configuring simple.
Configuring linux-stracciatella.
The new kernel files have been copied, but not installed.
Please use kernelctl to select the kernel to boot.
Configuring harmony.
Configuring remux.

Run the following command(s) to use remux as your launcher
$ systemctl enable --now remux

Configuring tilem.
Configuring yaft.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency fret (= 2.6-3) for oxide
reMarkable: ~/ 

```

**Comment by Eeems** [comment]
This is very odd as the `oxide` package no longer depends on `fret`. It's been removed and replaced with `oxide-extra`, as expected.

What does `opkg info oxide` output? As well as, does `opkg configure` fail with the dependency issue again?

**Comment by rM-self-serve** [comment]
No errors on opkg configure.

```
reMarkable: ~/ opkg info oxide
Package: oxide
Version: 2.6-3
Depends: erode (= 2.6-3), rot (= 2.6-3), liboxide (= 2.6-3), fret (= 2.6-3), decay (= 2.6-3), libsentry (= 0.5.0), tarnish (= 2.6-3), rm2fb-client, oxide-utils (= 2.6-3)
Status: unknown ok not-installed
Section: launchers
Architecture: rmall
Maintainer: Eeems <eeems@eeems.email>
Size: 1122731
Filename: oxide_2.6-3_rmall.ipk
Description: Launcher application

Package: oxide
Version: 2.7-3
Depends: libsentry (= 0.5.0), reboot-guard, liboxide (= 2.7-3), oxide-utils (= 2.7-3), rm2fb-client
Replaces: decay, tarnish, erode, corrupt
Conflicts: decay, tarnish, erode, corrupt
Status: install user installed
Section: launchers
Architecture: rmall
Maintainer: Eeems <eeems@eeems.email>
Size: 2452843
Filename: oxide_2.7-3_rmall.ipk
Description: Launcher application
Installed-Time: 1713821035

reMarkable: ~/ opkg configure
reMarkable: ~/ 
```

**Comment by Eeems** [comment]
So there are two `oxide` entires, likely one for each repo. The one that's marked as installed doesn't depend on `fret` though. This may be an `opkg` bug that wont be an issue when there is only one source for oxide. I'm suprised this is the first time we've encountered this. Could you try commenting out the toltec repos from your opkg.conf.d entry, then rebuild the opkg.conf and try again to see if it's because of the dual entries?

**Comment by rM-self-serve** [comment]
I commented out the toltec repos and no longer see the error, that seemed to work.

**Comment by Eeems** [comment]
> I commented out the toltec repos and no longer see the error, that seemed to work.

Alright, so users will not encounter this. It's rather annoying to properly test this kind of thing though. I may have to take some time to document how to get a full copy of the local repo setup on a host machine to test with, instead of copying just the changed files to the tablet and using a localrepo there.

**Comment by rM-self-serve** [comment]
Packages were upgraded from a local repo on v2.15 then reenabled on v2.10.

|package|notes|pass
|---|---|---|
|move-logs-to-opt|contains 20K of data|yes|
|oxide-extra, liboxide-dev, oxide, oxide-utils, inject_evdev, liboxide|set as launcher, killed process in manager, set timezone|yes|
|folly|passed the tutorial|yes|
|koreader|opened epub and pdf files|yes|
|linux-stracciatella|plugged in keyboard|yes|
|puzzles|played train track game|yes|
|genie|observed output from swipe|yes|
|harmony|drew a picture|yes|
|iago|drew a rectangle|yes|
|remux|launched/killed programs|yes|
|simple|ran nao|yes|
|tilem|characters blink when entered but same behavior as last version|yes|
|yaft|ran neofetch|yes|
|zoneinfo-utils|changed timezones and observed long list of zones|yes|
|toltec-base|ran toltec reenable|yes|
|rm2-suspend-fix|can't test|n/a|
|rmfakecloud-proxy|enabled and disabled, can't test server compatibility|n/a|

**Comment by Eeems** [comment]
I've gone through a fresh install of 2.15 and toltec on my rM2 and then ran through an update and double-checked `rm2-suspend-fix` and `rmfakecloud-proxy`. This should be good to merge.

**Review by raisjn — APPROVED** [review]

**Pull request merged**
