### PR TITLE
use HEAD request instead of GET when checking file existence on remote server

### PR DESCRIPTION
**Pull request by raisjn**
what do you think? (it could probably be better in terms of cleanliness)

### CODE REVIEW

**Comment by Eeems** [comment]
lgtm

**Comment by matteodelabre** [comment]
I'm always for saving network usage but with this change the `Packages`, `Packages.gz` and `Packages.stamps` files generated at the end of the `repo-build` script will only contain the newly updated packages. When the GitHub actions are run, those incomplete indexes will overwrite the previous ones, and therefore users of Opkg will only have access to a subset of the packages.

**Comment by raisjn** [comment]
there should be some way of using it for local building so we don't re
download files when running `make repo'

**Comment by raisjn** [comment]
alternatively, the generation of packages.gz can happen on remote server

**Comment by matteodelabre** [comment]
What about changing the `repo-build` script and `make repo` target so that they do not remove the build working directory every time they are run? Existing packages from the previous runs could be kept in place without doing anything, and the download would only happen on the first run.

**Comment by raisjn** [comment]
yes, that's a good idea. will save my bandwidth but not the ci servers, but I'm fine with that

**Pull request closed without merging**
