### PR TITLE
Update discord shield server ID

### PR DESCRIPTION
**Pull request by Ameb**
I have enabled the server widget on Discord, so the shield now displays the number of active users on the discord!

Cheers

### CODE REVIEW

**Comment by danshick** [comment]
Cool, this is neat.

I think even for small changes to the README, we'd want PRs to target "testing" and not "stable", mostly so that both branches are kept in sync. That's why the checks are failing.

**Comment by Eeems** [comment]
@Ameb could you rebase this on the testing branch.

**Comment by Ameb** [comment]
Shall i open another pull request into `testing`? (branching from there, cherrypick, rebase)

Eebasing the patch branch into testing will produce conflicts (As this branch is based on `stable`)

**Comment by Eeems** [comment]
> 
> 
> Shall i open another pull request into `testing`? (branching from there, cherrypick, rebase)

You can also do that. Might be easier to just recreate your branch locally and force push it up.

**Comment by Ameb** [comment]
Voilà

**Review by Eeems — APPROVED** [review]
lgtm

**Pull request merged**
