### PR TITLE
Add cache for python dependencies install

### LINKED ISSUE #472: Cache dependency install
https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
https://stackoverflow.com/a/59277514

This might speed up the builds slightly.

### PR DESCRIPTION
**Pull request by Eeems**
Fix #472

### CODE REVIEW

**Comment by Eeems** [comment]
Looks like this cut the install time with a fully primed cache from ~50s to ~30. It might be possible to cut down time even more by caching the entire python environment instead of just the pip cache, as recommended in the article in #472

**Comment by matteodelabre** [comment]
Thanks for this! I found the following error in the first caching step while inspecting this PR’s CI log:

```console
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/987aaa91-4997-4841-9cab-1d8b9faf2da5/cache.tzst -P -C /home/runner/work/toltec/toltec
/usr/bin/tar: ../../../../../usr/bin/bsdcat: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/bin/bsdcpio: Cannot open: Permission denied
/usr/bin/tar: ../../../../../usr/bin/bsdtar: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```

Is this expected? Other caches seem fine.

**Comment by Eeems** [comment]
> 
> 
> Thanks for this! I found the following error in the first caching step while inspecting this PR’s CI log:
> 
> ```
> /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/987aaa91-4997-4841-9cab-1d8b9faf2da5/cache.tzst -P -C /home/runner/work/toltec/toltec
> /usr/bin/tar: ../../../../../usr/bin/bsdcat: Cannot open: Permission denied
> /usr/bin/tar: ../../../../../usr/bin/bsdcpio: Cannot open: Permission denied
> /usr/bin/tar: ../../../../../usr/bin/bsdtar: Cannot open: Permission denied
> /usr/bin/tar: Exiting with failure status due to previous errors
> Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
> ```
> 
> Is this expected? Other caches seem fine.

This is not expected. I guess that's why https://stackoverflow.com/a/59277514 recommends caching to a different folder.

**Comment by Eeems** [comment]
@matteodelabre Okay, resolved. That seems to bring us down to ~25s. I'm tempted to say that we should cache the entire python environment to see how much time we save. Thoughts?

**Comment by matteodelabre** [comment]
> I'm tempted to say that we should cache the entire python environment to see how much time we save. Thoughts?

We’re now at ~17 s with the whole Python environment cached.

**Comment by Eeems** [comment]
Looks like that got us under 20s

**Review by matteodelabre — APPROVED** [review]
Looks good! If/when we implement toltec-dev/build#7 we should remember to add it to the workflow cache.

**Pull request merged**
