### PR TITLE
[TilEm][0.0.6] New Package

### PR DESCRIPTION
**Pull request by timower**
Adds tilem, my port of the ti calculator emulator.
Currently only support ti84+. It should popup to download a ROM file if none is available.

### CODE REVIEW

**Review by LinusCDE — CHANGES_REQUESTED** [review]
Tested on both rM 2 and 1. On both, I get the dialog to download the ROM, but afterwards it doesn't accept any input anymore. Logs don't seem to indicate any error. Did I miss something to get it running properly?

UI seems to look fine though:

(PNG-Grafik, 1404 × 1872 Pixel) - Skaliert (46%)

**Comment by timower** [comment]
I think you need to press ON

**Comment by LinusCDE** [comment]
Ok, my bad. 😅 Haven't used it in a while. I actually used the TI84+ in school. And often the WabbitEmu app for Android as well.

Works on rM 2. On the rM 1 the lcd is displayed wrong and not really readable:

 &nbsp;

Oxide also doesn't officially support arguments in the `call=` of draft anymore. So a wrapper script is probably necessary for proper launcher support. It is also probably more ideal to clear the background when launching (I launched from terminal here. Not sure if some launchers automatically clear the fb).

**Comment by timower** [comment]
Okay, I should've fixed the issues. I've used a commit in the package for now. If everything works I can push a new tag and update the package to use that.

I didn't use a wrapper script but just use the default path if no cmd line arg is specified. If you want to change the rom location you can create a script or provide the arg yourself.

**Comment by LinusCDE** [comment]
Works great now!

Btw I don't think you don't need the [toltec license header](https://github.com/timower/rM2-stuff/blob/8dc94a360358bf74da244beda74739663dd44741/apps/tilem/draft/tilem.draft#L1) in your draft file if it is not part of the toltec-repository.

I'll guess since you want to add the tag first, I'll wait until then and approve it afterwards. :+1:

**Comment by timower** [comment]
Done, yeah I should remove the license header. Technically I copy pasted it from the repo so it's still licensed by that license 😃

**Review by LinusCDE — APPROVED** [review]

**Pull request merged**
