### PR TITLE
Add 7zip package

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
The licensing for 7zip is interesting. I picked LGPL for the license in the package, since that's what most of the code is under. I included the license file since parts are under BSD 3-clause and the unRAR license.

**Comment by bkirwi** [comment]
Installed from CI and tested.

```
reMarkable: ~/ /opt/bin/7zz/7zz t toltec-test/7zip_22.01-1_rmall.ipk 

7-Zip (z) 22.01 (armt) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 32-bit arm_v:7 thumb:2 locale=C UTF8=- Threads:2

Scanning the drive for archives:
1 file, 962413 bytes (940 KiB)

Testing archive: toltec-test/7zip_22.01-1_rmall.ipk
--
Path = toltec-test/7zip_22.01-1_rmall.ipk
Type = gzip
Headers Size = 10

Everything is Ok         

Size:       972800
Compressed: 962413
```

I feel like that install path is not quite right... among other things it means the binary is not in PATH. Otherwise seems to be working as expected.

**Comment by Eeems** [comment]
Thanks for the rest, I must have messed up the paths when copying/pasting from other packages.

Where did the license file end up?

**Comment by bkirwi** [comment]
```
reMarkable: ~/ opkg files 7zip
Package 7zip (22.01-1) is installed on root and has the following files:
/opt/bin/7zz/7zz
/opt/usr/share/licenses/7zip/License.txt
```

License location seems reasonable to me!

**Review by bkirwi — APPROVED** [review]

**Comment by Eeems** [comment]
> ```
> reMarkable: ~/ opkg files 7zip
> Package 7zip (22.01-1) is installed on root and has the following files:
> /opt/bin/7zz/7zz
> /opt/usr/share/licenses/7zip/License.txt
> ```
> 
> License location seems reasonable to me!

I need to re-familiarize myself with the `install` doc. I never know when it wants a path to be the filename, and when it wants it to be a folder.

Thanks for the test!

**Review by raisjn — APPROVED** [review]

**Pull request merged**
