### PR TITLE
Micro text editor

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by Eeems** [comment]
I wonder if it would be better to install the licenses into `/opt` to avoid having to reinstall them, or filling up the root partition?

**Comment by Eeems** [comment]
> I wonder if it would be better to install the licenses into `/opt` to avoid having to reinstall them, or filling up the root partition?

I've moved it to `/opt` and also added back the man pages in case the user installs `man-pages`

**Comment by Eeems** [comment]
Test scenarios:

1. Run `micro` and make sure it works.
2. Install `man-pages` and ensure that you can run `man micro`.

**Review by LinusCDE — APPROVED** [review]
Works well :+1:

**Pull request merged**
