### PR TITLE
Stable merge for week 29 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
Important notices:

* When upgrading, users should run `opkg update && opkg upgrade` **twice** because of the changes introduced by this merge. (#310)
* Toltec **no longer supports** OS releases **earlier than 2.6**. You can check your current OS version in the settings panel. If you’re still running on 2.5 or earlier, please upgrade to 2.6 or newer after upgrading your Toltec install. (#366)

Less important notices:

* To re-enable Toltec after a system upgrade, **run `toltecctl reenable`** instead of the previous `entware-reenable` script that has been removed with this update.
* You can now easily uninstall Toltec by running `toltec uninstall`.
* This release marks the end of our work towards transitioning to a new repository layout. This means that **stable will be updated more frequently from now on.** If you switched to the testing branch because stable has been outdated for a few months, and if you prefer to run stable releases, you can go back to the stable branch by running `toltecctl switch-branch stable`.

Layout change: The repository is now split into architecture subfolders. The `rmall` subfolder contains packages that can run both on reMarkable 1 and reMarkable 2 without modification. The `rm1` and `rm2` subfolders contain packages that are specific to each of the two devices. This change requires updating the Opkg configuration to point to the appropriate architectures. The migration is automated by placing an upgrade to the `toltec-bootstrap` package in the root folder of the repo that contains a migration script.

New packages:

* bash-completion - 2.11-3 (#277, #375)
* display - 1.0.1-7 _(replaces the server part of the old rm2fb package)_ (#310)
* fuse - 1.0.0-3 (#331)
* gocryptfs - 2.0-beta2 (#318)
* innernet-client - 1.3.1-2 (#350, #358, #361)
* netsurf - 0.4.0-2 (#339)
* puzzles - 0.2.2-3 (#326)
* remarkable-stylus - 0.0.3-1 (#383)
* rm2fb-client - 1.0.1-7 _(replaces the client part of the old rm2fb package)_ (#310)
* tilem - 0.0.7-2 (#352)
* toltec-completion - 0.2.0-1 (#277)
* yaft - 0.0.4-4 (#261, #353)
* zoneinfo-utils - 2021a-2 (#182)

Updated packages:

* appmarkable - 0.0.0-11
* bufshot - 0.1.0-5
* calculator - 0.0.0-15
* chessmarkable - 0.8.0-1 (#362, #373, #392)
* ddvk-hacks - 23.02-1 (#385)
* draft - 0.2.0-20
* evtest - 1.34-3
* fbink fbdepth fbink-doom - 1.23.2-1 (#387)
* fingerterm - 1.3.5-14
* genie - 0.1.5-3
* harmony - 0.1.3-3
* iago - 0.1.0-4
* keywriter - 0.1.0-3
* koreader - 2021.07-1 (#330, #348, #357, #378, #389)
* lamp - 0.1.0-4
* libdlib libdlib-dev - 19.21-2
* libvncserver libvncclient libvncserver-dev - 0.9.13-2
* mines - 0.1.2-4
* nao - 0.1.3-3
* oxide erode fret rot tarnish decay corrupt anxiety - 2.2-1 (#382)
* plato - 0.9.17-2 (#344)
* quickjs - 2020.11.08-2
* recrossable - 0.0.0-7
* remarkable-splash - 1.0-5
* remux - 0.1.9-4
* restream - 1.1-2
* retris - 0.6.3-3
* rmservewacominput - 0.3.0-2
* simple - 0.1.4-3
* templatectl - 0.1.3-3
* toltec-bootstrap - 0.1.0-1 _(includes toltecctl)_ (#379)
* vnsee - 0.4.0-2 (#355)
* wikipedia - 0.1.0-3
* wireguard - 1.0.20210219-2
* xochitl - 0.0.0-7 (#383, #382, #386)
* zshelf - 0.3.1-3

Website: The source files and scripts used for generating the website have been transferred to a separate repository (<https://github.com/toltec-dev/web>). A website rebuild is triggered automatically from this repository’s workflow when the stable branch is updated, so that the displayed checksum of the bootstrap script is always accurate.

### CODE REVIEW

**Comment by matteodelabre** [comment]
The build artifacts are hosted at <https://toltec-dev.org/stable-next> to facilitate testing. Starting from an existing stable install, edit `/opt/etc/opkg.conf` and replace `https://toltec-dev.org/stable` with `https://toltec-dev.org/stable-next` to simulate the roll-out of this merge.

**Comment by matteodelabre** [comment]
Testing on rM2, version 2.8:

* ~~`puzzles`: When starting a game or when the program tries to autosave, I can see a line saying that it can’t read or write in `/opt/etc/puzzles/save`. The game state is therefore not restored as it should when exiting and re-entering a game. This can be fixed by creating the `/opt/etc/puzzles/save` folder (although it might make more sense to store this in `~/.cache`?) (#394).~~
* ~~`netsurf`: Is missing the rm2fb ELF patch, so running it directly from a SSH session without prefixing it with `rm2fb-client` doesn’t work (#395).~~
* `tilem`: Is downloading the TI ROM over HTTP, it might be better to use HTTPS here. Also it would be advisable to store the ROM and the state saves outside of the `/home/root` folder so that it doesn’t get too crowded. (timower/rM2-stuff#7)
* ~~`fbink`, `fbdepth`, & `fbink-doom`: Are missing the rm2fb ELF patch too, it seems. At least, I couldn’t make them work without prefixing them with `rm2fb-client` (fixed in #387).~~
* `harmony`: I get a SIGABRT when I open the `Load` menu if it contains previously saved images (rmkit-dev/rmkit#136).
* ~~`remux`: I can’t start Xochitl (blank screen) (rmkit-dev/rmkit#135).~~

Not tested:

* `innernet` (couldn’t make it work, but this is probably because I don’t know enough about innernet itself)
* `remarkable-stylus` (I don’t have a Lamy pen)

**Comment by Eeems** [comment]
Some of these issues I would consider blockers. Have you opened issues for any of them yet?

**Comment by Eeems** [comment]
@raisjn any ideas on what's happening with remux?

**Comment by matteodelabre** [comment]
> Some of these issues I would consider blockers. Have you opened issues for any of them yet?

Not yet, but I plan to do it very soon. I’ll add links in my previous comment when they are open.

**Comment by matteodelabre** [comment]
> any ideas on what's happening with remux?

This only happens when running remux directly from the command line instead of as a systemd service. So it’s not a major bug if we expect that most users will use it as a service.

**Comment by Eeems** [comment]
> > any ideas on what's happening with remux?
> 
> This only happens when running remux directly from the command line instead of as a systemd service. So it’s not a major bug if we expect that most users will use it as a service.

Ah, so I'm guessing it's just missing environment variables. If it's working fine as a service, which is the expected use-case, I no longer consider this a blocker.

**Comment by raisjn** [comment]
> This only happens when running remux directly from the command line instead of as a systemd service. So it’s not a major bug if we expect that most users will use it as a service.

what is the bug? is it something to do with rm2fb or something in remux's env variable setup? i'd prefer not to ship bug if we can avoid it (because down the line will still have to field this request of 'broken remux' but have even less details)

**Comment by Eeems** [comment]
> 
> what is the bug? is it something to do with rm2fb or something in remux's env variable setup? i'd prefer not to ship bug if we can avoid it (because down the line will still have to field this request of 'broken remux' but have even less details)

From https://github.com/toltec-dev/toltec/pull/391#issuecomment-886076197

>
>  * `remux`: I can’t start Xochitl (blank screen) [EDIT: Only when run directly from the command line instead of as a service.]

Since this is likely a pre-existing issue, I'm not as concerned about shipping it, especially since it's better than shipping nothing and having stable remain "broken".

**Comment by matteodelabre** [comment]
The remux bug proved difficult to consistently reproduce, but in the end it can happen regardless of whether remux is running as a service or not. I opened a bug report with more details: https://github.com/rmkit-dev/rmkit/issues/135

**Comment by Eeems** [comment]
So what is remaining to be tested? I think the primary focus should be for testing the upgrade of apps from existing stable installs to make sure they still work.

**Comment by matteodelabre** [comment]
I’ve only tested on rM2 so far, we would also need to confirm that everything works on rM1.

**Comment by matteodelabre** [comment]
Also, shall we take this opportunity to change the rM2 support badge to “supported” on the README? I think rM2 support is pretty much on par with rM1 support now.

**Comment by Eeems** [comment]
> Also, shall we take this opportunity to change the rM2 support badge to “supported” on the README? I think rM2 support is pretty much on par with rM1 support now.

I agree

**Comment by Eeems** [comment]
Alright, has anyone done an upgrade from stable with this on a rM1 yet?

**Comment by matteodelabre** [comment]
Not yet. Just updated https://toltec-dev.org/stable-next with a new build of this branch, by the way.

**Comment by matteodelabre** [comment]
Completed testing on rM1. The only issue I found is the following: after installing `gocryptfs` and `fuse`, I needed to manually run `modprobe fuse` before `gocryptfs path/` would work. Wasn’t the `depmod -a` command included in the configure script of the `fuse` package meant to automate this?

**Comment by Eeems** [comment]
> 
> 
> Completed testing on rM1. The only issue I found is the following: after installing `gocryptfs` and `fuse`, I needed to manually run `modprobe fuse` before `gocryptfs path/` would work. Wasn’t the `depmod -a` command included in the configure script of the `fuse` package meant to automate this?

It is meant to automate the module loading. It might not work at updating a module that's already been loaded though.

**Comment by matteodelabre** [comment]
This happens when first installing the module, without it being loaded first.

**Comment by Eeems** [comment]
> 
> 
> This happens when first installing the module, without it being loaded first.

Very odd. I do seem to remember that it was working last I tested.

**Comment by matteodelabre** [comment]
I think we need to run `systemctl restart kmod-static-nodes && systemctl restart systemd-tmpfiles-setup-dev` after `depmod -a` in the configure() script so that `/dev/fuse` gets created. Once `/dev/fuse` is present, the kernel module will get automatically loaded whenever a program tries to access that device (see #405).

**Comment by Eeems** [comment]
It probably isn't needed for the stable merge for now. Anything else outstanding? Or should I approve the PR?

**Comment by matteodelabre** [comment]
Since it’s a rather simple fix that I’ve confirmed to work I’d rather add it to this merge, if you don’t mind. This may save us some user reports that the module doesn’t work.

**Comment by matteodelabre** [comment]
This being done, I think we’re ready for the merge.

**Review by Eeems — APPROVED** [review]
⛵it!

**Pull request merged**
