### PR TITLE
Stable merge window for week 02 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
Tooling changes:

* Make `stable` the default branch.
* Strip binaries by default.
* Use `systemctl is-enabled` instead of `systemctl list-unit-files` to see whether a unit is enabled or not.

~~Installer changes:~~

* ~~Improve migration path from remarkable\_entware regarding the location of the `opt.mount` configuration file.~~
* ~~Keep existing branch configuration if an install of Toltec already exists.~~

Updated packages (not listing the packages that were only updated because of the strip changes):

* chessmarkable 0.5.1-1 → 0.6.0-2
* koreader 2020.10-2 → 2020.12-2
* oxide 2.0.1\~beta-3 → 2.0.3\~beta-1
* fret 2.0.1\~beta-3 → 2.0.3\~beta-1
* tarnish 2.0.1\~beta-3 → 2.0.3\~beta-1
* erode 2.0.1\~beta-3 → 2.0.3\~beta-1
* rot 2.0.1\~beta-3 → 2.0.3\~beta-1
* rm2fb 1.0.0-3 → 1.0.0-5
* remux 0.1.4-1 → 0.1.5-1

New packages:

* keywriter 0.1.0-1
* restream 0.0.0-1
* rm2-suspend-fix 0.0.0-1
* genie 0.1.0-1

### CODE REVIEW

**Comment by raisjn** [comment]
remux was updated to 0.1.5-1 (should be added to release notes)

**Comment by matteodelabre** [comment]
Whoops, sorry about that. Should be fixed now.

**Comment by raisjn** [comment]
usually, the 'repo.zip' appears in the checks section. after the KOReader commit push, that disappeared but is accessible by selecting the previous commit in the checks section. maybe this is an issue with the github workflow?

**Comment by raisjn** [comment]
tested (on rM2):

* chessmarkable: rotatable board works, but hard mode is slow. first move of PC took 15s, then 30+s
* rm2fb: re-installing causes the display to go white because rm2fb doesn't persist display
* remux: re-installed, restarted. three-finger tap gesture works
* genie: re-installed, tested by modifying genie.conf and verifying gestures work
* oxide: re-installed - tested oxide UI, its much snappier to open apps and menus. going to suspend does not show suspend screen, but does properly suspend/wake.
* rm2-suspend-fix: i have tarnish + rm2-suspend-fix running and wifi works after sleep/wake cycles 


untested:

* restream - 
* keywriter -

**Comment by Eeems** [comment]
Hmm, v2.0.3 is suppose to fix the suspend screen in oxide. Could you replicate with v2.1 as well?

Also, a better test of the suspend fix would be without tarnish running as it also has the same rmmod/modprobe code.

**Comment by LinusCDE** [comment]
> untested:
>
>    restream -
>    keywriter -

Both re-tested to work on rm1. :+1: 

> chessmarkable: rotatable board works, but hard mode is slow. first move of PC took 15s, then 30+s

The slowness of the hard mode is normal. It is basically trying to be neigh unbeatable with has a lot of number crunching to do. It should most not get slower after the first few moves. On the rM 2 it should also be faster than on the rM 1 since it uses a different algorithm that can take advantage of both cores. I never got that verified though.

**Comment by raisjn** [comment]
I just tested oxide again (but made sure to install tarnish+fret+erode 2.0.3~beta1) and suspend works properly

**Comment by raisjn** [comment]
To get the repo.zip for the KOReader commit, can go to `checks`, then find the `builds correctly` subtask and the artifact will be attached to that.

**Review by raisjn — DISMISSED** [review]
lgtmacro

**Comment by matteodelabre** [comment]
I’m getting the following output with the bootstrap script from this PR. The one in `stable` works fine.

```
cat: can't open '/home/root/.entware/etc/opkg.conf': No such file or directory
INFO:  Fetching secure wget
INFO:  Creating /home/root/.entware and mounting to /opt
INFO:  Updating opt.mount location
Failed to get unit file state for opt.mount: No such file or directory
rm: can't remove '/etc/systemd/system/opt.mount': No such file or directory
ERROR: Unexpected error on line bootstrap:141 in function entware-mount
umount: can't unmount /opt: Invalid argument
```

Can someone else confirm?

**Review by raisjn — DISMISSED** [review]

**Comment by matteodelabre** [comment]
Finished testing on my rM1. No more issues to report.

**Review by Eeems — APPROVED** [review]

**Pull request merged**
