### PR TITLE
Add icon for wikipedia and bump version to 0.1.0-2

### PR DESCRIPTION
**Pull request by dps**
Adds an icon, which is the [Wikipedia affiliative mark](https://commons.wikimedia.org/wiki/File:Wikipedia_affiliative_mark.png). The file has been cropped by dps for reMarkable and is otherwise unedited.

This artwork is under a Creative Commons Attribution-Share Alike 3.0 Unported license.
Per https://commons.wikimedia.org/wiki/File:Wikipedia_affiliative_mark.png and
https://foundation.wikimedia.org/wiki/Trademark_policy

It is appropriate for this use as it will link directly to official wikipedia content.

### CODE REVIEW

**Comment by matteodelabre** [comment]
Does this PR replace #309?

**Comment by dps** [comment]
Yes, it can.

**Review by danshick — APPROVED** [review]
LGTM

**Review by Eeems — APPROVED** [review]
lgtm

**Pull request merged**
