### PR TITLE
Update wget to use v1.21.1-1

### LINKED ISSUE #731: Bootstrap does not work on 3.6.0.1865 due to segmentation fault
**To Reproduce**
Steps to reproduce the behaviour:
1. SSH into Remarkable 2
2. Run Toltec installation command: `wget http://toltec-dev.org/bootstrap
echo "04a28483286f88c5c7f39e352afb62adc57f6162a29fd7e124d832205bb0980e  bootstrap" | sha256sum -c && bash bootstrap`
3. Get the following error: `INFO:  Fetching secure wget
INFO:  Bootstrapping Opkg
bootstrap: line 119:   400 Segmentation fault      wget --no-verbose "$entware_remote/opkg" --output-document "$opkg_path"
ERROR: Could not fetch opkg, make sure you have a stable Wi-Fi connection`

**Expected behaviour**

**Screenshots**

**Device information (please complete the following information):**
 - Device: Remarkable 2
 - OS version: 5.4.70-v1.3.4-rm11x

**Additional context**

The Wifi-connection of the RM2 is perfectly working, I was able to download Bootstrap.

### PR DESCRIPTION
**Pull request by Eeems**
Update bootstrap to use partial static compiled version due to issues with glibc not being safe to static compile: https://github.com/toltec-dev/bootstrap/pull/2

Fixes #731

### CODE REVIEW

**Comment by Eeems** [comment]
This is currently blocked until @matteodelabre can update the secrets in the bootstrap repo so that the sync to push the built file is fixed.

**Comment by robfox92** [comment]
How did you compile wget 1.21.1-1? It seems like this will take a little while to get merged, so I'm happy enough to build it myself and skip the download step in the bootstrap script.

**Comment by Eeems** [comment]
> How did you compile wget 1.21.1-1? It seems like this will take a little while to get merged, so I'm happy enough to build it myself and skip the download step in the bootstrap script.

You can find the build here: https://github.com/toltec-dev/bootstrap/actions/runs/6804417921

**Comment by Eeems** [comment]
The bootstrap repo has been fixed, so this is ready for testing.

**Comment by Eeems** [comment]
Superseded by #860

**Pull request closed without merging**
