### PR TITLE
Stable merge window for week 47 of 2023

### PR DESCRIPTION
**Pull request by Eeems**
### New Packages
- `template-daily-planner`, `template-weekly-planner`, `template-journal`, `template-meeting-notes`, `template-smart-goals`, and `template-good-time-journal` - 0.0.0-1 (#712)
- `splashscreen-starting-wavey-lines`, `splashscreen-suspended-wavey-lines`, `splashscreen-poweroff-gallifreyan`, `splashscreen-suspended-gallifreyan`, `splashscreen-suspended-gallifreyan-dark`, `splashscreen-starting-gallifreyan`, `splashscreen-suspended-gallifreyan-2`, `splashscreen-suspended-flower-pause`, `splashscreen-batteryempty-barnsley_fern`, `splashscreen-poweroff-barnsley_fern`, `splashscreen-starting-barnsley_fern`, `splashscreen-suspended-barnsley_fern`, `splashscreen-batteryempty-chaotic_ribbon`, `splashscreen-poweroff-chaotic_ribbon`, `splashscreen-starting-chaotic_ribbon`, `splashscreen-suspended-chaotic_ribbon`, `splashscreen-batteryempty-collatz_sea_weed`, `splashscreen-poweroff-collatz_sea_weed`, `splashscreen-starting-collatz_sea_weed`, `splashscreen-suspended-collatz_sea_weed`, `splashscreen-batteryempty-dragon_curve`, `splashscreen-poweroff-dragon_curve`, `splashscreen-starting-dragon_curve`, `splashscreen-suspended-dragon_curve`, `splashscreen-batteryempty-fire`, `splashscreen-poweroff-fire`, `splashscreen-starting-fire`, `splashscreen-suspended-fire`, `splashscreen-batteryempty-fractal_tree`, `splashscreen-poweroff-fractal_tree`, `splashscreen-starting-fractal_tree`, `splashscreen-suspended-fractal_tree`, `splashscreen-batteryempty-sacks_spiral`, `splashscreen-poweroff-sacks_spiral`, `splashscreen-starting-sacks_spiral`, `splashscreen-suspended-sacks_spiral`, `splashscreen-batteryempty-sierpinski_triangle`, `splashscreen-poweroff-sierpinski_triangle`, `splashscreen-starting-sierpinski_triangle`, `splashscreen-suspended-sierpinski_triangle`, `splashscreen-batteryempty-snowy_hills`, `splashscreen-poweroff-snowy_hills`, `splashscreen-starting-snowy_hills`, `splashscreen-suspended-snowy_hills`, `splashscreen-batteryempty-starr`, `splashscreen-poweroff-starr`, `splashscreen-starting-starr`, and `splashscreen-suspended-starr` - 0.0.0-1 (#724)
  - Installing a splashscreen will automatically enable it
  - Removing a splashscreen will automatically revert to the previous splashscreen

### Updated Packages
- `toltec-bootstrap` - 0.2.3-1 (#740)
- `rmfm` - 1.5.0-2 (#700 #746)
- `whiteboard-hypercard` - 0.3.7-2 (#700 #747)
- `yaft` - 0.0.10-2 (#700 #736)
- `xochitl` - 0.0.0-16 (#700 #707)
- `reboot-guard` - 1.0.1-7 (#689)
- `calculator` - 0.0.0-16 (#700)
- `chessmarkable` - 0.8.0-2 (#700)
- `doomarkable` - 0.4.1-2 (#700)
- `fingerterm` - 1.3.5-15 (#700)
- `keywriter` - 0.2~20-gddc9e73-2 (#700)
- `koreader` - 2023.08-2 (#700)
- `netsurf` - 0.4.0-3 (#700)
- `erode`, `fret`, `oxide`, `rot`, `tarnish`, `decay`, `corrupt`, `anxiety`, `oxide-utils`, `inject_evdev`, and `liboxide` - 0.2.6-2 (#700 #745)
- `plato` - 0.9.34-2 (#700)
- `puzzles` - 0.2.2-4 (#700)
- `recrossable` - 0.0.0-8 (#700)
- `regenda` - 0.0.2-2 (#700)
- `reterm` - 20230628.1927-2 (#700)
- `retris` - 0.6.3-4 (#700)
- `dumbskull` - 0.0.1-3 (#700)
- `harmony` - 0.2.2-2 (#700)
- `mines` - 0.1.4-3 (#700)
- `nao` - 0.1.2-4 (#700)
- `rpncalc` - 0.0.3-3 (#700)
- `wordlet` - 0.0.2-3 (#700)
- `sill` - 0.1.1-1 (#700)
- `vnsee` - 0.4.1-2 (#700)
- `wikipedia` - 0.1.0-4 (#700)
- `zshelf` - 0.4.0-4 (#700)
- `changescrn` - 1.0.0-2 (#724)

### Tooling
- Packages that contain files in `/opt/etc/draft` or `/opt/usr/share/applications` will now automatically reload oxide applications as part of install, upgrade, and remove.

### Documentation
- Add documentation for the reload-oxide-apps hook.
- Update category list to include the new splashscreens category.

### Known Issues
- lowbattery and starting splashscreens don't work since they need to be in a specific bmp format and put in `/var/lib/uboot` (https://github.com/pr0fsmith/rMscreens/issues/7)
- Installing two splashscreens of the same type will error instead of replacing the previously installed splashscreen (#761)
- Fingerterm icon is incorrect (#762)

### CODE REVIEW

**Comment by Eeems** [comment]
- [x] Include #700
- [x] Update description with list of changes
- [x] Test everything on rM1
- [ ] Test everything on rM2

**Comment by Eeems** [comment]
**Testing**
- Copied rm1/rmall folders to device, added new file named `/opt/etc/opkg.conf.d/16-local.conf` with the following content:
  ```
  src/gz local-rmall file:///home/root/packages/local/rmall
  src/gz local-rm1 file:///home/root/packages/local/rm1
  ```
- Ran `toltecctl generate-opkg-conf` to generate the new `opkg.conf` file.
- Tested installing packages and ensured they installed as expected
- Quick smoke test of the packages to ensure that they work as expected

**Issues**

- For some reason fingerterm's icon is 
  fingerterm
  instead of
  fingerterm
  Not entirely sure why this is happening.

**Comment by Jayy001** [comment]
| Name                          | Launches | Working as intended?                                                                                                                   | Pass |
|-------------------------------|----------|----------------------------------------------------------------------------------------------------------------------------------------|------|
| Keywriter                     | OK       | Able to open up command-prompt and type in commands. Input is recognised however no content shows up on the device. (Can attach video) | NO   |
| Harmony                       | OK       | YES                                                                                                                                    | YES  |
| NetSurf                       | OK       | YES                                                                                                                                    | YES  |
| chessMarkable                 | OK       | YES                                                                                                                                    | YES  |
| whiteboard                    | OK       | YES                                                                                                                                    | YES  |
| yaft                          | OK       | YES (Switches automatically from horizontal -> Vertical)                                                                               | YES  |
| xochitl                       | OK       | YES                                                                                                                                    | YES  |
| DOOMarkable                   | FAIL     | "If you see this screen, then the game probably didn't start"                                                                          | NO   |
| Dumbskull                     | OK       | YES                                                                                                                                    | YES  |
| reboot-guard                  | OK       | YES (No functional change)                                                                                                             | YES  |
| Changescrn                    | OK       | YES                                                                                                                                    | YES  |
| Update-Desktop-Database-Oxide | OK       | YES (Working as intended)                                                                                                              | YES  |
| Templates                     | OK       | YES                                                                                                                                    | YES  |
| Fingerterm                    | OK       | YES (Functionality OK! But, Icon is like the one which Eeems got)                                                                      | NO   |

Apart from Fingerterms icon, keywriter content not showing up and doomarkable not loading, everything works fine!

**Review by Jayy001 — APPROVED** [review]

**Comment by Jayy001** [comment]
Just tested on 2.15.1.1189 - all working well. The only weird thing I encountered was this new section that doesn't display anything when selected.
```
Dec 06 16:03:42 reMarkable xochitl[1533]: 16:03:42.234 default                  qrc:/qml/device/view/settings/Settings.qml:242: ReferenceError: menuItem is not defined (qrc:/qml/device/view/settings/Settings.qml:242)
Dec 06 16:03:48 reMarkable xochitl[1533]: 16:03:48.775 default                  qrc:/qml/device/view/settings/Settings.qml:241: ReferenceError: menuItem is not defined (qrc:/qml/device/view/settings/Settings.qml:241)
Dec 06 16:03:53 reMarkable xochitl[1533]: 16:03:53.134 default                  qrc:/qml/device/view/settings/Settings.qml:241: ReferenceError: menuItem is not defined (qrc:/qml/device/view/settings/Settings.qml:241)
Dec 06 16:04:00 reMarkable xochitl[1533]: 16:04:00.426 rm.network.notifications Notification error:  QAbstractSocket::RemoteHostClosedError "The remote host closed the connection" 1000 ""
Dec 06 16:05:12 reMarkable xochitl[1533]: 16:05:12.877 default                  qrc:/qml/device/view/settings/Settings.qml:241: ReferenceError: menuItem is not defined (qrc:/qml/device/view/settings/Settings.qml:241)
```

**Comment by Jayy001** [comment]
IMG_20231206_160502

**Pull request merged**
