### PR TITLE
Add package for wireguard-tools

### PR DESCRIPTION
**Pull request by Etn40ff**
This PR adds the required binaries to use the wireguard module installed via `linux-stracciatella` (or by any other mean).

This new package, together with #742, supersedes the package `wireguard`.

### CODE REVIEW

**Review by Eeems — CHANGES_REQUESTED** [review]
Since this supersedes the wireguard package, it will need to indicate as such. We currently have `replaces` and `conflicts` for this. #600 also adds `provides` support, which I think would be preferable here. You can mark this as `conflicts` with `wireguard`, as well as update the `wireguard` package to provide `wireguard-tools`.

For #600, I just need someone to let me know that it works on a rM2 and I can merge it as I tested on my rM1.

**Comment by Etn40ff** [comment]
Still waiting on #600

**Comment by Eeems** [comment]
> Still waiting on #600 

You could pull the changes required from that PR into this.

**Comment by Eeems** [comment]
```shell
reMarkable: ~/ opkg install wireguard
Installing wireguard (1.0.20210219-3) to root...
Downloading https://toltec-dev.org/testing/rmall/wireguard_1.0.20210219-3_rmall.ipk
Configuring wireguard.
reMarkable: ~/ cd ./packages/
reMarkable: ~/packages/ opkg install ./wireguard-tools_1.0.20210914-1_rmall.ipk 
Installing wireguard-tools (1.0.20210914-1) to root...
Collected errors:
 * check_conflicts_for: The following packages conflict with wireguard-tools:
 * check_conflicts_for: 	wireguard * 
 * opkg_install_cmd: Cannot install package wireguard-tools.
reMarkable: ~/packages/ opkg remove wireguard
Removing package wireguard from root...
Wireguard has been removed.
The kernel module will remain loaded until you reboot, or you can attempt
to manually remove it by running "modprobe -r wireguard".
reMarkable: ~/packages/ opkg install ./wireguard-tools_1.0.20210914-1_rmall.ipk 
Installing wireguard-tools (1.0.20210914-1) to root...
Configuring wireguard-tools.
```
Looks like it works as expected

**Review by Eeems — APPROVED** [review]

**Pull request merged**
