### PR TITLE
[restream][1.1] - Updated Package

### PR DESCRIPTION
**Pull request by danshick**
Official release notes state:
```
- low-latency streaming of the reMarkable framebuffer
- support for reMarkable generation 1 and 2
- POSIX shell on host machine supporting linux, mac and windows
- Rust executable on reMarkable
```

It should be noted that the only actual code changes that took place since the version we most recently packaged were:
```
- Disable password authentication for ssh
- Add warning message on ssh failure
```

Both of these changes took place on the computer side script, so the real advantage of this update is to start building against the tagged releases instead of individual commits, and to update the toolchain version.

### CODE REVIEW

**Comment by danshick** [comment]
I think it is also worth mentioning here that https://github.com/rien/reStream/pull/41 has not been accepted yet, so we are still unable to remove the conflict with rm2fb.

**Comment by Eeems** [comment]
> 
> 
> I think it is also worth mentioning here that [rien/reStream#41](https://github.com/rien/reStream/pull/41) has not been accepted yet, so we are still unable to remove the conflict with rm2fb.

:(

**Comment by rien** [comment]
I've created a new release: https://github.com/rien/reStream/releases/tag/1.1

The rust binary `restream.rs` and the script `restream.sh` now follow the same versions to avoid confusion.

**Comment by matteodelabre** [comment]
I updated the version and took the liberty to remove the duplication of the version number in the source array. I also removed the part of the configure message that asks the user to link `/home/root/restream` to `/opt/bin/restream` since restream supports the standard Toltec location if I’m not mistaken.

**Comment by danshick** [comment]
> I've created a new release: https://github.com/rien/reStream/releases/tag/1.1
> 
> The rust binary `restream.rs` and the script `restream.sh` now follow the same versions to avoid confusion. 

Thanks for the new release and for including rm2fb support!

**Comment by danshick** [comment]
> I updated the version and took the liberty to remove the duplication of the version number in the source array. I also removed the part of the configure message that asks the user to link `/home/root/restream` to `/opt/bin/restream` since restream supports the standard Toltec location if I’m not mistaken.

Both changes look good to me. /opt/bin was added in my PR, so that message can be safely removed. I've also removed the rm2fb conflict!

Edit:

We can also update the release notes I mentioned above to include everything in the official 1.1 release message. Should that be duplicated here for inclusion?

**Review by matteodelabre — APPROVED** [review]
Tested and confirmed to work on rM1 and rM2.

**Comment by 1ykos** [comment]
I did install `restream` from toltec-testing and linked `/root/restream` to `/opt/bin/restream` but I'm getting an error message when running `./reStream.sh`:
```bash
[...]
error: The following required arguments were not provided:B f=0/0   
    --height <height>
    --width <width>
    --bytes-per-pixel <bytes>
    --file <path>

USAGE:
    restream [OPTIONS] --height <height> --width <width> --bytes-per-pixel <bytes> --file <path>
[...]
```
I have no idea what the correct argument for `--file` would be, otherwise I could test more.

**Comment by danshick** [comment]
> I have no idea what the correct argument for `--file` would be, otherwise I could test more.

You should have gotten the following message when installing.

```
This app is only the device-side half of reStream. The companion script for consuming the output of this app can be found at <https://github.com/rien/reStream>.
```

**Comment by 1ykos** [comment]
That's what I did. I got `./reStream.sh` from that link and ran it, which produced the error message that I showed. The version I need is probably not in master yet. To investigate further I tried running the executable on the device directly, but I don't know what to specify in the `--file` parameter, whereas the other parameters are mostly self-explanatory.

**Comment by danshick** [comment]
> That's what I did. I got `./reStream.sh` from that link and ran it, which produced the error message that I showed.

Ah, misread your last comment.

Current master branch of reStream has this line in the script.

https://github.com/rien/reStream/blob/57dcd7ca271df898471662c1bca0b8230ecb4e65/reStream.sh#L200

$fb_file is going to depend on which version of the rM you have, and whether or not you are using rm2fb. It (and all of the other arguments to this binary) gets set earlier in the conditional block between lines 100 and 129.

> To investigate further I tried running the executable on the device directly, but I don't know what to specify in the `--file` parameter, whereas the other parameters are mostly self-explanatory.

I wouldn't recommend doing this. You'll just get a very overwhelming spam of ASCII/binary noise representing the contents of the framebuffer dumped into your console. It won't be human readable output even if it is working.

I think we need to see more of the output from `./reStream.sh` before and after the error message.

**Comment by 1ykos** [comment]
I think I was using an old version of `./reStream.sh` somehow. Another pull fixed the issue, sorry for the inconvenience and thank you all for your work! It now works with fb2 on my rm2 too.

**Pull request merged**
