### PR TITLE
Update neofetch to v1.1.0

### PR DESCRIPTION
**Pull request by rM-self-serve**
[Release Notes v1.1.0](https://github.com/rM-self-serve/neofetch-rM/releases/tag/v1.1.0)
[Repo](https://github.com/rM-self-serve/neofetch-rM/)

Add the current software version.

Screenshot_2023-12-06_11-26-01

### CODE REVIEW

**Review by Eeems — CHANGES_REQUESTED** [review]
I think it would be worth adding a `postupgrade()` step to inform users they can delete `~/.config/neofetch/config.conf` to get the latest default config. Thoughts?

**Comment by rM-self-serve** [comment]
Yes I think that is vital. I'm not sure how to see the output of postupgrade() when testing, but I believe the change should be correct.

**Comment by Eeems** [comment]
> Yes I think that is vital. I'm not sure how to see the output of postupgrade() when testing, but I believe the change should be correct.

You can install the previous version of the package from toltec, and then install the ipk file over top of it. I've had opkg get confused before after installing a newer version, but there is a file you can edit in `/opt/lib/opkg` or something that is the cache of what packages are available. You can just fix the available version number in there and then `opkg update` will properly sync the repo again for that package. I can give more explicit instructions later if you'd like on discord if you poke me. I'd have to be around my tablet to put them together.

**Comment by rM-self-serve** [comment]
Thanks I should be able to go from there! I attempted to install over the existing version of neofetch but did not see the postupgrade message.

**Comment by Eeems** [comment]
> Thanks I should be able to go from there! I attempted to install over the existing version of neofetch but did not see the postupgrade message.

I don't see the message as well. I realized that this is because pre/post upgrade scripts are only called for the old version of the package, not the new one. Configure is the only script called from the new package.
https://github.com/toltec-dev/toltec/blob/stable/docs/package.md#install-section

I guess this will need to be in `configure()`.

**Comment by Eeems** [comment]
```shell
reMarkable: ~/packages/ opkg install neofetch
Installing neofetch (0.0.0-1) to root...
Downloading https://toltec-dev.org/testing/rmall/neofetch_0.0.0-1_rmall.ipk
Configuring neofetch.
reMarkable: ~/packages/ neofetch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   root@reMarkable 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   --------------- 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   OS: Codex Linux 3.1.35-2 (dunfell) armv7l 
@@@@@@@@@@@@:^::::@@@@@@@@@@@@::::^.@   Host: reMarkable 1.0 
@@@@@@@@@@@@!B@&&&!@@@@@@@@@@5@&@#?:@   Kernel: 5.4.70 
@@@@@@@@@@@@@~@@@@@?@@@@@@@.G@@@@P@@@   Uptime: 9 days, 53 mins 
@@@@@..@.^^.@~@##@@@Y@@@@@:B&B@@@P@@@   Packages: 154 (opkg) 
@^7YG&YJ&@@!@~@P^#@@@5.@@^##:Y@@@P@@@   Shell: bash 5.0.18 
@^5@@@P77YJ@@~@G@:B@@@G.~&G.@7@@@P@@@   Terminal: /dev/pts/0 
@@7@@@J@@@@@@~@G@@.G@@@#&5.@@7@@@P@@@   CPU: Freescale i.MX6 SoloLite (Device Tree) (1) @ 996MHz 
@@7@@@J@@@@@@~@G@@@@5@@@J@@@@7@@@P@@@   Memory: 89MiB / 466MiB 
@@?@@@Y@@@@@@!@B.@@@@Y&7@@@@@G@@@B.@@   Disk (/home): 2.4G / 6.5G (39%) 
@~5GGGPJ^@@.7PGGY^@@@@@@@@@^YGGGGGY^@   Battery0: 100% [Full] 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           

reMarkable: ~/packages/ opkg install ./neofetch_1.1.0-1_rmall.ipk 
Upgrading neofetch on root from 0.0.0-1 to 1.1.0-1...
Configuring neofetch.

You may choose to remove ~/.config/neofetch/config.conf
in order to get the latest default config.
reMarkable: ~/packages/ neofetch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   root@reMarkable 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   --------------- 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   OS: Codex Linux 3.1.35-2 (dunfell) armv7l 
@@@@@@@@@@@@:^::::@@@@@@@@@@@@::::^.@   Host: reMarkable 1.0 
@@@@@@@@@@@@!B@&&&!@@@@@@@@@@5@&@#?:@   Kernel: 5.4.70 
@@@@@@@@@@@@@~@@@@@?@@@@@@@.G@@@@P@@@   Uptime: 9 days, 53 mins 
@@@@@..@.^^.@~@##@@@Y@@@@@:B&B@@@P@@@   Packages: 154 (opkg) 
@^7YG&YJ&@@!@~@P^#@@@5.@@^##:Y@@@P@@@   Shell: bash 5.0.18 
@^5@@@P77YJ@@~@G@:B@@@G.~&G.@7@@@P@@@   Terminal: /dev/pts/0 
@@7@@@J@@@@@@~@G@@.G@@@#&5.@@7@@@P@@@   CPU: Freescale i.MX6 SoloLite (Device Tree) (1) @ 996MHz 
@@7@@@J@@@@@@~@G@@@@5@@@J@@@@7@@@P@@@   Memory: 89MiB / 466MiB 
@@?@@@Y@@@@@@!@B.@@@@Y&7@@@@@G@@@B.@@   Disk (/home): 2.4G / 6.5G (39%) 
@~5GGGPJ^@@.7PGGY^@@@@@@@@@^YGGGGGY^@   Battery0: 99% [Full] 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           

reMarkable: ~/packages/ rm ~/.config/neofetch/config.conf 
reMarkable: ~/packages/ neofetch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   root@reMarkable 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   --------------- 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   OS: Codex Linux 3.1.35-2 (dunfell) armv7l 
@@@@@@@@@@@@:^::::@@@@@@@@@@@@::::^.@   Host: reMarkable 1.0 
@@@@@@@@@@@@!B@&&&!@@@@@@@@@@5@&@#?:@   Xochitl: v2.15.1.1189 
@@@@@@@@@@@@@~@@@@@?@@@@@@@.G@@@@P@@@   Kernel: 5.4.70 
@@@@@..@.^^.@~@##@@@Y@@@@@:B&B@@@P@@@   Uptime: 9 days, 53 mins 
@^7YG&YJ&@@!@~@P^#@@@5.@@^##:Y@@@P@@@   Packages: 154 (opkg) 
@^5@@@P77YJ@@~@G@:B@@@G.~&G.@7@@@P@@@   Shell: bash 5.0.18 
@@7@@@J@@@@@@~@G@@.G@@@#&5.@@7@@@P@@@   Terminal: /dev/pts/0 
@@7@@@J@@@@@@~@G@@@@5@@@J@@@@7@@@P@@@   CPU: Freescale i.MX6 SoloLite (Device Tree) (1) @ 996MHz 
@@?@@@Y@@@@@@!@B.@@@@Y&7@@@@@G@@@B.@@   Memory: 89MiB / 466MiB 
@~5GGGPJ^@@.7PGGY^@@@@@@@@@^YGGGGGY^@   Disk (/home): 2.4G / 6.5G (39%) 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   Battery0: 99% [Full] 
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                           
                                                                

reMarkable: ~/packages/ opkg remove neofetch
Removing package neofetch from root...
reMarkable: ~/packages/ rm ~/.config/neofetch/config.conf 
reMarkable: ~/packages/ opkg install ./neofetch_1.1.0-1_rmall.ipk 
Installing neofetch (1.1.0-1) to root...
Configuring neofetch.
reMarkable: ~/packages/
```

Pefect!

**Review by Eeems — APPROVED** [review]

**Pull request merged**
