### PR TITLE
Stable merge for week 40 of 2021

### PR DESCRIPTION
**Pull request by matteodelabre**
This is a small update that mainly improves support for system update 2.9.

Updated packages:

* ddvk-hacks - 24.04-1 (#439)
* display, rm2fb-client - 1:0.0.7-2 (#446)
* draft - 0.2.0-21 (#446)
* koreader - 2021.09-2 (#441)
* erode, fret, oxide, rot, tarnish, decay, corrupt, anxiety - 2.2.2-1 (#444)
* xochitl - 0.0.0-8 (#441)

### CODE REVIEW

**Comment by Eeems** [comment]
Has anybody had a chance to test?

**Comment by LinusCDE** [comment]
Want to, but would need to get install a patched rm2fb package first. I think it is better to wait for that support anyway since it is kinda vital to rm 2 users.

**Comment by Eeems** [comment]
> 
> 
> Want to, but would need to get install a patched rm2fb package first. I think it is better to wait for that support anyway since it is kinda vital to rm 2 users.

Are you running 2.10? If so you can grab the configuration file from https://github.com/toltec-dev/toltec/pull/461 and put it in `/opt/etc/rm2fb.conf`

**Comment by LinusCDE** [comment]
> Are you running 2.10? If so you can grab the configuration file from #461 and put it in /opt/etc/rm2fb.conf

Thanks, that fixed it! Didn't know that it could be overridden this way. This is awesome!

**Review by LinusCDE — APPROVED** [review]
Built and installed those packages ontop of a fresh stable installation on my rM 2.

Everything looks good to me. I only couldn't test ddvk-hacks (it rightfully told me that my version isn't supported and didn't install).

**Review by matteodelabre — COMMENTED** [review]
Tested ddvk-hacks on rM2, version 2.9.1

**Comment by Eeems** [comment]
Time to merge?

**Pull request merged**
