### PR TITLE
[rmkit][rm2] update rmkit to latest version

### PR DESCRIPTION
**Pull request by raisjn**
* apps now support rm2 with rm2fb

### CODE REVIEW

**Review by LinusCDE — DISMISSED** [review]
All sub-packages compiled and ran fine for me. Not sure if you also a rM2 owner review this as well.

**Review by LinusCDE — APPROVED** [review]
Retested remux on my rM1. Seems fine.

Btw: The harmony binary has changed (e.g. not bit-perfect producible). I don't see this as an issue, what's your opionion on this, @matteodelabre ?

**Comment by raisjn** [comment]
thanks for reviewing!

One line in a shared file (`src/rmkit/fb/fb.cpy`) was changed which would explain why harmony has a new hash. I haven't verified that harmony builds with the same signature every time, though, so I'm not sure if we expect it to.

**Comment by LinusCDE** [comment]
Ok. I don't think that we need to retest harmony then. It seemed pretty stable so far.

**Pull request merged**
